### ISSUE TITLE
Application Fee `Get` method is POST'ing a refund inappropriately

### ISSUE THREAD

**Issue by pagreczner** [stripe/stripe-go#100]
https://github.com/stripe/stripe-go/blob/master/fee/client.go#L35

Hi,

The Get method for Fee's is making a POST call to the refund endpoint, which then refunds the fee instead of returning unmodified fee information.  Is this a bug or am I misunderstanding the usecase of Get here?

It seems like there should be both a method to `Get` the data and one to `Refund` (which the Get currently does).

Docs: https://stripe.com/docs/api/go#retrieve_application_fee

Thanks for the help!

**Comment by cosn** [comment]
Clearly a bug, thanks for flagging!
