### ISSUE TITLE
Invoice line item structure missing the invoice item field

### ISSUE THREAD

**Issue by malisper** [stripe/stripe-go#1010]
In the [Stripe docs](https://stripe.com/docs/api/invoices/line_item), there's supposed to be an `invoice_item` attached to invoice line items (InvoiceLine). It appears this field is just skipped over in the structure definition. There doesn't appear to be any other way to figure out what invoice line item is associated with.

**Comment by remi-stripe** [comment]
@malisper Thanks for the report. I opened a PR in https://github.com/stripe/stripe-go/pull/1011 and will get this released tomorrow!

**Comment by remi-stripe** [comment]
@malisper This was released and fixed in 68.8.0!
