### ISSUE TITLE
Customers.Update removes coupon from Customer if called with Coupon = nil

### ISSUE THREAD

**Issue by jsignanini** [stripe/stripe-go#1016]
### Potential issue
I'm calling `Customers.Update("id", CustomerParams{ ... })` with the `CustomerParams.Coupon` field set to `nil`. If the customer previously had a Cuoupon attached to itself (not to an individual subscription), the coupon will be removed.

### Expected behavior
As per the customers update documentation [here](https://stripe.com/docs/api/customers/update):

> Updates the specified customer by setting the values of the parameters passed. Any parameters not provided will be left unchanged.

The coupon should not have been removed as it was not provided (set to `nil` / default).

Stripe Go: v62.1.2
Go: v1.13.6 darwin/amd64

**Comment by remi-stripe** [comment]
@jsignanini I tried to reproduce but if I don't set `Coupon` then it's never sent in the API. For example this code confirms the Customer still has the coupon after the update:

```
createParams := &stripe.CustomerParams{
  Coupon: stripe.String("ca0CDHGR"),
}

c, _ := customer.New(createParams)

fmt.Printf("Coupon: %v\n", c.Discount.Coupon.ID)

updateParams := &stripe.CustomerParams{
  Description: stripe.String("updated description"),
}

c2, _ := customer.Update(c.ID, updateParams)

fmt.Printf("Coupon: %v\n", c2.Discount.Coupon.ID)
```

Are you able to provide some exact steps/code to reproduce the issue?

**Comment by jsignanini** [comment]
@remi-stripe I can confirm your example does work as intended on my end, however I'm still seeing the issue on my more intricate production code.


Is there a way to remove a Coupon from a Customer programmatically besides Customers.Update?
Also, would adding the Coupon to the Customer through the dashboard make any difference?


In the meantime I'll keep trying to get you a code sample where this is happening.

**Comment by remi-stripe** [comment]
> Is there a way to remove a Coupon from a Customer programmatically besides Customers.Update?

there are two ways. You either update a customer and pass `Coupon: stripe.String("")` to explicitly unset it. Or you you can call `discount.Del()` from [here](https://github.com/stripe/stripe-go/blob/master/discount/client.go#L17)

> Also, would adding the Coupon to the Customer through the dashboard make any difference?

No that would not change anything.

> In the meantime I'll keep trying to get you a code sample where this is happening.

Sounds good! If you have an example request id (req_123) where you see the coupon being unset, I can also likely work backwards from that

**Comment by jsignanini** [comment]
@remi-stripe yes, here it is `req_LCqm6kc60Dbat3`. It appears to be a call to `discount.Del()`

**Comment by remi-stripe** [comment]
That request is a call to `/v1/subscriptions` which is when you actively create a Subscription and you're explicitly passing `Coupon: stripe.String("")` and it should not mutate the Customer

**Comment by jsignanini** [comment]
Alright, looks like I'm able to reproduce:

>
	c1, _ := customer.New(&stripe.CustomerParams{
		Coupon: stripe.String("TEST"),
	})
	fmt.Printf("Coupon: %v\n", c1.Discount.Coupon.ID)
	s1, _ := sub.New(&stripe.SubscriptionParams{
		Customer: stripe.String(c1.ID),
		Items: []*stripe.SubscriptionItemsParams{
			{
				Plan: stripe.String("some_plan"),
			},
		},
		Coupon:          stripe.String(""),
		TrialPeriodDays: stripe.Int64(1),
	})
	fmt.Printf("Subscription: %v\n", s1.ID)
	c2, _ := cutomer.Get(c1.ID, nil)
	fmt.Printf("Discount: %v\n", c2.Discount)

You'll see that now the Customer's discount (not the subscription's) has been deleted. Is this intentional? If so it's pretty confusing since as far as I understand it, setting an actual coupon through the subscription attaches it to the subscription and not to the customer.

**Comment by jsignanini** [comment]
And to clarify, we were blindly passing the empty string Coupon value on the call to `sub.New()` from the front-end assuming it would only affect that specific subscription.

**Comment by remi-stripe** [comment]
@jsignanini Okay so I looked at this more closely and this seems to be a bug in the API itself and not the Go library. I flagged internally so that we can investigate.

My advice for now is to make sure you don't send `coupon: ""` when you create the Subscription

**Comment by jsignanini** [comment]
@remi-stripe yeah, that's what we're going for. Thanks for your help!
Feel free to close this or leave if open if you wanna link it to an API issue.

**Comment by remi-stripe** [comment]
Going to close as we're working on a fix but it might take a while. Thanks a lot for taking the time to report, this is a really strange one and I'm glad we were able to narrow it down.
