### ISSUE TITLE
Mismatch between API docs and golang CLI implementation

### ISSUE THREAD

**Issue by kytrinyx** [stripe/stripe-go#103]
According to the API docs, the customer resource responds with a field `default_source` which is a string representing the ID of the payment source: https://stripe.com/docs/api#create_customer

The `Customer` type has a field `DefaultSource` which is a pointer to a `PaymentSource`: https://github.com/stripe/stripe-go/blob/master/customer.go#L43

It doesn't seem like the code would be able to unmarshal a string into an actual payment source. Am I missing a step?

**Comment by cosn** [comment]
The custom unmarshaling takes care of parsing either the ID or the object:

https://github.com/stripe/stripe-go/blob/master/payment_source.go#L120

This is the case with all expandable properties

**Comment by kytrinyx** [comment]
Ah, that makes sense. Thank you!
