### ISSUE TITLE
Unable to expand subscription on invoice

### ISSUE THREAD

**Issue by lwalen** [stripe/stripe-go#1032]
stripe-go version: v68.20.0

Since the [Invoice.Subscription](https://godoc.org/github.com/stripe/stripe-go#Invoice.Subscription) field is a `string`, it is not possible to expand the Subscription when fetching invoices.

```go
in, _ := invoice.Get("...", &stripe.InvoiceParams{
	Params: stripe.Params{
		Expand: []*string{
			ptr.String("subscription"),
		},
	},
})

// in.Subscription is just a string, so there is nothing to access.
```

Ideally this would work like [Invoice.Customer](https://godoc.org/github.com/stripe/stripe-go#Invoice.Customer) so that `in.Subscription.ID` could be used if expansion of the Subscription was not requested.

**Comment by remi-stripe** [comment]
@lwalen Thanks a lot for the report! I just released 69.0.0 to make this field expandable in the the library!
