### ISSUE TITLE
Get profile results in all the nil values being replaced with 0 and empty strings

### ISSUE THREAD

**Issue by anatoliyfedorenko** [stripe/stripe-go#1045]
GO: go1.13.6 linux/amd64

When I parse webhooks regarding profile updates, I see that DOB fields and Address fields contain nil values. 

![image](https://user-images.githubusercontent.com/8424103/76770968-d998a080-67c8-11ea-9e03-c5ed6c7fe5a3.png)

however, after unmarshalling this json into a go struct, all the nil values are being replaces with 0 values for corresponding types.... 
`"dob": {"day": 0, "year": 0, "month": 0}, "email": "", "phone": "+12364587554", "gender": "", "object": "person", "account": "acct_1GOJ1EL4yeC9sajZ", "address": {"city": "", "town": "", "line1": "", "line2": "", "state": "AL", "country": "US", "postal_code": ""}`  since the types in the struct are all non pointers, the JSON unmarshaller cannot unmarshal nils there... (https://github.com/stripe/stripe-go/blob/master/account.go#L552) 

What do people do in this situations? Should I use different structs? or make my own model that will have pointers in DOB fields for example.

**Comment by brandur-stripe** [comment]
Hey @anatoliyfedorenko! By convention in the stripe-go API library (and indeed many structs generally in Go), non-struct fields are defined as scalar types (string, int, etc.) as opposed to pointers to those types.

This can definitely be a disadvantage when working with nullable data. However, for most cases _in practice_ it should be good enough to treat the zero value of a field the same as if it wasn't provided. This is most obviously true for fields like those in DOB — 0/0/0 aren't valid days/months/years so if you see any of them then you can assume they were null. It's less obvious for the address fields, but in practice an empty string can be treated functionally the same as if a value wasn't provided.

This is a convention that we largely inherited from the Go language itself. I don't 100% agree with it in that there's certainly a distinction between a null and zero value, but it does work well enough for most intents and purposes. If you're very concerned about it, you could build your own structs as you mentioned as a possibility above.

**Comment by anatoliyfedorenko** [comment]
Thanks! trying to use them so far. In case it becomes too problematic, will go for your advice and create structs of my own.
