### ISSUE TITLE
Missing DeclineCode when creating or update the customer with the token

### ISSUE THREAD

**Issue by dmuntean** [stripe/stripe-go#1064]
Hi there,

When I'm creating or updating a customer with Customers.New() or Customers.Update() using the test card that returns "Insufficient Funds" or any other test card that results in "card_declined" Code, the value of DeclineCode is empty.

I can see the correct value of "insufficient_funds" in the Stripe Dashboard when reviewing the customer, but it is not available in the SDK.

This is very similar to #948

Go and Stripe SDK versions:
go version go1.14.2 linux/amd64
github.com/stripe/stripe-go v70.14.0+incompatible

**Comment by remi-stripe** [comment]
@dmuntean Would you be able to provide an example request id (req_123) that you see in the Dashboard? Usually creating a customer will return a 402 but there shouldn't be a `decline_code` in that case so seeing an example would help narrow things down

**Comment by dmuntean** [comment]
req_XGraxUGYMUGDEZ for update customer
req_scXSSaTzBS8VuD for create customer

**Comment by remi-stripe** [comment]
Thanks for the extra information. When I reproduce locally, `DeclineCode` is set as expected in Go. Here's my code:

```
	params := &stripe.CustomerParams{}
	params.SetSource("tok_chargeDeclinedInsufficientFunds")

	_, err := customer.New(params)

	if err != nil {
		// Try to safely cast a generic error to a stripe.Error so that we can get at
		// some additional Stripe-specific information about what went wrong.
		if stripeErr, ok := err.(*stripe.Error); ok {
			// The Err field can be coerced to a more specific error type with a type
			// assertion. This technique can be used to get more specialized
			// information for certain errors.
			if cardErr, ok := stripeErr.Err.(*stripe.CardError); ok {
				fmt.Printf("Card was declined with code: %v\n", cardErr.DeclineCode)
			} else {
				fmt.Printf("Other Stripe error occurred: %v\n", stripeErr.Error())
			}
		} else {
			fmt.Printf("Other error occurred: %v\n", err.Error())
		}
	}
```

And the output I get is:
```
Card was declined with code: insufficient_funds
```

**Comment by dmuntean** [comment]
Thanks for clarifying this.

I got confused - stripe.Error has a DeclineCode field too and that resembles JSON response structure. But I can now see the comments in the code.
https://github.com/stripe/stripe-go/blob/4f3efa91c5958010cbd36ada1622d27938fadf7b/error.go#L179-L182

Thanks again for your help!
