### ISSUE TITLE
Missing "Metadata" for "CheckoutSessionSubscriptionDataParams"

### ISSUE THREAD

**Issue by RensTillmann** [stripe/stripe-go#1092]
https://github.com/stripe/stripe-go/blob/b363a1c3d64708d837a96d32a498b59d6287ab7b/checkout_session.go#L98

**Comment by remi-stripe** [comment]
@RensTillmann This was fixed in 71.9.0. Thanks again for the report!

**Comment by RensTillmann** [comment]
@remi-stripe Thanks, you are welcome :)
