### ISSUE TITLE
unable to update beyond v70.15.0

### ISSUE THREAD

**Issue by adlmr** [stripe/stripe-go#1098]
Hello,
I'm using `github.com/stripe/stripe-go v70.15.0+incompatible` as written on go.mod and i have issues with `CheckoutSession LineItem` so i want to update to latest version.

go says:
`go get github.com/stripe/stripe-go@6cf67b3fa584: github.com/stripe/stripe-go@v1.0.4-0.20200514011123-6cf67b3fa584: invalid version: go.mod has post-v1 module path "github.com/stripe/stripe-go/v71" at revision 6cf67b3fa584`

if i put `github.com/stripe/stripe-go latest` in go.mod i get `github.com/stripe/stripe-go v70.15.0+incompatible`

**Comment by remi-stripe** [comment]
@adlmr With 71.* we started using go modules. This means that when you include stripe-go you now need to reference the major version you are depending on. This is documented [here](https://github.com/stripe/stripe-go#installation)

```
import (
    "github.com/stripe/stripe-go/v71"
    "github.com/stripe/stripe-go/v71/customer"
)
```

**Comment by ls-dac-chartrand** [comment]
I'm having the same issue.

When [I look at your docs](https://github.com/stripe/stripe-go#installation), it says I should I type:

```
go get -u github.com/stripe/stripe-go
```

When I do that I get: `go: github.com/stripe/stripe-go upgrade => v70.15.0+incompatible`

### Workaround

```
go get -u github.com/stripe/stripe-go/v71
```

**Comment by brandur-stripe** [comment]
@ls-dac-chartrand I'll get that README updated, but in modern Go, you really don't need to `go get -u` anything anymore.

If you just put the stripe-go module in one of your `require`s then do a `go build`, Go will fetch all the necessary dependencies for you automatically.

**Comment by brandur-stripe** [comment]
Pitched an amendment to the README in #1100.
