### ISSUE TITLE
TopUp Object does not include "Metadata"

### ISSUE THREAD

**Issue by nemosupremo** [stripe/stripe-go#1107]
https://github.com/stripe/stripe-go/blob/d5e092ab5fe6391f076cf2f7cde5756d346006ac/topup.go#L40

The TopUp object does not have a metadata key - although the TopUp object in the API reference supports storing and retrieving metadata.

**Comment by remi-stripe** [comment]
@nemosupremo Thanks for the report! I opened a PR to fix this and we'll release the fix tomorrow!

**Comment by remi-stripe** [comment]
This has been fixed in 71.16.0
