### ISSUE TITLE
Missing DeclineCode when CardError on `Error` top-level

### ISSUE THREAD

**Issue by luw2007** [stripe/stripe-go#1114]
The Error object has most properties top-level, also the DeclineCode. (add by #949)

like #1064 We can get `card_declined` from `CardError`.
When we print the err.(Error) object, card_declined is empty.

If Error.DeclineCode is added, it should be initialized when CardError occurs.
Otherwise, remove it.

**Comment by remi-stripe** [comment]
@luw2007 Thanks a lot for the report and opening a PR. I'm sorry for the automated bot response, it's some internal logic we have and it shouldn't have said that.

@brandur-stripe opened a separate PR to fix this while cleaning up the error deserialization logic. I just released 71.20.0 that fixes this.
