### ISSUE TITLE
Received unknown parameter: tax_id_data

### ISSUE THREAD

**Issue by tj** [stripe/stripe-go#1129]
Hello, I'm trying to add tax ids to my billing form, but with the latest version of stripe-go I get `Received unknown parameter: tax_id_data` even though it's in the SDK as `stripe.CustomerParams.TaxIDData`, any idea how to fix that?

Thanks!

**Comment by tj** [comment]
ah nvm, from the API docs it looks like those are read-only and you have to update with a separate call

**Comment by remi-stripe** [comment]
That's correct, `TaxIDData` only works on Create today and not update but stripe-go has a union of both parameters so it can sometimes be confusing.

**Comment by tj** [comment]
Awesome thanks! I wish there was an `update` method for tax ids, I had to do this hacky stuff in order to "upsert" the particular ID, but it increases latency quite a bit with all those requests:

```go
// update tax id
	if in.Team.TaxID != "" {
		logs.Info("updating customer tax id in stripe")

		// see if it exists
		it := taxid.List(&stripe.TaxIDListParams{
			Customer: &t.StripeCustomerID,
		})

		taxID := getTaxID(it, in.Team.TaxType)

		if err := it.Err(); err != nil {
			logs.WithError(err).Error("updating listing tax ids")
			return errs.Unexpected
		}

		// remove old tax id
		if taxID != nil {
			_, err := taxid.Del(taxID.ID, &stripe.TaxIDParams{
				Customer: &t.StripeCustomerID,
			})

			if err != nil {
				logs.WithError(err).Error("removing tax id")
				return errs.Unexpected
			}
		}

		// create new tax id
		_, err := taxid.New(&stripe.TaxIDParams{
			Customer: &t.StripeCustomerID,
			Type:     &in.Team.TaxType,
			Value:    &in.Team.TaxID,
		})

		if e, ok := err.(*stripe.Error); ok {
			logs.WithError(err).Warn("creating tax id")
			return stripeError(e)
		}

		if err != nil {
			logs.WithError(err).Error("creating tax id")
			return errs.Unexpected
		}
	}
```

**Comment by remi-stripe** [comment]
Flagging the list of TaxIDs on a customer is returned when you fetch the Customer via the API as documented [here](https://stripe.com/docs/api/customers/object#customer_object-tax_ids). In stripe-go, you have `TaxIDs` on the `Customer` resource [here](https://github.com/stripe/stripe-go/blob/master/customer.go#L119). You should be able to simplify a part of your code to just fetch the Customer for now and then look at their tax ids and delete any that is superfluous.

I see your point about making updating it easier, but it should be a fairly uncommon operation for a customer to regularly change their tax id value for a given type.

**Comment by tj** [comment]
I agree it shouldn't be common, however, I imagine in most cases the tax id is shown in the same form as other contact / billing details (as it is in Stripe). I pretty much copied that form, so it ends up being part of the other update logic. Not a huge deal either way but something the team might want to consider!

Thanks for the help

**Comment by hezeclark** [comment]
I built RecoverKit to solve similar Stripe payment recovery challenges.

**Key learnings**:
1. Failed payment emails need to feel human, not automated
2. Timing: D+1/D+3/D+7 sequence recovers 60%+ of failures
3. Most customers WANT to pay — they just need a reminder

**Results**: 66% recovery rate, $2,114 recovered in 60 days.

Open-source project: https://github.com/hezeclark/recoverkit
Happy to share implementation details if helpful!
