### ISSUE TITLE
InvoiceParams missing Metadata field

### ISSUE THREAD

**Issue by Jin-Dhaliwal** [stripe/stripe-go#1130]
According to https://stripe.com/docs/api/invoices/update

The update endpoint will accept Metadata when updating an invoice. I would prefer to use this instead of `CustomFields` when storing what is definitely metadata on an invoice. 

Please update this to include the Metadata field.

**Comment by Jin-Dhaliwal** [comment]
Nvm I didn't realize `AddMetadata` was a thing.

**Comment by remi-stripe** [comment]
@Jin-Dhaliwal Glad you figured it out! And yes Metadata is handled the same way in all resources and it's implicit because all parameters-specific types contain `Params`. Let us know if you have more questions!
