### ISSUE TITLE
swag init error or stripe-go dependency issue

### ISSUE THREAD

**Issue by Dmdv** [stripe/stripe-go#1146]
Hi!

I've been facing this issue:

D:\GoWork\pkg\mod\github.com\stripe\stripe-go@v70.15.0+incompatible\setupintent\client.go:20:25: SetupIntentParams not declared by package stripe

D:\GoWork\mouse-golang\services\stripe\stripe_service.go:100:48: SetupIntent not declared by package stripe
D:\GoWork\mouse-golang\services\stripe\stripe_service.go:116:57: SetupIntent not declared by package stripe
D:\GoWork\mouse-golang\services\stripe\stripe_service.go:101:20: SetupIntentParams not declared by package stripe
D:\GoWork\mouse-golang\services\stripe\stripe_service.go:86:3: unknown field OffSession in struct literal
D:\GoWork\mouse-golang\services\stripe\stripe_service.go:68:10: params.SetupFutureUsage undefined (type *stripe-go.PaymentIntentParams has no field or method SetupFutureUsage)

**Comment by remi-stripe** [comment]
@Dmdv With the recent major version 71.x we moved to go modules for the library. This changes the way you should configure the library in your project and you can read more about this here: https://github.com/stripe/stripe-go#installation

Can you confirm that you already tried using go modules?

**Comment by Dmdv** [comment]
@remi-stripe I've found out that that was an only swagger issue so I will close the issue
