### ISSUE TITLE
running go get github.com/stripe/stripe-go fetches v70

### ISSUE THREAD

**Issue by benjcal** [stripe/stripe-go#1147]
After installing the library using the official documentation (https://stripe.com/docs/api) using `go get github.com/stripe/stripe-go` and I still has structures missing (specifically `stripe.PriceListParams`)

Some digging later revealed that in my `go.mod` I had `v70.15.0+incompatible`
Looking at the README it mentions that the library should be imported and then run `go build/run/` but it seems easier to just run `go get github.com/stripe/stripe-go/v71` to install the latest version of the library.

I'm submitting this issue hoping that the api documentation as well as the README can be updated so future users can avoid the headache I went through.

Thanks for such great library guys! :+1:

**Comment by brandur-stripe** [comment]
@benjcal Thanks!

Out of curiosity, were your imports pointing to `github.com/stripe/stripe-go/v71`or `github.com/stripe/stripe-go/v71`?

I don't mind adding a line to the README with a `go get -u` invocation, but ideally we try to keep the maximum signal for the most number of users. There will be a few people in your situation, but it might be slightly more confusing to the others who aren't because the `go get -u` would be an extra step that they don't really need.

**Comment by benjcal** [comment]
Maybe backing out a little so it makes more sense.

I was following the instructions from the Stripe API reference (https://stripe.com/docs/api)
![image](https://user-images.githubusercontent.com/2781653/88959182-97e82e00-d26f-11ea-8273-006d4bc41d89.png)
There was there no mention at all of v71 or what was the right import. About the imports, I don't really manage that, my IDE (Goland) takes care of that thus it was puzzling when my IDE detected to stripe package but there were definitions missing.

Coming to the repo helped but still I think the instructions could be made clear.

So yeah, I was importing `github.com/stripe/stripe-go` because I didn't know about v71 :smiley: 

Idk about `go get -u` but just for reference, my workflow is to `go get` whatever dependency BEFORE importing it and running the  normal go commands because that allows me to use the autocomplete function.

Anyways, hope this helps!

**Comment by brandur-stripe** [comment]
@benjcal Okay, thanks for the extra detail.

I put a note in the README in #1149, although might amend that in the future again if it's confusing people.

I think the main problem that got to you is that the `go get` invocation on /docs/api is really just not right anymore in a Go Modules world. I'm really not even sure it should be there at all given that it's not strictly necessary anymore (although I take your point about IDE autocompletion being able to kick in). I'm looking into fixing that separately now.

In the meantime, I'm going to close this out. Thanks again!
