### ISSUE TITLE
Empty setup intent upon creating subscription that has trial period

### ISSUE THREAD

**Issue by arizanovj** [stripe/stripe-go#1155]
go version go1.13.5 linux/amd64
github.com/stripe/stripe-go/v71
Testing CC: 4000000000003220

I am trying to create subscription that has trial period. As stated in the documentation - https://stripe.com/docs/billing/subscriptions/overview#non-payment:  "SetupIntents are automatically created for subscriptions that don’t require an initial payment." 
What I am getting from the server as part of the created subscription is the following:

```json 
 "pending_setup_intent":{
      "application":null,
      "cancellation_reason":"",
      "client_secret":"",
      "created":0,
      "customer":null,
      "description":"",
      "id":"seti_1HEMs4BL4EAJNqH8AY5JNWxM",
      "last_setup_error":null,
      "livemode":false,
      "mandate":null,
      "metadata":null,
      "next_action":null,
      "object":"",
      "on_behalf_of":null,
      "payment_method":null,
      "payment_method_options":null,
      "payment_method_types":null,
      "single_use_mandate":null,
      "status":"",
      "usage":""
   }
```

I expect to get status=requires_action and client_secret that I can pass to stripe.confirmCardSetup, but as you can see those fields are empty.

This is my server side code:

```go
func (r repository) CreateSubscription(methodID string, customerID string, priceID string) (*stripe.Subscription, error) {
	params := &stripe.PaymentMethodAttachParams{
		Customer: stripe.String(customerID),
	}
	pm, err := paymentmethod.Attach(
		methodID,
		params,
	)
	if err != nil {
		r.logger.Error("payment method.Attach: %v %s", err, pm.ID)
		return nil, err
	}
	// Update invoice settings default
	customerParams := &stripe.CustomerParams{
		InvoiceSettings: &stripe.CustomerInvoiceSettingsParams{
			DefaultPaymentMethod: stripe.String(pm.ID),
		},
	}
	c, err := customer.Update(
		customerID,
		customerParams,
	)
	if err != nil {
		r.logger.Error("customer.Update: %v %s", err, c.ID)
		return nil, err
	}

	// Create subscription
	price :=prices[priceID]
	subscriptionParams := &stripe.SubscriptionParams{
		Customer: stripe.String(customerID),
		Items: []*stripe.SubscriptionItemsParams{
			{
				Plan: &price,
			},
		},
	 	TrialPeriodDays:stripe.Int64(7),
	 	OffSession:stripe.Bool(true),
	}
	subscriptionParams.AddExpand("latest_invoice.payment_intent")
	s, err := sub.New(subscriptionParams)

	if err != nil {
		r.logger.Error("sub.New: %v", err)
		return nil, err
	}
	return s, nil
}
```

**Comment by arizanovj** [comment]
For this card 4000000000003063 I get pending_setup_intent=null. 
Source of 3D secure card: https://stripe.com/docs/testing#three-ds-cards

**Comment by remi-stripe** [comment]
@arizanovj Github issues should be limited to bugs with the library itself and not questions about our products or APIs. I'm going to close this out and I would recommend that you contact our support team instead directly as they can help you investigate this: https://support.stripe.com/contact

**Comment by arizanovj** [comment]
Looks to me like the structure of the response does not correspond to that of the documentation. I'll try to contact and see what they say.

**Comment by remi-stripe** [comment]
The problem here is that `pending_setup_intent` is a string by default. You have to explicitly expand it if you want the full object, otherwise you only get the ID back. So when you create your subscription make sure to expand `pending_setup_intent` the same way you expand the `latest_invoice`.

You can read more about expansion here: https://stripe.com/docs/expand
