### ISSUE TITLE
go dependency error

### ISSUE THREAD

**Issue by Godley** [stripe/stripe-go#1164]
Hi there, I'm using Golang 1.15 and stripe v71. I'm also using go modules.

No matter what I do in go.mod, I always get the following added to my go mod file:
```
github.com/stripe/stripe-go v70.15.0+incompatible
github.com/stripe/stripe-go/v71 v71.46.0
```
not really sure why, but then when I follow the API docs, I then seem to get some confusion over where different objects are coming from in the library:
```
pkg/trackback/stripe.go:41:29: cannot use params (type *"github.com/stripe/stripe-go/v71".CheckoutSessionParams) as type *"github.com/stripe/stripe-go".CheckoutSessionParams in argument to session.New
```

Not really sure what I should be doing here?

**Comment by brandur-stripe** [comment]
Hey @Godley, you need to make sure that you're using the "v71" version of the package exclusively everywhere. That applies to the top-level package like:

``` go
    "github.com/stripe/stripe-go/v71"
```

But it also applies to subpackages, which are included like this:

``` go
    "github.com/stripe/stripe-go/v71/customer"
``` 

From the error message you posted, it looks like you are importing `github.com/stripe/stripe-go/session` somewhere, which you should changed to `github.com/stripe/stripe-go/v71/session`.

**Comment by Godley** [comment]
Ah, my bad! Whenever I pressed save in vs code it added in the import to the wrong one sneakily. Thank you!
