### ISSUE TITLE
Package stripe load the version 72 by default

### ISSUE THREAD

**Issue by gourlaa** [stripe/stripe-go#1175]
Hi Stripe,

We are still using the version v71 with Plan, TrialEnd, etc.. on the class CustomerParams.

However since the release, I can't build our pipeline anymore because when we have the import : github.com/stripe/stripe-go it's loading the v72..

Currently I have this message : 
unknown field 'Plan' in struct literal of type stripe.CustomerParams"

Can you find a way to manage your GoLang package without breaking our pipeline?

If every package do like you are doing, It's impossible to maintain for us. we can't afford to do : go get -u github.com/stripe/stripe-go/v71 and it's not working for us :
package github.com/stripe/stripe-go/v71: cannot find package "github.com/stripe/stripe-go/v71"

In the mid time, we made a fork : https://github.com/braineet/stripe-go

Best regards,
Pierre

**Comment by brandur-stripe** [comment]
Hi Pierre,

stripe-go uses semantic versioning, which means that v72 may contain backwards incompatible changes compared to v71. We're quite careful to never put anything breaking into minor or patch versions, but you can't jump a major and expect perfect compatibility.

> If every package do like you are doing, It's impossible to maintain for us. we can't afford to do : go get -u > github.com/stripe/stripe-go/v71 and it's not working for us :
package github.com/stripe/stripe-go/v71: cannot find package "github.com/stripe/stripe-go/v71"

It sounds like you might not be using Go Modules. Check out [using Go modules](https://blog.golang.org/using-go-modules) and consider upgrading — they're more or less required to use stripe-go and many other common packages in the Go ecosystem these days. We delayed making the full jump to requiring them for a long time, but they've been the official Go package manager for many years now, and not supporting them properly was causing a lot of user confusion. Once you have those in place, locking to v71 will work.

> In the mid time, we made a fork : https://github.com/braineet/stripe-go

Obviously that's your prerogative, but I'd suggest using Go Modules and locking to v71 instead.

**Comment by twocs** [comment]
I know that this issue is closed, but just to mention that I found we needed to manually edit the import statements to invalidate the v71 package. It wouldn't work to just run `go get`, some of the packages would be v71 and then there would be a conflict.

import (
	"github.com/stripe/stripe-go/v72"
	"github.com/stripe/stripe-go/v72/checkout/session"
	"github.com/stripe/stripe-go/v72/paymentintent"
	"github.com/stripe/stripe-go/v72/sub"
)
