### ISSUE TITLE
Issuing Card Details Undefined 

### ISSUE THREAD

**Issue by griffinmc22** [stripe/stripe-go#1179]
Go 1.15
Stripe-go v72.0.0

https://stripe.com/docs/api/issuing/cards/retrieve_details

Stripe docs reference accessing the card details endpoint using card.Details, however it doesn't appear that this function works

if I am missing something I apologize.

**Comment by remi-stripe** [comment]
@griffinmc22 This API method is actively deprecated and has been removed. Only developers that were part of the Issuing beta have access to it.
Instead, you should retrieve an issuing card and explicitly expand `cvc` and `number` as documented here instead: https://stripe.com/docs/issuing/cards/virtual

Hope this helps and sorry for the confusion!

**Comment by griffinmc22** [comment]
Thank you that ended up working out!
