### ISSUE TITLE
Returned webhook objects have no metadata, so can't access webhook metadata via the api

### ISSUE THREAD

**Issue by hugbubby** [stripe/stripe-go#1181]
Stripe go library version: v72
Go version: 1.14.7

Title. I'm currently sticking metadata in webhook descriptions. I wasn't born this way, but I must survive

**Comment by remi-stripe** [comment]
@hugbubby Would you be able to provide a bit more details about the issue you are encountering? I don't really follow which event(s) you are missing and what metadata you are not getting so if you could provide a bit more information I should be able to help!

**Comment by hugbubby** [comment]
https://stripe.com/docs/api/webhook_endpoints
^ notice the metadata field in this object

said metadata field is not present in the golang webhookendpoint object, and I can't modify or read it

**Comment by remi-stripe** [comment]
@hugbubby I just released 72.3.0 with a fix so you should be all set! Thank again for the report, sorry we missed that property originally!
