### ISSUE TITLE
Prevent automatic retry on context cancellation

### ISSUE THREAD

**Issue by mickeyreiss** [stripe/stripe-go#1184]
When making requests with a `context.Context` set in the `Params`, there's no need to retry requests if the error is due to the context being done (e.g. `context.Canceled`).

I noticed this organically while testing edge cases in a context-aware codebase, and then I found this TODO in the codebase:

https://github.com/stripe/stripe-go/blob/81f75d56592cae0f0a478bbc5f052d3f2adaaffa/stripe.go#L624-L630

I think a context check would be a relatively simple place to start.

***

For reference, here's another open-source library's approach to "retry network errors": 

https://github.com/hashicorp/go-retryablehttp/blob/6861976bd32109e69c73cb1546e7671102fb703b/client.go#L399-L445

**Comment by brandur-stripe** [comment]
Thanks Mickey, and good catch. We'll take a closer look at this one.
