### ISSUE TITLE
Customer Email and Desc params aren't loaded

### ISSUE THREAD

**Issue by dclausen** [stripe/stripe-go#119]
I can load a customer via customer.Get(customerId) directly and see the Email and Desc correctly. 

However, if I load all charges for that same customer using charge.List(), and then try to access charge.Customer.Desc and charge.Customer.Email, they are both always blank.

I was expecting charge.Customer to display all attributes from the Customer struct.

In the ruby client, I'm able to pass expand: ['data.customer'] to load the details of the customer. However, I don't see how to do so using ChargeListParams or ListParams.

**Comment by kyleconroy** [comment]
@dclausen Thanks for the bug report. Expansion is supported on `Params`, but not `ListParams`, which I believe is just an oversight. Look for an incoming pull request.
