### ISSUE TITLE
Fails to decode unexpected API errors

### ISSUE THREAD

**Issue by Stumblinbear** [stripe/stripe-go#1196]
While setting up OAuth for Stripe, I've received the following error when trying to decode one of the errors I received.

```Golang
token, err := oauth.New(&stripe.OAuthTokenParams{
	GrantType: stripe.String("authorization_code"),
	Code:      stripe.String(code),
})
```

```Error decoding error from Stripe: Couldn't deserialize JSON (response status: 500, body sample: '{\n "error": {\n "code": "unexpected_api_error",\n "message": "An unexpected error occurred",\n "type": "api_error"\n }\n}\n'): json: cannot unmarshal object into Go struct field rawErrorInternal.error of type string```

**Comment by remi-stripe** [comment]
Going to close that one as it's been a while, sorry for the delay. Please flag if you experience this again
