### ISSUE TITLE
Mandate missing in ChargePaymentMethodDetailsSepaDebit

### ISSUE THREAD

**Issue by entvia** [stripe/stripe-go#1204]
ChargePaymentMethodDetailsSepaDebit struct has to have Mandate property. It is there if you make a curl request, but not when you use this client. Would be great if you could add it.

**Comment by remi-stripe** [comment]
@entvia Thank you for the report and sorry we missed that property. I just released 72.13.0 with a fix so you should now be all set!

**Comment by entvia** [comment]
@remi-stripe thank you for super fast reaction!

**Comment by entvia** [comment]
@remi-stripe I just realized that it has to be added to all structs related to SepaDD, at least to `PaymentMethodSepaDebit`

**Comment by remi-stripe** [comment]
@entvia There is no `mandate` property in `payment_method_details[sepa_debit]` on `PaymentMethod` today: https://stripe.com/docs/api/payment_methods/object#payment_method_object-sepa_debit 
Can you clarify what you're seeing that you think is missing?

**Comment by entvia** [comment]
@remi-stripe yes, you are right, there is no mandate property there, my bad. Thanks for the first fix!
