### ISSUE TITLE
Can not create metadata for subscription

### ISSUE THREAD

**Issue by smiletrl** [stripe/stripe-go#1233]
According to https://stripe.com/docs/api/subscriptions/create, there's a parameter `metadata` to assign metadata, but this library doesn't seem to provide such parameter in `type SubscriptionParams` in sub.go. But it has such field `Metadata` at `type Subscription struct`.

Btw, my go version is 1.14, and v72 for this library.

Thanks for this great library though!

**Comment by remi-stripe** [comment]
@smiletrl stripe-go does support `Metadata` but it works a bit differently and is inside the custom `Params` class. What we recommend is to use `AddMetadata` instead as documented [here](https://stripe.com/docs/api/metadata?lang=go) so the code would look like this:
```
params := &stripe.SubscriptionParams{
  Customer: stripe.String("cus_1234"),
  Items: []*stripe.SubscriptionItemsParams{
    {
      Price: stripe.String("price_ABC"),
    },
  },
}
params.AddMetadata("key1", "value1")
s, err := sub.New(params)
```

Alternatively, if you prefer to pass the 
```
params := &stripe.SubscriptionParams{
  Customer: stripe.String("cus_1234"),
  Items: []*stripe.SubscriptionItemsParams{
    {
      Price: stripe.String("price_ABC"),
    },
  },
  Params: stripe.Params{
    Metadata: map[string]string {
      "key1": "value1",
    },
  },
}
params.AddMetadata("key1", "value1")
s, err := sub.New(params)
```

**Comment by smiletrl** [comment]
thanks!
