### ISSUE TITLE
Missmatch docs vs go library

### ISSUE THREAD

**Issue by eripe970** [stripe/stripe-go#1238]
According to the docs at https://stripe.com/docs/connect/subscriptions#collecting-fees-on-subscriptions. There should the application fee percent be of type Int64 but it's float64 in the go sdk. 

```
ApplicationFeePercent: stripe.Int64(10),
```

Guess the docs should be updated to float64? 

```
ApplicationFeePercent: stripe.Float64(10),
```

**Comment by remi-stripe** [comment]
@eripe970 Thanks for the report. The stripe-go library is correct here and the docs are wrong so I'm going to close this out and get it fixed internally!

**Comment by pxue** [comment]
@remi-stripe any word on this? went through the doc again and it's getting more and more mismatched. thanks in advance though!

**Comment by remi-stripe** [comment]
@pxue Can you give me a bit more context about what is more and more mismatched?

**Comment by pxue** [comment]
@remi-stripe on closer inspection, it's my mistake!

specifically, the checkout line item "price" fields can be either ID of the price OR the ID of the plan. which i did not expect.

**Comment by remi-stripe** [comment]
@pxue Oh I see! When we built the Price API we made sure that it was backwards compatible with the Plan API so that you could pass a Plan id as a Price to not have to recreate all your data!
