### ISSUE TITLE
looks like there is a typo on the Invoice struct

### ISSUE THREAD

**Issue by brotich** [stripe/stripe-go#1244]
it looks like https://github.com/stripe/stripe-go/blob/f3ced151edef44bee641555e373033461e5aa67a/invoice.go#L277 has the `ThresholdReason` spelled as `ThreasholdReason`

**Comment by brandur-stripe** [comment]
Oof confirmed, thank you. Worse yet, it looks like it was added two years ago, so it's been misspelled for quite some time and probably has users.

@remi-stripe Any thoughts on preferred fix?  Should we tee up a patch and wait for a major or something?

**Comment by yejia-stripe** [comment]
Fixed with the [v73 release](https://github.com/stripe/stripe-go/releases/tag/v73.0.0)
