### ISSUE TITLE
CheckoutSessionParams missing Metadata?

### ISSUE THREAD

**Issue by jaunt** [stripe/stripe-go#1251]
Go 1.14
github.com/stripe/stripe-go/v72 v72.33.0

When creating a session, the docs say I can pass in metadata: https://stripe.com/docs/api/checkout/sessions/create#create_checkout_session-metadata

CheckoutSessionParams doesn't seem to support this.  Is there a workaround?

**Comment by remi-stripe** [comment]
@jaunt stripe-go does support `Metadata` already on all the relevant resource. It's just not directly visible because `Metadata` was built a bit differently in the library. The recommended way is to use `AddMetadata` as documented in https://stripe.com/docs/api/metadata?lang=go
