### ISSUE TITLE
JSON structs omitempty

### ISSUE THREAD

**Issue by tarasyarema** [stripe/stripe-go#1255]
We're integrating Stripe with a SQL-like database and we need to only store those fields that are actually populated when fetching from the API using this library. The problem is that, as we are using the default `json.Marshal` function to marshal the fields of the resources, we get all the fields with its zero values. 

It's easy to solve for pointers, for example, but when we have fields of builtin types like `bool` or `int64`, the defaults are `false` and `0`, resp. This issue is hard to overcome, and I was wondering if there's an actual reason for the fields to not have the `omitempty` JSON tag.

As a concrete example, you can consider a [discounts coupon](https://github.com/stripe/stripe-go/blob/6fd6a3d8f2d560f4f52a50a7c2b7cd82e9a480f6/coupon.go#L51) which may not have both fields `AmountOff` and `PercentOff` set at the same time, hence it could be handy to only store the one that are returned from the API. In the [online API docs](https://stripe.com/docs/api/coupons/object) the example object actually has the `amount_off` set to `null` ("empty") and the `percent_off` set to some number.

```json
{
  "id": "25_5OFF",
  "object": "coupon",
  "amount_off": null,
  "created": 1614207164,
  "currency": "usd",
  "duration": "repeating",
  "duration_in_months": 3,
  "livemode": false,
  "max_redemptions": null,
  "metadata": {},
  "name": "25.5% off",
  "percent_off": 25.5,
  "redeem_by": null,
  "times_redeemed": 0,
  "valid": true
}
```

**Comment by brandur-stripe** [comment]
@tarasyarema The reason nothing's tagged with `omitempty` is that the JSON tags are only meant to go one way — i.e. we unmarshal from JSON, but don't marshal to it. The lack of `omitempty` is one issue, but there are various others as well, like custom `UnmarshalJSON` code in a few places that doesn't have a matching Marshal.

If you're storing data to your database, we'd highly recommend _not_ using `stripe-go` structs, and instead use your own versions which you have perfect serialization control over. This approach will also be better for your long term schema stability as we make changes to stripe-go structs over time.
