### ISSUE TITLE
stripe.Error does not work with errors.As()

### ISSUE THREAD

**Issue by megapctr** [stripe/stripe-go#1260]
Hello!

I have a `shop` package with a Client type that wraps a Stripe client in a focused, higher-level interface. I am adding support for coupon codes and need to check if the error I get from Stripe means "that coupon code is invalid" or something else.

I have this
```go
package shop

func IsNotFound(err error) bool {
        var stripeErr stripe.Error
        if errors.As(err, &stripeErr) {
                return stripeErr.Type == stripe.ErrorTypeInvalidRequest &&
                        stripeErr.Code == stripe.ErrorCodeResourceMissing
        }
        return false
}
```

but I get this warning in my editor, and executing this code results in a panic
> second argument to errors.As must be a non-nil pointer to either a type that implements error, or to any interface type

Which is weird, as in the docs I clearly see that `stripe.Error` implements the `error` interface. I'm not sure if this is a bug in stripe-go package, the built-in errors package, or maybe I'm too tired to think. By the way, is this the correct way for checking for such an error? Please advise :slightly_smiling_face: 

<hr>

Additional note: I can't just do a type assertion, because my `shop.Client` wraps the error with `fmt.Errorf`. For now I will just type-assert `Unwrap()`pable interface, and then type-assert `stripe.Error` the inner error.

<hr>

My environment:
```shell
$ go version
go version go1.15.2 linux/amd64
$ grep stripe go.mod
	github.com/stripe/stripe-go/v72 v72.35.0
```

**Comment by brandur-stripe** [comment]
The docs for `errors.As` are shockingly awful in that as far as I can tell, this is never explicitly mentioned, but it actually wants a pointer to a pointer. Make `stripeErr` in your code a pointer type:

``` go
var stripeErr *stripe.Error
```

**Comment by megapctr** [comment]
Right, because that Error method actually takes `*stripe.Error` and `errors.As` needs a pointer to that receiver. Thank you for responding so quickly!
