### ISSUE TITLE
module github.com/stripe/stripe-go@latest found (v70.15.0+incompatible), but does not contain package github.com/stripe/stripe-go/billingportal/session

### ISSUE THREAD

**Issue by XiovV** [stripe/stripe-go#1267]
Every time I try compiling my project, I get the following error:
```bash
go: finding module for package github.com/stripe/stripe-go/billingportal/session
handlers/stripe.go:8:2: module github.com/stripe/stripe-go@latest found (v70.15.0+incompatible), but does not contain package github.com/stripe/stripe-go/billingportal/session
```

I tried running go mod tidy but I'm still getting the same issue. This is my code:
```Go
func HandleCustomerPortal(w http.ResponseWriter, r *http.Request) {
	stripe.Key = os.Getenv("STRIPE_SECRET_KEY")

	params := &stripe.BillingPortalSessionParams{
		Customer: stripe.String("customer id"),
		ReturnURL: stripe.String("https://example.com/account"),
	}
	s, _ := session.New(params)

	http.Redirect(w, r, s.URL, 302)
}
```

**Comment by brandur-stripe** [comment]
Try changing any v70s you have at the end of your import strings to v72. e.g.

``` go
import "github.com/stripe/stripe-go/v72"
```

**Comment by XiovV** [comment]
> Try changing any v70s you have at the end of your import strings to v72. e.g.
> 
> ```go
> import "github.com/stripe/stripe-go/v72"
> ```

I had that imported. I fixed this issue by copy-pasting the code that's in github.com/stripe/stripe-go/billingportal/session into my own library. Altough now I'm getting a CORS issue: 
Access to XMLHttpRequest at 'https://billing.stripe.com/session/_sessionid' (redirected from 'https://api.mysite.com/api/stripe/create-customer-portal-session') from origin 'https://app.mysite.com' has been blocked by CORS policy: Response to preflight request doesn't pass access control check: No 'Access-Control-Allow-Origin' header is present on the requested resource.

**Comment by XiovV** [comment]
I think I can bypass this issue by sending the billing.stripe.com url back to the client, so then the client can redirect the user to the customer portal.

**Comment by brandur-stripe** [comment]
> I had that imported. I fixed this issue by copy-pasting the code that's in github.com/stripe/stripe-go/billingportal/session into my own library.

Okay, good that you got this fixed, but if you were importing v72 and had a v70 package like in your error message, then something unusual was probably going on.

We try to keep GitHub issues reserved for use with API library specific bugs. We've confirmed there isn't one here so I'm going to close this out. Would you mind sending future questions about CORS and other subjects to support@stripe.com? You'll get higher quality support over there.
