### ISSUE TITLE
why publishable key need to be rotatable?

### ISSUE THREAD

**Issue by rohitkeshwani07** [stripe/stripe-go#1294]
In what use case should a merchant rotate his publishable key? 

It's a public key present in browsers to be used in public apis so why would i ever rotate this?

**Comment by remi-stripe** [comment]
@rohitkeshwani07 There are some valid use-cases like sharing the key with another integration that you want to deprecate and ensure isn't making valid API requests anymore but you don't control the code. It's definitely uncommon to roll your publishable key. Overall, it's mostly here for consistency, it's an API key and it should be rotatable.

I'm going to close this us as Github issues should be limited to bugs with the library itself and this is more a product question that should go to our support team: https://support.stripe.com/contact/email
