### ISSUE TITLE
Change type for Error field in SigmaScheduledQueryRun struct

### ISSUE THREAD

**Issue by groovypalak** [stripe/stripe-go#1307]
I am unable to unmarshal the JSON  response from https://api.stripe.com/v1/sigma/scheduled_query_runs to the struct SigmaScheduledQueryRun. In the struct of SigmaScheduledQueryRun, the Error field is of type string, whereas the JSON response returns a field of type Error instead.

**Comment by remi-stripe** [comment]
@groovypalak sorry for the trouble and thank you for the report. I've opened a PR https://github.com/stripe/stripe-go/pull/1309 though it's technically a breaking change and might need to wait a bit until we plan the next major release
