### ISSUE TITLE
Payment Method Params ExpMonth, Exp Year Datatype

### ISSUE THREAD

**Issue by phanthaiduong22** [stripe/stripe-go#1308]
What I'm doing is update PaymentMethod. I see in Payment Method Params Object. 
![Payment Method Params Object.](https://user-images.githubusercontent.com/30502963/124214255-20c0b700-db1c-11eb-8a4a-b5bc2e5e91aa.png)
Exp_month, Exp_year are integer
However, in Golang code I see `PaymentMethodParams` struct use `Card * PaymentMethodCardParams`
And in PaymentMethodCardParams struct
![image](https://user-images.githubusercontent.com/30502963/124214823-0e934880-db1d-11eb-91bd-1341479754cd.png)
ExpMonth, ExpYear is string.
I come with this. Because when I update the Payment Method I got `parameter_invalid_integer`

**Comment by paulasjes-stripe** [comment]
This is expected, as you can see by the sample code here: https://stripe.com/docs/api/payment_methods/create?lang=go

Those fields are strings to make working with them easier. For instance for `ExpMonth` you could pass in `"7"` or `"07"` and they would both work. For `ExpYear` you can pass in either `"2022"` or `"22"` and expect both formats to work.
