### ISSUE TITLE
The uploads.stripe.com host is down

### ISSUE THREAD

**Issue by cristianpontes** [stripe/stripe-go#1313]
# The problem

- The current version of the lib uses `uploads.stripe.com` as the host for uploading files, see: https://github.com/stripe/stripe-go/blame/master/stripe.go#L1224

- https://uploads.stripe.com/ is currently down

- By looking at the docs, `files.stripe.com` seems to be the prefered host for this

- [According to this comment](https://github.com/stripe/stripe-php/issues/424#issuecomment-359891091), `uploads.stripe.com` and `files.stripe.com` are aliases. I'm guessing the alias was recently taken down

**Comment by remi-stripe** [comment]
@cristianpontes thanks for the report. We're working on a fix, I'd recommend using Discord to chat with developers instead of github issues for things like this so that you can get a real time response: https://stripe.com/go/developer-chat
