### ISSUE TITLE
Payout struct is missing reference field

### ISSUE THREAD

**Issue by imprint75** [stripe/stripe-go#1321]
The API docs indicate that `reference` can be included in the payout response, but it's missing from the struct https://github.com/stripe/stripe-go/blob/master/payout.go#L118-L146 so it gets removed when unmarshaling. Is there a workaround using the API or is it possible to get `reference` added?

**Comment by remi-stripe** [comment]
@imprint75 The `reference` property on `Payout` is not a public feature and it's undocumented which is why it's not in stripe-go today. It wouldn't be added until the property ships publicly and right now it's only limited to some accounts.

You can use `LastResponse.RawJSON` instead like this:

```
s, _ := payout.Get("po_123", nil)

var rawData map[string]interface{}
_ = json.Unmarshal(s.LastResponse.RawJSON, &rawData)
rawData["reference"].(string)
```
