### ISSUE TITLE
SubscriptionParams struct has obsolete OnBehalfOf field

### ISSUE THREAD

**Issue by snaffi** [stripe/stripe-go#1327]
I received an error during creation a subscription with on_behalf_of parameter 

Regarding to subscription creation [documentation](https://stripe.com/docs/api#create_subscription) that parameter is obsolete

```javascript
{
  "error": {
    "code": "parameter_unknown",
    "doc_url": "https://stripe.com/docs/error-codes/parameter-unknown",
    "message": "Received unknown parameter: on_behalf_of",
    "param": "on_behalf_of",
    "type": "invalid_request_error"
  }
}
````

**Comment by remi-stripe** [comment]
@snaffi it's not an obsolete/deprecated parameter but a feature that is in beta and not yet public. We hope to release publicly in the future when it can be used by anyone. Hope this clarifies the situation!
