### ISSUE TITLE
Stripe update subscription and add new payment method with 3d secure

### ISSUE THREAD

**Issue by gadelkareem** [stripe/stripe-go#1348]
I created a subscription as described on https://stripe.com/docs/billing/subscriptions/elements but now I want to give the user the choice to change the plan on the subscription and use another payment method, ex 3d Secure card. However if I update the subscription to get a client secret for a new payment intent as following:
```
func (c *Client) UpdateSubscription(s *models.Subscription) (*models.Subscription, error) {
    sps := &stripe.SubscriptionParams{
        DefaultPaymentMethod: stripe.String(s.PaymentMethodId),
        CancelAtPeriodEnd:    stripe.Bool(false),
        ProrationBehavior:    stripe.String(string(stripe.SubscriptionProrationBehaviorAlwaysInvoice)),
    }
    if s.CreatePaymentIntent {
        s.PaymentBehavior = "allow_incomplete"
        sps.PaymentBehavior = stripe.String(s.PaymentBehavior)
        sps.AddExpand("latest_invoice.payment_intent")
    } else if s.ItemID != "" {
        sps.Items = []*stripe.SubscriptionItemsParams{
            {Price: stripe.String(s.PriceID)},
            {ID: stripe.String(s.ItemID), Deleted: stripe.Bool(true)},
        }
    }
    ss, err := sub.Update(s.ID, sps)
    if ss.LatestInvoice != nil && ss.LatestInvoice.PaymentIntent != nil {
        s.PaymentIntentClientSecret = ss.LatestInvoice.PaymentIntent.ClientSecret
    }
    return s, err
}
```
the `PaymentIntentClientSecret` is the same for the subscription which means it is already processed.
Stripe 'confirm card' API is throwing error `payment_intent_unexpected_state` https://stripe.com/docs/error-codes/payment-intent-unexpected-state and that's probably because I used that payment intent previously to create the subscription. However I still need a new payment intent to authorise the new card.

**Comment by remi-stripe** [comment]
@gadelkareem Github issues should be limited to bugs with the library itself and it seems your question is more an integration question. We recommend contacting our support team for help directly [here](https://support.stripe.com/contact) or you can ask developers on our Discord server [here](https://stripe.com/go/developer-chat)
