### ISSUE TITLE
AutomaticTax

### ISSUE THREAD

**Issue by valensto** [stripe/stripe-go#1367]
I may be using the AutomaticTax key but when implimenting the example given on the sites instruction to set automatic tax with stripe struct  I have an error thrown that tells me that the AutomaticTax field is not present in the SubscriptionParams struct.

https://stripe.com/docs/billing/taxes/collect-taxes?tax-calculation=stripe-tax#create-a-subscription
```
  subscriptionParams := &stripe.SubscriptionParams{
		Customer: stripe.String(string(cid)),
		Items: []*stripe.SubscriptionItemsParams{{
				Price: stripe.String(string(pid)),
				Quantity: stripe.Int64(9),
			},
		},
		AutomaticTax: &stripe.SubscriptionAutomaticTaxParams{
			Enabled: stripe.Bool(true),
		},
		PaymentBehavior: stripe.String("default_incomplete"),
	}
```

Give me Unknown field 'AutomaticTax' in struct literal
And Unresolved type 'SubscriptionAutomaticTaxParams' on stripe struct

**Comment by remi-stripe** [comment]
@valensto The `AutomaticTax` parameter is present in stripe-go and defined [here](https://github.com/stripe/stripe-go/blob/master/sub.go#L193). That was added back in June 2021 in `72.48.0` ([changelog](https://github.com/stripe/stripe-go/blob/master/CHANGELOG.md#72480---2021-06-04)). 

You likely are on an older version of stripe-go in your system from before this was added. Can you double check your version and confirm that upgrading fixes the issue?

**Comment by valensto** [comment]
@remi-stripe Yes it was the version, maybe edit it into the documentation with a mention :)
Thank you !
