### ISSUE TITLE
Charge object empty on error

### ISSUE THREAD

**Issue by stengland** [stripe/stripe-go#139]
When an error occurs when creating a charge I do not seem to get any information about the charge returned.

```go
ch, err := charge.New(chargeParams)
if err !=nil
  ...
   t.ChargeID = ch.ID // < this is null. Logging shows:
   // 2015/09/07 17:45:11 Error encountered from Stripe: {"type":"card_error","message":"Your card was declined.","code":"card_declined","request_id":"req_6wLQirhwDRiX7P"}
  ...
end
```

I'd like to know the id of the failed charge so we can cross-reference with our app and the Stripe dashboard. What am I doing wrong?

**Comment by goors** [comment]
log.Println(err) will give you 
<pre>
2015/09/07 17:45:11 Error encountered from Stripe: {"type":"card_error","message":"Your card was declined.","code":"card_declined","request_id":"req_6wLQirhwDRiX7P"}
</pre>
  ...

**Comment by stengland** [comment]
@goors I am already using that error object but it only contains a "request_id". What I am after is the id of the charge object. I believe the charge object it is returned in the API response.

**Comment by kyleconroy** [comment]
@stengland The charge object won't be on the charge itself. Instead, it will now be on the error struct. See my PR for a code example.

**Comment by stengland** [comment]
@kyleconroy Thanks!
