### ISSUE TITLE
Balance Transaction Source UnmarshalJSON missing case for connect collection transfer

### ISSUE THREAD

**Issue by mickeyreiss** [stripe/stripe-go#1392]
The switch statement here:

https://github.com/stripe/stripe-go/blob/e0838db3fda9dbd57abfd2caf97ce5f2bde894f8/balancetransaction.go#L223-L249

is missing a case for `connect_collection_transfer`. As a result, the expanded source destination account cannot be read off of balance transactions with the reporting category `connect_collection_transfer`.

Feel free to reach out to me directly if you'd like an example txn_ id to trace this down.

**Comment by dcr-stripe** [comment]
Hi @mickeyreiss,

Thanks for the feedback here - great catch! We'll look into this in the near future and get back to you.
