### ISSUE TITLE
Stripe fails to interpolate {CHECKOUT_SESSION_ID} when percent-encoded

### ISSUE THREAD

**Issue by yktoo** [stripe/stripe-go#1394]
Honestly, this isn't directly related to the Go API, but with the way Go handles query parameters it's very difficult to circumvent.

When passing the `{CHECKOUT_SESSION_ID}` to Stripe Checkout success URL and using Go's `url.Values.Encode()` to add query params, the braces `{` and `}` get [percent-encoded](https://en.wikipedia.org/wiki/Percent-encoding), so the URL looks as follows:

```
https://.../success?session_id=%7bCHECKOUT_SESSION_ID%7d
```

Stripe then fails to recognise this as a placeholder and returns as is, which subsequently leads to 404 errors.

**Expected behaviour**

Stripe correctly percent-decodes the URL and the placeholder, then replaces it with the session ID.

**See also**

[Here](https://stackoverflow.com/questions/61856273/stripe-success-url-format-in-a-rails-app-not-creating-correct-url) is a description of the same bug when using Ruby.

**Comment by yejia-stripe** [comment]
Hi @yktoo, thanks for the report! As this isn't an issue with the stripe-go library itself, but rather the result of using `url.Values.Encode` and our API, we've decided not to fix this in the library. This would be consistent with our other libraries, as we do not handle `{CHECKOUT_SESSION_ID}` specially in them either.

As a workaround, I would suggest doing something like the following, which is similar to the workaround mentioned in the answer to the stripe-ruby StackOverflow question:
```go
successURL, _ := url.Parse("https://example.com/")
parameters := url.Values{}
parameters.Add("foo", "bar")
successURL.RawQuery = parameters.Encode() +"&session_id={CHECKOUT_SESSION_ID}"
```

**Comment by yktoo** [comment]
Well that's more or less what I ended up with. I think it'd be the best to use another, ASCII-based, placeholder for the session ID though. That'd resolve similar issues once and for all.

**Comment by yejia-stripe** [comment]
Thank you for the suggestion! I've forwarded it to the appropriate team
