### ISSUE TITLE
Webhooks testing

### ISSUE THREAD

**Issue by ivanduka** [stripe/stripe-go#1406]
How can I mock the requests from Stripe to my webhooks?

The Node library has the `stripe.webhooks.generateTestHeaderString` method that allows to mock such requests:

```javascript
const payload = {
  id: 'evt_test_webhook',
  object: 'event',
};

const payloadString = JSON.stringify(payload, null, 2);
const secret = 'whsec_test_secret';

const header = stripe.webhooks.generateTestHeaderString({
  payload: payloadString,
  secret,
});

const event = stripe.webhooks.constructEvent(payloadString, header, secret);

// Do something with mocked signed event
expect(event.id).to.equal(payload.id);
```

However, I do not see such method on the `webhook` package.

Is there any way we can achieve the same with the Go library?

**Comment by yejia-stripe** [comment]
@ivanduka Thank you for the suggestion! Added with #1520. See the [Testing Webhook signing
](https://github.com/stripe/stripe-go#testing-webhook-signing) section in the README for how to use.
