### ISSUE TITLE
Use `stripe.Error` in function declarations? 

### ISSUE THREAD

**Issue by zdufour-asp** [stripe/stripe-go#1412]
I'm new to Go, so apologies if this is a dumb idea.

If the CRUD methods in `paymentintent/client.go` return a `stripe.Error`, shouldn't that be declared so that developers can see the `stripe.Error` help text when mousing over `err` in something like

```go
intent, err := client.PaymentIntents.New(args)
```

(Whereas at the moment the generic `error` is used)

**Comment by richardm-stripe** [comment]
Hello @zdufour-asp,, not a dumb idea at all, unfortunately as presently implemented, we can't guarantee that `err` here will be a `stripe.Error`. That [only happens](https://github.com/stripe/stripe-go/blob/1b0ed54939a3c798f332ee7a9f2627fb1bad61c8/stripe.go#L647-L651) when the client gets a 4xx or 5xx error from the server and can parse the JSON, but there might be an HTTP connection error, or a json parsing error, and those will have the primitive error types.

I think wrapping the primitive errors for better IDE support is something to consider for a future version. It would take some careful though. I'm not aware of any other Go SDKs that operate this way, but if anybody reading happens to have an example of a library that does this well for inspiration, that would be helpful!

**Comment by hampgoodwin** [comment]
@zdufour-asp generally you would want to take the go [error interface type](https://cs.opensource.google/go/go/+/go1.19:src/builtin/builtin.go;l=280), and then use [errors.Is](https://cs.opensource.google/go/go/+/go1.19:src/errors/wrap.go;l=40) or [.As](https://cs.opensource.google/go/go/+/go1.19:src/errors/wrap.go;l=78) to determine if it is a stripe.Error. However, the stripe.Error, in v72, does not meet the go interface.
(lots of other ways to do this, too, this is just [std lib recommended way](https://go.dev/blog/go1.13-errors#examining-errors-with-is-and-as))

Here is an example, but it's not possible currently, and instead we do it [as documented by stripe here](https://stripe.com/docs/api/errors/handling?lang=go).

```go
val, err := stripeClient.Doit()
if err != nil {
  var stripeErr stripev72.Error
  if errors.As(err, &stripeErr) {
    fmt.Println(stripeErr.Code) // do whatever here because we now have the custom stripe error
  }
}
```

**Comment by pakrym-stripe** [comment]
Hi. Returning `stripe.Error` from all methods won't work well because there are other non-Stripe related errors that can be returned. If we wrap all errors into `stripe.Error` it'll become equivalent to the standard `Error`. 

You can use `error.Is` to determine if the `Error` is a `stripe.Error`:
```go
         _, err := c.RetrievePaymentMethod("", &stripe.CustomerRetrievePaymentMethodParams{})
	if err != nil {
		var stripeErr *stripe.Error
		if errors.As(err, &stripeErr) {
			fmt.Println(stripeErr.Msg)
		}
	}
```
