### ISSUE TITLE
[Feature Request] Format Amount in Currency

### ISSUE THREAD

**Issue by stuartmscott** [stripe/stripe-go#1426]
Hey all,

Formatting monetary amounts can be tricky as each currency/country have their own set of rules. As I am sure Stripe has solved this problem already internally, could a utility be introduced to `stripe-go` that would accept an amount and a currency, and return a string representation?

ie.
```go
fmt.Println(stripe.FormatAmount(1234, stripe.CurrencyBGN))
fmt.Println(stripe.FormatAmount(1234, stripe.CurrencyGBP))
fmt.Println(stripe.FormatAmount(1234, stripe.CurrencyUSD))
```

> 12.34 лв.
> £12.34
> $12.34

Here is a cursory implementation I have made myself, it would be great if Stripe adopted and expanded it to include all supported currencies.

```go
func FormatAmount(amount float64, currency stripe.Currency) string {
	switch currency {
	case stripe.CurrencyBGN:
		// Format as decimal
		price := fmt.Sprintf("%.2f", amount/100.0)
		// Remove trailing zeros
		price = strings.TrimRight(price, "0")
		// Remove trailing point
		price = strings.TrimRight(price, ".")
		// Append lev symbol
		return price + " лв."
	case stripe.CurrencyGBP:
		// Format as decimal with pound symbol
		price := fmt.Sprintf("£%.2f", amount/100.0)
		// Remove trailing zeros
		price = strings.TrimRight(price, "0")
		// Remove trailing point
		price = strings.TrimRight(price, ".")
		return price
	case stripe.CurrencyUSD:
		// Format as decimal with dollar symbol
		price := fmt.Sprintf("$%.2f", amount/100.0)
		// Remove trailing zeros
		price = strings.TrimRight(price, "0")
		// Remove trailing point
		price = strings.TrimRight(price, ".")
		return price
	default:
		log.Println("Unhandled currency:", currency)
	}
	return ""
}
```

Thanks,
Stuart

**Comment by richardm-stripe** [comment]
Hi Stuart, thank you for the suggestion.

It's unlikely we would add this to `stripe-go` itself. Currency formatting is an extremely involved problem -- formatting a currency correctly depends not only on what type of currency it is, but also which locale you are attempting to display the currency for, e.g. when displaying USD in English-speaking Canada the dollar sign goes to the left of the amount, but in French-speaking Canada the dollar sign goes to the right. Doing this robustly is a task better suited for a globalization library, not an API client like `stripe-go`. Internally at Stripe, we don't solve globalization from scratch, and leverage globalization libraries available for the programming languages we use.

I recommend searching for a globalization library in golang - I can't endorse any particular library as I haven't vetted any thoroughly -- but useful search term might be "CLDR" as this is the [unicode standard](https://cldr.unicode.org/) that includes information about the world's currencies and how they should be formatted, and so a robust globalization library would draw upon this data.

I hope that helps! I'm closing out the issue, as I don't think we are going to take any action, but I'm happy to continue discussing.
