### ISSUE TITLE
name field missing from Plan

### ISSUE THREAD

**Issue by DziegChris** [stripe/stripe-go#1427]
The struct for a plan does not contain the "name" field, only the "nickname".

**Comment by yejia-stripe** [comment]
There is no `name` attribute on the plan object for the current version of the API ([API reference](https://stripe.com/docs/api/plans/object)). It was [moved to product](https://stripe.com/docs/api#product_object-statement_descriptor) objects with the 2018-02-05 version of the API ([changelog](https://stripe.com/docs/upgrades#2018-02-05)). Unfortunately, stripe-go is only able to reflect the values in the latest version of the API.
