### ISSUE TITLE
Unmarshalling error on schedule create from subscription

### ISSUE THREAD

**Issue by Arsaev** [stripe/stripe-go#1428]
How to reproduce:
1. Create subscription for connected account with application fee.
2. Call Subscription Schedule Create from subscription 

Result: 
Schedule is successfully created but go binding lib fails to unmarshal json with error
`(response status: 200, body sample: '{\\n \"id\": \"sub_sched_\",\\n \"object\": \"subscription_schedule\",\\n \"canceled_at\": null,\\n \"completed_at\": null,\\n \"created\": 1646824588,\\n \"current_phase\": {\\n \"end_date\": 1649502612,\\n \"start_date\": 1646824212\\n },\\n \"customer\": \"cus_\",\\n \"default_settings\": {\\n \"application_fee_percent\": 1.0,\\n \"automatic_tax\": {\\n \"enabled\": false\\n },\\n \"billing_cycle_anchor\": \"automatic\",\\n \"billing_thresholds\": null,\\n \"collection_method\": \"charge_autom ...'): json: invalid use of ,string struct tag, trying to unmarshal unquoted value into float64"`

**Comment by Arsaev** [comment]
Created a PR for this issue
https://github.com/stripe/stripe-go/pull/1429

**Comment by dcr-stripe** [comment]
Merged and released in https://github.com/stripe/stripe-go/releases/tag/v72.92.0 - thank you @Arsaev !
