### ISSUE TITLE
support refunds for Bitcoin payment

### ISSUE THREAD

**Issue by mndrix** [stripe/stripe-go#143]
When refunding a Bitcoin payment through the Stripe web interface, it appears that one sends a POST request to "/v1/charges/py_16lPYAA.../refunds" with a JSON document like this:

```json
{
"refund_address":"1KFHE7w..."
}
```

I don't see how to accomplish something similar with stripe-go.  It would be nice to be able to automate these refunds similar to credit card refunds.

**Comment by kyleconroy** [comment]
Bitcoin refunds are actually already supported. You'll need to set the refund address on the bitcoin receiver

https://stripe.com/docs/guides/bitcoin#refunds
