### ISSUE TITLE
External Account functionality missing

### ISSUE THREAD

**Issue by tylerb** [stripe/stripe-go#144]
I'd like to use stripe connect, but I need to be able to set the `external_account` param in the `AccountParams` in order to attach a bank account to the `Account` object using the token retrieved from Stripe.js.

**Comment by brandur** [comment]
Hi @tylerb! Thanks for reporting this and sorry about the trouble.

See #145 for details, but you should now be able to add an `ExternalAccount` parameter of the type `AccountExternalAccountParams` when updating an account. Please let us know if you have any trouble.

**Comment by tylerb** [comment]
Wonderful! Thanks very much for getting this implemented!
