### ISSUE TITLE
'Retrieve a Checkout Session's line items' document outdated

### ISSUE THREAD

**Issue by abishekmuthian** [stripe/stripe-go#1447]
Document to retrieve checkout session line items located at - https://stripe.com/docs/api/checkout/sessions/line_items is outdated.

`CheckoutSessionListLineItemParams` has been changed to `CheckoutSessionListLineItemsParams` https://github.com/stripe/stripe-go/blob/7a3134b3fbf1fd1ad4974057b726badf0450ef62/checkout_session.go#L744

Also the id which used to reside in `CheckoutSessionListLineItemParams` is shifted to argument of the function ListLineItems - https://github.com/stripe/stripe-go/blob/216602f0fe2231b21e00b84d5f3e2f1987f1d584/checkout/session/client.go#L113

Also, the `ListParams` now seem to contain a `Limit` field apart from the ` Filters` field which was used to set limits in the outdated documentation, Will the limit field continue to remain?

Please update the documentation with correct code and examples.

P.S. This issue seem to have previously raised two years ago by someone else in an IRC chat(?) - https://freenode.logbot.info/stripe/20200622 but hasn't been addressed yet.

**Comment by kamil-stripe** [comment]
This is going to be updated with the next release. Thank you for bringing this to our attention!
