### ISSUE TITLE
Cant update price - amount and currency 

### ISSUE THREAD

**Issue by Ch0c0l4tE** [stripe/stripe-go#1450]
Hi guys, 
I'm using the stripe-go lib to interact with stripe api, I was trying to build something to update a price that is attached to a product but when I use the price.Update I got an 400 error.

Go version 1.18
stripe-go version: v72.101.0

Code that reproduces the error: 
```
func (provider StripePaymentProvider) UpdatePrice(priceId *string, dto ...) (rpriceId *string, error error) {

	stripe.Key = "....."

	params := &stripe.PriceParams{
		Currency: stripe.String(strings.ToLower(....)),
		Recurring: &stripe.PriceRecurringParams{
			Interval:      stripe.String(strings.ToLower(string(....))),
			IntervalCount: stripe.Int64(....),
		},
		UnitAmount: stripe.Int64(....),
	}

	updatedPrice, err := price.Update(*priceId, params)

	if err != nil {
		return nil, err
	}

	return &updatedPrice.ID, err 
}
```

Error Message: 
`"{\"code\":\"parameter_unknown\",\"doc_url\":\"https://stripe.com/docs/error-codes/parameter-unknown\",\"status\":400,\"message\":\"Received unknown parameters: currency, unit_amount\",\"param\":\"currency\",\"request_id\":\"req_uMe3SMqUOtg7zW\",\"type\":\"invalid_request_error\"}"`

**Comment by remi-stripe** [comment]
@Ch0c0l4tE Github issues should be limited to bugs with the library itself. Your question is an integration support question and better directed at our support team [here](https://support.stripe.com/contact) or on our [Discord community server](https://stripe.com/go/developer-chat)

To provide more context though, this is not a bug. The Update Price [API](https://stripe.com/docs/api/prices/update) does not let you change the underlying currency or amount and such. You can only change a handful of properties on an existing Price such as `metadata` or `active`.
Instead, you should be creating a new Price via the [API](https://stripe.com/docs/api/prices/create) and separately mark the old one as `active: false`.
