### ISSUE TITLE
Adding "Shipping" to Customers

### ISSUE THREAD

**Issue by seenickcode** [stripe/stripe-go#147]
Hello,

I'm having some trouble associating shipping information with a new customer.  

I can't seem to find a "Shipping" struct field on the CustomerParams type (https://github.com/stripe/stripe-go/blob/d64e6480a8d6dee9d31ba24a4b9965e952395ded/customer.go) but the documentation states that there should be one:  https://stripe.com/docs/api/go#create_customer  On the other hand, I see it can be added to a Charge (https://github.com/stripe/stripe-go/blob/d64e6480a8d6dee9d31ba24a4b9965e952395ded/charge.go) 

I forked and created this feature:  https://github.com/seenickcode/stripe-go/blob/master/customer/client_test.go  Does this fix look appropriate?

Thanks,

**Comment by brandur** [comment]
@seenickcode Thank-you for reporting this! This seems very reminiscent of #87 where the original shipping information was added to "charge" and is likely just an oversight.

I see that you had to play around with import paths in your fork, but did you want to try and clean that up and contribute it back? If not, we can just add it on our end too.

**Comment by seenickcode** [comment]
Hey, for sure. I plan to revert the import paths and submit a pull request soon, unless you recommend another way to submit these new fixes/additions + tests.

**Comment by brandur** [comment]
> Hey, for sure. I plan to revert the import paths and submit a pull request soon, unless you recommend another way to submit these new fixes/additions + tests.

Nope, that sounds good!

(But again, totally up to you, we're happy to rebuild the changes over here if that's preferrable.)

**Comment by seenickcode** [comment]
Hey Brandur, just submitted my pull request
<https://github.com/stripe/stripe-go/pull/148>

**Comment by brandur** [comment]
Fixed by #148.
