### ISSUE TITLE
Add Relay support

### ISSUE THREAD

**Issue by steadicat** [stripe/stripe-go#149]
What’s the ETA for adding support for Orders and Products? The [docs for Go](https://stripe.com/docs/api#orders) already show code samples using features that don’t seem implemented yet.

**Comment by brandur** [comment]
Hi @steadicat! Thanks for logging this and our apologies for the delay in getting these features into the Go bindings.

Unfortunately I don't have an immediate update for you today, but please expect to see these integrated relatively soon. We'll bump this issue when they become available.

**Comment by brandur** [comment]
Closed by #154. Let us know if you find any problems. Thanks!
