### ISSUE TITLE
Support for Metrics Middleware

### ISSUE THREAD

**Issue by OilyLime** [stripe/stripe-go#1490]
### Is your feature request related to a problem? Please describe.

The problem: 

For operational purposes we'd like to have the rate, count and latency of all Stripe requests being made. These metrics could be used to build dashboards and alerts such that we have abundant signals for how applications are performing, what kind of traffic we're experiencing and whether or not our integrations with Stripe are functioning correctly.

### Describe the solution you'd like

A solution that would be general enough to support our usecase (and many others) would be the ability to pass middleware (as a slice of types that implement an interface) and have those middleware be called, in FILO order, when each request is dispatched to Stripe by the SDK.

We can imagine the middleware interface looking something like this:
```go
type StripeMiddleware interface {
	Before(r *http.Request)
	After(r *http.Response)
}
```

### Describe alternatives you've considered

Alternatives exist. We could define custom implementations of https://github.com/stripe/stripe-go/blob/master/stripe.go#L193 and pass those as the backends when initializing the Stripe client. It's not clear however whether this approach is recommended.

**Comment by pakrym-stripe** [comment]
Hi, thank you for your feature request. 

You have more than one existing option here:
1. The `Backend` infrastructure is supported and can be instrumented to collect the data you need
2. The `http.Client` can be instrumented by replacing transport and provided using `stripe.NewBackends(httpClient)`

```go
type CustomTransport struct {
	http.RoundTripper
}

func (ct *CustomTransport) RoundTrip(req *http.Request) (*http.Response, error) {
	println("Before")
	resp, err := ct.RoundTripper.RoundTrip(req)
	println("After")
	return resp, err
}

sc := &client.API{}
client := &http.Client{Transport: &CustomTransport{http.DefaultTransport}}
sc.Init("sk_key", stripe.NewBackends(client))

result, _ := sc......
```

The second option seems more generic as you can use the same code to instrument all HTTP-based communication in your application.

Please let us know if you see a limitation that these options have that the middlware design don't.

**Comment by Abrdjalw** [comment]
> 
https://github.com/stripe/stripe-go/issues/1490#issue-1291808317

**Comment by OilyLime** [comment]
@pakrym-stripe thank you! The latter solution seems like a good fit for our use case.
