### ISSUE TITLE
Subscription.Cancel does not return the subscription object (per spec)

### ISSUE THREAD

**Issue by hariananth** [stripe/stripe-go#150]
I'm referring specifically to [`func sub.Cancel(id string, params *stripe.SubParams) error`](https://github.com/stripe/stripe-go/blob/master/sub/client.go#L164)

The [spec](https://stripe.com/docs/api/go#cancel_subscription) specifies that canceling a subscription returns a "canceled subscription object". Looks like [all language examples except Go](https://stripe.com/docs/api/python#cancel_subscription) return the canceled subscription object. Especially since we can not fetch inactive subscriptions via the API, it would be awesome of at least the now-inactive subscription was returned to the Cancel call.

**Comment by remistr** [comment]
Hey @hariananth! Thank you for reporting this issue! It also seems to impact the customer deletion which only returns an error and not the resource. We'll work on a fix on our end for the future release.
