### ISSUE TITLE
One-off product metadata does not persist

### ISSUE THREAD

**Issue by salter31** [stripe/stripe-go#1515]
### Describe the bug

One-off product support and documentation feels very much like an afterthought and the rules around them either aren't functioning correctly, or there is missing documentation on this behavior.

The flow that I am using is very simple.
1. CreateSession via golang package that sets metadata on Line Items using ProductData. This metadata being sent can later be validated through the stripe dashboard UI on both a product page the events log.
2. Listen on web hooks for events
3. Use the session ID for appropriate events to retrieve the Line Items associated with that session
4. Try to collect the metadata gathered in step # 1

The only documentation I can find on the ProductData is [here](https://stripe.com/docs/api/checkout/sessions/create#create_checkout_session-line_items-price_data-product_data). I was digging around on the product page where I found this bubble that calls this type of product a "one-off". The product is archived in a special state where it doesn't show up under the archived page.
![Screen Shot 2022-08-01 at 4 53 09 PM](https://user-images.githubusercontent.com/5315889/182263864-165a693a-61cc-4c11-9e3f-d8acc17c1049.png)
The "archived" product has the correct metadata that I would expect. So I think it has something to do with the "one-off" nature of using ProductData. Also that label of "one-off" doesn't seem to appear anywhere in the documentation either.

### To Reproduce

1. make a line item with a config like 

```
&stripe.CheckoutSessionLineItemParams{
			PriceData: &stripe.CheckoutSessionLineItemPriceDataParams{
				Currency: stripe.String("usd"),
				ProductData: &stripe.CheckoutSessionLineItemPriceDataProductDataParams{
					Name:   "name",
					Metadata: map[string]string{
						"id":             "123",
						"something-else": "567",
					},
				},
				UnitAmount: stripe.Int64(100),
			},
			Quantity: stripe.Int64(1),
		})
```

3. using the example webhook event listener with switch case
```
var sess stripe.CheckoutSession
		err := json.Unmarshal(event.Data.Raw, &sess)
		if err != nil {
			return err
		}
		fmt.Printf("session %v\n", sess.Metadata)
		iter := session.ListLineItems(sess.ID, &stripe.CheckoutSessionListLineItemsParams{})
		for iter.Next() {
			d := iter.LineItem()
			fmt.Printf("item %v\n", d)
			fmt.Printf("product %v\n", d.Product)
			if d.Product != nil {
				fmt.Printf("product md %v\n", d.Product.Metadata)
			}
			fmt.Printf("price %v\n", d.Price.Metadata)
			if d.Price.Product != nil {
				fmt.Printf("price product %v\n", d.Price.Product.Metadata)
			}
		}
```
for `checkout.session.completed` events

### Expected behavior

I would expect either the metadata to persist since nowhere that I could find says it is a special case. We should be able to lookup the parent line items and retrieve the metadata that was set.

### OS

alpine

### Go version

1.18.3

### stripe-go version

v72.120.0

### API version

2020-08-27

### Additional context

On a personal note I am just using one-off payments because I don't want to have to duplicate inventory logic in another system and in stripe so I choose to keep the stripe logic minimal and use the other system primarily. I am using web hooks to decrement inventory counts as payments go through but ran into this issue.

Obviously I could just duplicate the product catalog into stripe and it should work, but I don't want to have to do that if I don't have to.

**Comment by remi-stripe** [comment]
@salter31 Thanks for the detailed bug report. I don't think there's a real bug here and it should just work as you assume it does. If you create a Session and set metadata on the underlying Product then the information lives on that Product.

The problem in your code is that you are not getting the real Product back. You only get the Product id back in your code when listing line items. So you get `product: 'prod_123'` in the API so metadata are not returned/retrieved. You have to explicitly **expand** ([doc](https://stripe.com/docs/expand)). If you did that you'd get the entire Product object back with its metadata as expected.

**Comment by salter31** [comment]
@remi-stripe thanks for the super fast response 👍 

Is Product even an expandable option? This is from the code itself.
`
// When retrieving a Checkout Session, there is an includable line_items property containing the first handful of those items. There is also a URL where you can retrieve the full (paginated) list of line items.
type CheckoutSessionListLineItemsParams struct {
`

When using this code
`	p := &stripe.CheckoutSessionListLineItemsParams{}
	p.AddExpand("data.line_items")
	iter := session.ListLineItems(sess.ID, p) // errors
`

I have tried product, data.product, line_items, data.line_items and all of them return 400s from the backend.

Seems like it should be straightforward from following the docs.

**Comment by remi-stripe** [comment]
We do have detailed docs on Expand here: https://stripe.com/docs/expand You would need to expand `line_items.data.price.product` when retrieving the Session to get the full Product object

This is not a bug with stripe-go though and is an integration support question that is better suited for our support team: https://support.stripe.com/contact/email

**Comment by salter31** [comment]
Thanks for the help, I got it working.

The working version is actually
`
		p := &stripe.CheckoutSessionListLineItemsParams{}
		p.AddExpand("data.price.product")
	        _ := session.ListLineItems(sessionID, p)
`

because `.ListLineItems(...)` calls the GET endpoint with the `/line_items` suffix already so that expansion prefix isn't needed. 

Since the server already responds with hints on errors it would be cool if it checked for redundant selectors since I doubt many expansions would actually use `X.X.Y` and be correct. I could be wrong though.
