### ISSUE TITLE
Webhook: ConstructEventOptions has only unexported fields

### ISSUE THREAD

**Issue by friedemannf** [stripe/stripe-go#1516]
### Describe the bug

While upgrading stripe-go from v72 to v73 I'm trying to retain the old behavior of ignoring an API version mismatch. The migration guide states:

> You can revert to the original behavior by switching to ConstructEventWithOptions and setting ignoreAPIVersionMismatch: false.

This newly added [ConstructEventOptions](https://github.com/stripe/stripe-go/blob/ddf143b8e906bee6215433302460f07e2c05be0b/webhook/client.go#L165) has only unexported fields, preventing access to `ignoreAPIVersionMismatch`. For the other two available options, this isn't as much of a problem as there are dedicated ConstructEventXX functions, but not for ignoring the API version.

Maybe I'm reading the migration guide wrong? If so, what's the intended way of restoring the old behavior?

### To Reproduce

1. Update stripe-go to v73
2. According to the migration guide, try to construct the webhook while ignoring the API version by using the new `ConstructEventWithOptions` instead of `ConstructEvent` 
3. There's no way of using the fields of `ConstructEventOptions` as described in the migration guide

### Expected behavior

I'd expect the `ConstructEventOptions.ignoreAPIVersionMismatch` to be exported as otherwise there would be a need for `ConstructEventOptions` to be exported or even the `ConstructEventWithOptions()` to exist.

### Code snippets

```Go
event, err := webhook.ConstructEventWithOptions(payload, signatureHeader, signingSecret, webhook.ConstructEventOptions{
		ignoreAPIVersionMismatch: true, // Unexported field usage
	})
```

### OS

macOS

### Go version

go1.18.5 darwin/arm64

### stripe-go version

v73.0.0

### API version

2022-08-01

**Comment by pakrym-stripe** [comment]
Hi, this is a bug. We'll ship a version with fields exported tomorrow and update the guide.

**Comment by friedemannf** [comment]
Hi @pakrym-stripe. Awesome, thanks for the quick reply!

**Comment by pakrym-stripe** [comment]
The fix is in https://github.com/stripe/stripe-go/releases/tag/v73.0.1
