### ISSUE TITLE
payment number 

### ISSUE THREAD

**Issue by wuqinqiang** [stripe/stripe-go#1518]
### Describe the solution you'd like

is there no payment number?

suppose I want to check the stripe payment information corresponding to my system order, what should I do ?
just idempotency_key?

**Comment by yejia-stripe** [comment]
Hi @wuqinqiang, GitHub issues for this repo are meant to be for feature requests or bugs with the library itself. It sounds like you have an integration question, which our support team is better equipped to answer. You can reach out to them at https://support.stripe.com/
