### ISSUE TITLE
Subscription property in the CheckoutSession struct has incorrect type

### ISSUE THREAD

**Issue by hirulez** [stripe/stripe-go#1527]
### Describe the bug

According to the docs Subscription property in CheckoutSession struct is a string:
https://stripe.com/docs/api/checkout/sessions/object#checkout_session_object-subscription

But in the v72 there is a Subscription object
<img width="858" alt="image" src="https://user-images.githubusercontent.com/7124955/185397792-9d123f77-c131-4cf0-a7ba-26ff9abf3b15.png">

### To Reproduce

Create var of type CheckoutSession and check Subscription property type

### Expected behavior

Subscription property to have type *string

### OS

macOs

### Go version

1.18.3

### stripe-go version

v72.67.0

### API version

2019-02-19

**Comment by kamil-stripe** [comment]
Hi @hirulez! Thank you for your report. The "Subscription" property is marked as expandable in the docs you have linked. That means you can request the property to be expanded and include more properties (see: https://github.com/stripe/stripe-go#expanding-objects). By default, only the ID property, which is a string, will be present in that object.
