### ISSUE TITLE
stripe.Error does not meet go Error interface

### ISSUE THREAD

**Issue by hampgoodwin** [stripe/stripe-go#1538]
### Describe the bug

the stripe.Error does not meet the go error interface because the method to meet the interface is a pointer receiver.

### To Reproduce

https://go.dev/play/p/n8vvMSQd5pl

^ run this in go playground, see the errors.

```go
// You can edit this code!
// Click here and start typing.
package main

import (
	"errors"
	"fmt"

	stripev72 "github.com/stripe/stripe-go/v72"
)

func main() {
	// simulate an error returned from any client call, let's say payment intents in this case
	err := paymentIntentClientCall
	if err != nil {
		var stripeErr stripev72.Error
		if errors.As(err, &stripeErr) {
			fmt.Println(stripeErr.Code)
		}
	}
}

func paymentIntentClientCall() error {
	return stripev72.Error{Code: stripev72.ErrorCodePaymentIntentUnexpectedState}
}
```

### Expected behavior

While the stripe-go lib does, somehow (I haven't dug deeply into how), return a go error, you cannot use the stripev72.Error type as a go error after the fact (errors.Is, errors.As, etc...), because the error does not meet the go error interface.

I expect to be able to use the stripe error type as a go error type to integrate it with the go error standard library code.

Instead, as document by stripe, we have to do a less safe type casting of the error. like so

### Code snippets

```Go
Instead of


var stripeErr stripev72.Error
if errors.As(err, &stripeErr) {
  // ....
}


We must

```go
		if stripeErr, ok := err.(*stripev72.Error); ok {
			switch stripeErr.Code {
			case stripev72.ErrorCodePaymentIntentUnexpectedState:
                        default:
                        }
                }
```
```


### OS

macOS

### Go version

Go 1.18 and Go 1.19

### stripe-go version

v72

### API version

2020-08-27

### Additional context

It would be great if it were somehow possible to not make the error interface a pointer method receiver

```go
func (e Error) Error() string {
	ret, _ := json.Marshal(e)
	return string(ret)
}
```

instead of

```go
func (e *Error) Error() string {
	ret, _ := json.Marshal(e)
	return string(ret)
}
```

----

https://github.com/stripe/stripe-go/blob/30ff791110756be379b979acc4ccba6eb4d50604/error.go#L217-L253

https://go.dev/play/p/n8vvMSQd5pl

**Comment by pakrym-stripe** [comment]
Hi @hampgoodwin ,

You can use `stripe.Error` both in `errors.As` and as an `error` return value.

```go

func main() {
	_, err := c.RetrievePaymentMethod("", &stripe.CustomerRetrievePaymentMethodParams{})
	if err != nil {
		var stripeErr *stripe.Error
		if errors.As(err, &stripeErr) {
			fmt.Println(stripeErr.Msg)
		}
	}
}

func test() error {
	return &stripe.Error{Code: stripe.ErrorCodePaymentIntentUnexpectedState}
}
```

https://go.dev/play/p/QM__Ondr-kG

**Comment by hampgoodwin** [comment]
Ok, this works in v73, it did not in v72.
I will say it's unusual to see a pointer receiver for the error interface meeting `(e *ErrorType) Error() string` method.
However, this seems to work now. Thanks.
