### ISSUE TITLE
Improve support for unit testing

### ISSUE THREAD

**Issue by palsivertsen** [stripe/stripe-go#1540]
### Is your feature request related to a problem? Please describe.

Writing unit tests for code that uses this SDK is sometimes difficult. Some functions returns concrete types without any exported fields, which really limits the options for mocking.

If I wanted to count the number of subscriptions I might create a simple service like this:
```go
package example

import (
	"fmt"

	"github.com/stripe/stripe-go/v73/client"
)

type Service struct {
	StripeClient *client.API
}

func (s Service) CountSubs() (int, error) {
	itr := s.StripeClient.Subscriptions.List(nil)

	var c int
	for itr.Next() {
		c++
	}

	if err := itr.Err(); err != nil {
		return 0, fmt.Errorf("itr subs: %w", err)
	}

	return c, nil
}
```

To make it easier to test I can create an abstraction for the Stripe client like so:
```go
package example

import (
	"fmt"

	"github.com/stripe/stripe-go/v73"
	"github.com/stripe/stripe-go/v73/subscription"
)

type SubscriptionClient interface {
	List(listParams *stripe.SubscriptionListParams) *subscription.Iter
}

type Service struct {
	Subscriptions SubscriptionClient
}

func (s Service) CountSubs() (int, error) {
	itr := s.Subscriptions.List(nil)

	var c int
	for itr.Next() {
		c++
	}

	if err := itr.Err(); err != nil {
		return 0, fmt.Errorf("itr subs: %w", err)
	}

	return c, nil
}
```

This will let me create a stub/mock of the client for use during testing:
```go
package example_test

import (
	"testing"

	"example"

	"github.com/stripe/stripe-go/v73"
	"github.com/stripe/stripe-go/v73/subscription"
)

type SubscriptionClientStub struct{}

func (s SubscriptionClientStub) List(listParams *stripe.SubscriptionListParams) *subscription.Iter {
	return &subscription.Iter{}
}

func TestService_CountSubs(t *testing.T) {
	t.Parallel()

	var stub SubscriptionClientStub

	unit := example.Service{
		Subscriptions: &stub,
	}

	c, err := unit.CountSubs()
	if err != nil {
		t.Fatalf("counting subs failed: %s", err)
	}
	if c != 0 {
		t.Fatalf("expected 0 subs but got: %d", c)
	}
}
```

But the problem is that I have no control over the return type `*subscription.Iter`. Using the zero value results in a nil pointer error and since there is no exported fields I can't control the amount of subscriptions either.

### Describe the solution you'd like

Functions and methods should return types that can be stubbed/mocked during testing.

Eg. in this example replacing the returned `*Iter` type with an interface would solve the problem. Alternatively the `Iter` struct could expose some way to control the data source.

### Describe alternatives you've considered

I know there's a stripe-mock library available but it wont let me control the output. Even if it did, it's a bit too complicated to set up for something this simple.

### Additional context

If internal test files where in separate packages (eg. `subscription_test`) then these kind of problems would be more apparent at development time.

**Comment by pakrym-stripe** [comment]
Hi @palsivertsen ,

You can use the `GetIter` method with a callback to create iterator stubs:

```golang
type SubscriptionClientStub struct{}

func (s SubscriptionClientStub) List(listParams *stripe.SubscriptionListParams) *subscription.Iter {
	return &subscription.Iter{
		Iter: stripe.GetIter(listParams, func(p *stripe.Params, b *form.Values) ([]interface{}, stripe.ListContainer, error) {
			ret := []interface{}{
				stripe.Subscription{
					ID: "sub_id",
				},
			}
			return ret, &stripe.SubscriptionList{}, nil
		}),
	}
}

func TestService_CountSubs(t *testing.T) {
	t.Parallel()

	var stub SubscriptionClientStub

	unit := example.Service{
		Subscriptions: &stub,
	}

	c, err := unit.CountSubs()
	if err != nil {
		t.Fatalf("counting subs failed: %s", err)
	}
	if c != 1 {
		t.Fatalf("expected 1 subs but got: %d", c)
	}
}
```

**Comment by pakrym-stripe** [comment]
Closing the issue as it had no engagement for a bit. Please reopen if you have more questions.
