### ISSUE TITLE
Pay() should be method on Order instance

### ISSUE THREAD

**Issue by steadicat** [stripe/stripe-go#156]
There’s a discrepancy between the docs and the implementation of the orders API. According to the [docs](https://stripe.com/docs/api#pay_order), `Pay` is a method on an `Order` instance. In the current implementation, `Pay` is a function that takes an order ID as its first argument. It would be great to update one or the other to match.

(In general it would be nice if the code samples in the docs were actually tested, but I can keep filing individual bugs as I find them. Let me know if this is not helpful.)

**Comment by brandur** [comment]
> (In general it would be nice if the code samples in the docs were actually tested, but I can keep filing individual bugs as I find them. Let me know if this is not helpful.)

Sorry about the trouble here :/ We're aware of this particular shortcoming and others in the bindings, and are working towards improving this experience. And your reports are definitely helpful! Please keep them coming.

**Comment by brandur** [comment]
@steadicat Hey! Sorry about the delay on this one.

I was just taking a look and it _looks_ like the docs are correct. The `Pay` method is located in the `order` _package_ with the signature:

``` go
func Pay(id string, params *stripe.OrderPayParams) (*stripe.Order, error) {
	return getC().Pay(id, params)
}
```

And the docs for Go suggest that you use:

```
orderPayParams = &stripe.OrderPayParams{}
orderPayParams.SetSource("tok_17Alsr2eZvKYlo2CT4srxJnV")
o, err := order.Pay(
  "or_16vFS92eZvKYlo2Cadn0nIaD",
  orderPayParams,
)
```

Rather than being an instance, I believe the `order` reference here is a meant to be a package. Does that make sense?

**Comment by steadicat** [comment]
Oh ok I must have misread. Thanks!
