### ISSUE TITLE
Price missing from docs?

### ISSUE THREAD

**Issue by andrewbaxter** [stripe/stripe-go#1576]
### Describe the bug

I can't see anything about prices in the docs.  ctrl+f only shows 4 hits, all in SKU. There's no price directory or files listed either... did I miss something huge?

### To Reproduce

Visit https://pkg.go.dev/github.com/stripe/stripe-go

### Expected behavior

Expecting to see at the very least `PriceParams`

### OS

chromium

### Go version

1.19.0

### stripe-go version

v70.15.0+incompatible

### API version

2020-08-27

**Comment by remi-stripe** [comment]
@andrewbaxter You're on an old version of stripe-go as that as I can tell from before Go modules which is from 2+ years ago.

Make sure to update to the most recent version (v74). We're also fixing the link to the reference in https://github.com/stripe/stripe-go/pull/1575 but you can look at the most recent docs at https://pkg.go.dev/github.com/stripe/stripe-go/v74 directly

**Comment by andrewbaxter** [comment]
Ah right, reference = repo.  Right, thanks!
