### ISSUE TITLE
Wiki documentation issue: Some `client#API` chenged is not updated

### ISSUE THREAD

**Issue by shiroemons** [stripe/stripe-go#1577]
### Describe the bug

Some `client#API` chenged in Wiki Migration guide for v73 is not updated.

### To Reproduce

- https://github.com/stripe/stripe-go/wiki/Migration-guide-for-v73#changed

`BalanceTransaction`, `CountrySpec`, and `PaymentSource` remain singular.
The new name is the same as the old name.

<img width="600" alt="chenged" src="https://user-images.githubusercontent.com/800753/203917788-7464999c-f8cf-411f-b584-21bd391acbbb.png">

### Expected behavior

Old name | New name |
:-- | :--
Account | Accounts
BalanceTransaction | BalanceTransactions
CountrySpec | CountrySpecs
PaymentSource | PaymentSources

### OS

N/A

### Go version

N/A

### stripe-go version

N/A

### API version

N/A

**Comment by anniel-stripe** [comment]
Hi @shiroemons , thank you for noticing this! I've fixed the migration guide with these changes.
