### ISSUE TITLE
Use expMonth and expYear in PaymentMethodCardParams in string format

### ISSUE THREAD

**Issue by AnthonyPrls** [stripe/stripe-go#1590]
### Is your feature request related to a problem? Please describe.

We'll like to use the `PaymentMethodCardParams` from here https://github.com/stripe/stripe-go/blob/5edf47fd7a79ac3358333df7ad1e7ce3c677f3c2/paymentmethod.go#L239 the problem is we're using Skyflow vault to create the card payment method and they required UUID in `expMonth` and `expYear`. Like the client using `PaymentMethodCardParams` is typed we can't use our own custom one.

### Describe the solution you'd like

The easy solution will be to have `*string` instead of `*Int64` for this fields but it will be less convenient to use this struct so maybe having a new struct `PaymentMethodCardVaultParams` could be the way to go.

**Comment by anniel-stripe** [comment]
Hello @AnthonyPrls , thank you for submitting this issue! We generate our SDKs to match the Stripe API specification, where [`expMonth` and `expYear` are integer fields on the PaymentMethod card](https://stripe.com/docs/api/payment_methods/object#payment_method_object-card-exp_month). As this is a feature request for the API, we recommend contacting Stripe Support at https://support.stripe.com/contact/.

**Comment by pakrym-stripe** [comment]
Closing as inactive. Feel free to reopen!
