### ISSUE TITLE
No way to manually resume a paused subscription

### ISSUE THREAD

**Issue by autovisasaaron** [stripe/stripe-go#1602]
### Describe the bug

If you set SubscriptionPauseCollectionParams to nil then it is never set on the body so never updated.

### To Reproduce

according to stripe documentation this code:

_, err = subscription.Update(sub.ID, &stripe.SubscriptionParams{
			PauseCollection: nil,
		})

should update a paused account to resumed, but it does not

### Expected behavior

Subscription should be resumed

### Code snippets

examples folder shows subscription.Resume(), but I get "Resume not declared by package subscription

### OS

Windows

### Go version

go1.19.2 windows/amd64

### stripe-go version

v74.5.0

### API version

2022-11-15

**Comment by remi-stripe** [comment]
@autovisasaaron In our API, the way you do this is by passing `pause_collection` as an empty string. Unfortunately this is not something stripe-go supports well today but it works with the `AddExtra` functionality like this:

```
params := &stripe.SubscriptionParams{}
params.AddExtra("pause_collection", "")
_, err = subscription.Update(sub.ID, params)
```

Definitely something we want to improve in the future but for now that should get you unblocked.
