### ISSUE TITLE
Encode payloads deterministically

### ISSUE THREAD

**Issue by zepatrik** [stripe/stripe-go#1606]
### Is your feature request related to a problem? Please describe.

Instead of mocking complex use-cases, we want to speed up our test pipeline by using https://github.com/google/go-replayers through using a custom `*http.Client`. The problem is now that the payloads are not deterministic with the custom form encoder included in this SDK. Specifically map types, as used for metadata, are not encoded deterministic and therefore mess with the replayer:

```
metadata[interval]=monthly&metadata[plan]=Essentials%400&customer=cus_NKH10bl....
metadata[plan]=Essentials%400&metadata[interval]=monthly&customer=cus_NKH10bl....
```

### Describe the solution you'd like

The payload should be encoded deterministically. This could either be achieved by

1. sorting keys
2. using the stdlib JSON

### Describe alternatives you've considered

1. sorting keys
2. using the stdlib JSON

**Comment by pakrym-stripe** [comment]
As discussed in the PR, we need to keep key order the same as the insertion order but sorting map keys when they are added to form collection looks like a good fix.
