### ISSUE TITLE
CheckoutSession.customer unmarshals to *Customer instead of a string (customer id)

### ISSUE THREAD

**Issue by tkrajina** [stripe/stripe-go#1650]
### Describe the bug

Hi,

I think there's a problem with the `CheckoutSession.customer` field:
```go
type CheckoutSession struct {
        ...
	// The ID of the customer for this Session.
	// For Checkout Sessions in `payment` or `subscription` mode, Checkout
	// will create a new customer object based on information provided
	// during the payment flow unless an existing customer was provided when
	// the Session was created.
	Customer *Customer `json:"customer"`
```
As the documentation for the `CheckoutSession.Customer` field says, it should contain `The ID of the customer` instead of a pointer to a `Customer`.

I understand I can use `event.Data.Raw` and `event.Data.Object` as a workaround, but the generated models should still unserialise from JSON by using the correct schema.

I went through https://stripe.com/docs/changelog to see if this was an API change, but couldn't find anything.

For example, the stripe-java library has:

```go
  /**
   * The ID of the customer for this Session. For Checkout Sessions in {@code payment} or {@code
   * subscription} mode, Checkout will create a new customer object based on information provided
   * during the payment flow unless an existing customer was provided when the Session was created.
   */
  @SerializedName("customer")
  @Getter(lombok.AccessLevel.NONE)
  @Setter(lombok.AccessLevel.NONE)
  ExpandableField<Customer> customer;


  /**
   * The customer details including the customer's tax exempt status and the customer's tax IDs.
   * Only the customer's email is present on Sessions in {@code setup} mode.
   */
  @SerializedName("customer_details")
  CustomerDetails customerDetails;
  ```

It is the same in `Charge` (and probably in other places):
```go
type Charge struct {
         ...
	// ID of the customer this charge is for if one exists.
	Customer *Customer `json:"customer"`
```

### To Reproduce

Clone the project and handle the `checkout.session.expired` event using `CheckoutSession`.

### Expected behavior

I'd expect `CheckoutSession.Customer` to be a `string`

### OS

all

### Go version

1.18

### stripe-go version

72 and 74

### API version

2019-03-14

**Comment by pakrym-stripe** [comment]
The `CheckoutSession.customer` is an expandable field meaning you can receive back an ID or an entire object depending on the request. When only the ID is received `Customer.ID` will be populated.
