### ISSUE TITLE
SetupIntentNextActionUseStripeSDK is always empty

### ISSUE THREAD

**Issue by davidgvf** [stripe/stripe-go#1674]
### Describe the bug

When a card number required action of SetupIntentNextAction use_stripe_sdk, always is empty field SetupIntentNextActionUseStripeSDK, why? 

### To Reproduce

create setup intent with card number test that required actions

### Expected behavior

d

### OS

last

### Go version

last

### stripe-go version

v72

### API version

last

**Comment by remi-stripe** [comment]
@davidgvf The `use_stripe_sdk` next action indicates that you need to use one of our official SDKs such as our Stripe.js library on the web or one of our Mobile SDKs to handle the next action. The content of that hash is purely opaque to developers and caters only to our libraries and can change at any point in time. So the next step for you is to handle the next action client-side in one of those SDKs.

If you have any follow up questions, please work directly with our support team instead for integration help: https://support.stripe.com/contact

**Comment by davidgvf** [comment]
@remi-stripe  thanks, but I don't use the sdk client, because I use the custom integration, I need to listen to what comes inside that object to open a webview, with the url it gives me inside SetupIntentNextAction

**Comment by remi-stripe** [comment]
You can't do that. Trying to access what is inside this hash will not work since the shape could change at any time on our end. You need to use our official SDKs in this case or contact our support team for further help.

**Comment by davidgvf** [comment]
okey, thanks for all
