### ISSUE TITLE
Plan object missing on Subscription object despite being present in Webhook Event

### ISSUE THREAD

**Issue by abraithwaite** [stripe/stripe-go#1681]
### Describe the bug

In the `customer.subscription.succeeded` event JSON, I see the `plan` object as a top-level attribute.

I want to access this using the Go SDK.

It appears undocumented here: https://stripe.com/docs/api/subscriptions/object

However, looking at the event itself, we can clearly see it's presence:

![Screenshot 2023-06-22 at 10 27 03 AM](https://github.com/stripe/stripe-go/assets/3791413/a833aa39-5430-4596-8a59-1475c40e4a5c)

### To Reproduce

```
stripe listen --format JSON -s --log-level error
stripe trigger customer.subscription.created
```

And look at the event produced.

### Expected behavior

I expect the plan object to be accessible through the Go SDK, and perhaps for the object to be documented in the API reference.

### OS

Linux, macOS

### Go version

Go 1.20.5

### stripe-go version

v74.22.0

### API version

2022-11-15

### Additional context

Looks like this is a regression between v72 and v74.  I see the plan object on v72 godoc.

**Comment by remi-stripe** [comment]
@abraithwaite The `plan` property on Subscription has been deprecated for many years now so it's expected that it's not in types and undocumented. See https://github.com/stripe/stripe-node/issues/1794 for a longer explanation as to why.
We recommend using `items.data[xxx].price` instead!

**Comment by abraithwaite** [comment]
Gotcha, thanks for the quick response and link to detailed explanation!
