### ISSUE TITLE
Make it easier to add subscription schedule phases

### ISSUE THREAD

**Issue by palsivertsen** [stripe/stripe-go#1686]
### Is your feature request related to a problem? Please describe.

I want to add a phase to an existing subscription schedule, keeping any existing phases as is.

I can easily get the subscription phases (`stripe.SubscriptionSchedulePhase`) from `stripe.SubscriptionSchedule`, but the `SubscriptionSchedules.Update` API expects a different type for phases (`stripe.SubscriptionSchedulePhaseParams`).

### Describe the solution you'd like

An API to append phases to a schedule

or

A convenient way to add the `stripe.SubscriptionSchedulePhase` type to `SubscriptionScheduleParams.Phases` field.

### Describe alternatives you've considered

Manually mapping fields in `stripe.SubscriptionSchedulePhase` to corresponding fields in `stripe.SubscriptionSchedulePhaseParams`, but this is tricky since there's a lot of nil checks and type conversion needed.

### Additional context

An example highlighting the issue:
https://go.dev/play/p/OECbCh3ysgt

**Comment by remi-stripe** [comment]
Hey @palsivertsen ! Github issues are limited to bugs with the library itself and this is more an API feature request better directed at our support team: https://support.stripe.com/contact

We're definitely aware that adding/appending/amending phases can be quite complex and we're looking into potential future improvements such as an API to specifically amend one phase for example or append one at the end without having to re-pass all the phase details. No timeline for a ship just yet but know that we're looking into this as we have heard similar feedback before.
