### ISSUE TITLE
Empty refund list in the charge object

### ISSUE THREAD

**Issue by mudassirkhan19** [stripe/stripe-go#1695]
### Describe the bug

I'm trying to retrieve the reason for refunded charge in by listening to the `charge.refunded` event, in the event data in the dashboard, I'm able to see the refunds, but in the charge object its always showing empty:
```go
Refunds:                   (*stripe.RefundList)(nil)
```
The refunds in the webhook obtained from the dashboard:
```json
"refunds": {
      "object": "list",
      "data": [
        {
          "id": "re_1NZwmVBQzictNbDF63sle8VP",
          "object": "refund",
          "amount": 400000,
          "balance_transaction": "txn_1NZwmXBQzictNbDFoLYMQzQk",
          "charge": "ch_1NZwlpBQzictNbDFcI05JCDZ",
          "created": 1690812547,
          "currency": "inr",
          "metadata": {
          },
          "payment_intent": "pi_1NZwlpBQzictNbDFZ9PTCUsr",
          "reason": "requested_by_customer",
          "receipt_number": null,
          "source_transfer_reversal": null,
          "status": "succeeded",
          "transfer_reversal": null
        }
      ],
      "has_more": false,
      "total_count": 1,
      "url": "/v1/charges/ch_1NZwlpBQzictNbDFcI05JCDZ/refunds"
    },
```
I also tried retrieving the charge using the API but I'm still getting empty refunds. 

### To Reproduce

1. Fetch a charge object with refunds
2. Try to access the refund list

### Expected behavior

The refunds object should be populated.

### OS

macOS

### Go version

Go 1.18.10

### stripe-go version

v74.27.0

### API version

2022-11-15

**Comment by remi-stripe** [comment]
@mudassirkhan19 Github issues are limited to bugs with the stripe-go library itself. Your question is more an integration support question better directed at our support team as this is not a support forum. You can contact them here: https://support.stripe.com/contact 

To unblock you though I can explain that this is expected today. In the latest API version, [2022-11-15](https://stripe.com/docs/upgrades#2022-11-15), removed the `refunds` collection on the `Charge` object by default to improve latency of the API but it's leading to this confusion unfortunately. We do want to add a `refund.created` Event for this in the future, but for now your best option is to use the List Refunds [API](https://stripe.com/docs/api/refunds/list) instead.
