### ISSUE TITLE
Upgrading API versions cannot be done cleanly

### ISSUE THREAD

**Issue by jameshartig** [stripe/stripe-go#1698]
### Is your feature request related to a problem? Please describe.

The README suggests upgrading to a new major version:
> If you are on an older major version, we recommend that you upgrade to the latest in order to use the new features and bug fixes including those for security vulnerabilities.

However, upgrades cannot be done cleanly for webhooks with this package as-is. Take the following change to `paymentintent.go` [1] where `Charges` was deleted and replaced with `LatestCharge`. If unmarshalling an event from an old API version you no longer get any charge information but if you're using the new API version then everything works fine. If you upgrade your API version **after** deploying the latest Go version then any events created in between deploying and upgrading will forever be incorrectly processed. Since the docs say the shape of resources is defined by the API version at the time the event occurred [2].

This is further exacerbated by the fact that your default API version in "test mode" cannot be different than your live version so you can't "test" your upgrade to the latest go major version before putting it live.

[1] https://github.com/stripe/stripe-go/commit/85af7bbdf8f5b880aae78736e6891593fa7f4ce2#diff-fe711f55ea185d786c949c3c5b624a0aacef0ddfc6e0690eb083d78a41f3fb64
[2] https://stripe.com/docs/upgrades#how-can-i-upgrade-my-api

### Describe the solution you'd like

The Stripe recommendation [1] is that you should:
> Update your webhook code to handle both the old and new version of each object.

But that is not what this library does. Ideally in the change to `paymentintent.go` referenced above the unmarshal code would've detected an older `charges` array and took the charge from that array and set it as `LatestCharge`.

[1] https://stripe.com/docs/upgrades#how-can-i-upgrade-my-api

### Describe alternatives you've considered

Instead our webhook code could always ignore objects inside webhook events and always fetch those objects which should send a header indicating our desired version but this seems very inefficient.

**Comment by remi-stripe** [comment]
@jameshartig What we usually recommend is what is in your quote: have two separate WebhookEndpoints, one pinned to each version of the API you want to test and then in your webhook handler, process the version of the Event mapped to the API version your code is expected (based on the version of stripe-go) you're running, and ignore the other one which isn't compatible.

There isn't really a way for stripe-go to adapt safely here. The change you took is really simple where we used to have a `charges` as a sub-list and now it's just a string of the most recent one. But it's not as straightforward for many of the breaking API changes that have existed over the years as most don't have a straightforward translation.

**Comment by jameshartig** [comment]
@remi-stripe if I understand correctly, we would define an "default" endpoint that is pointed at the default version, then when we're ready to upgrade we'd deploy the new stripe library to a "next" endpoint (which has a different url than the "default" endpoint) and define that webhook as the latest version. In either webhook handler the code would call `webhook.ConstructEvent` and if the error complains about the API version we would just return 200 OK and ignore the event.

Do you think the library could expose a specific error that we could check for with `errors.Is` to understand if its an API version error rather than checking the error string?

**Comment by remi-stripe** [comment]
@jameshartig what you described is what I would do yes and I'd recommend always having my webhook endpoints pinned to a specific API version. What you could do is use the same URL but have the expected API version as a query parameter like `https://example.com/webhook?api_version=YYYY-MM-DD`.
When we generate Event A, we'd do it for each version of your endpoints and we'd send the right version to the right endpoint. Your code can look at that parameter, check if it matches your current library's expected version and react accordingly.
Alternatively, you can parse the raw JSON to look at the `api_version` property and only use `ConstructEvent` when it matches.

Overall though your ask is a good feature request. We'd have to implement this in stripe-java and stripe-dotnet too which have subtly different behaviour and interfaces but it's something we might consider adding in the future.

Did you have any additional questions about this or do you think you have enough to build this right?

**Comment by jameshartig** [comment]
@remi-stripe Thanks for the detailed response and the help! Yes, I think I have enough to go off of now.
