### ISSUE TITLE
Missing Version Tags

### ISSUE THREAD

**Issue by jeffutter** [stripe/stripe-go#172]
According to the readme: "Each revision of the binding is tagged and the version is updated accordingly." However, it appears the last tag is v8.0.0 while the version number is up to 10.3.0 . Could we get the tags updated?

Thanks

**Comment by brandur** [comment]
Hey @jeffutter, sorry about the trouble here! The Go bindings are the only ones which we don't have an automated release process for, and it's easy for some steps to get skipped accidentally. We'll work on getting that tightened up.

In the meantime, I've manually tagged the last 5 releases. Let us know if you run into any other trouble. Thanks!

**Comment by iamrgon** [comment]
Hey @brandur, this seems to still be happening – the last tagged release was 10.3.0. Thanks in advance!

**Comment by brandur** [comment]
Ugh, sorry @iamrgon! Obviously I still don't have the automated process finished up.

Just pushed v11.0.0, v11.0.1, v11.1.0, v11.1.1, and v11.1.2.

Thanks for the heads up!

**Comment by iamrgon** [comment]
No worries. Thanks!
