### ISSUE TITLE
initUserAgent is slow

### ISSUE THREAD

**Issue by egonelbre** [stripe/stripe-go#1728]
### Describe the bug

initUserAgent is relatively slow (100ms) and is run always, even when stripe client is not being used.

https://github.com/stripe/stripe-go/blob/d038ebbf7b3100fb94bfb4ac21874a5dbfaba25e/stripe.go#L1357

### To Reproduce

```
func BenchmarkInitUserAgent(b *testing.B) {
	for i := 0; i < b.N; i++ {
		initUserAgent()
	}
}
```

```
$ go test -bench InitUserAgent -run "$^"
goos: windows
goarch: amd64
pkg: github.com/stripe/stripe-go/v75
cpu: AMD Ryzen Threadripper 2950X 16-Core Processor
BenchmarkInitUserAgent-32             12          92528067 ns/op
```

Note, the performance on Mac/Linux can be different, because the os exec overhead is smaller.

### Expected behavior

initUserAgent is done on-demand / lazily rather than in `init`.

### OS

Windows 11

### Go version

Go 1.21.1

### stripe-go version

master

### API version

not-relevant

### Additional context

This slows down tests unrelated to stripe.

**Comment by pakrym-stripe** [comment]
The fix will ship next week.
