### ISSUE TITLE
Custom backend implementation issues with deprecation of `Params.Metadata`

### ISSUE THREAD

**Issue by zepatrik** [stripe/stripe-go#1794]
### Is your feature request related to a problem? Please describe.

We use a custom backend for unit tests to add metadata to the objects automatically. Until now, we used this code:

```go
func addMeta(method, path string, params stripe.ParamsContainer) {
	if params == nil || (reflect.ValueOf(params).Kind() == reflect.Ptr && reflect.ValueOf(params).IsNil()) {
		params = &stripe.Params{}
	}
	_, hasMetaAlready := params.GetParams().Metadata[MetaKeyTestdata]
	if method == http.MethodPost && !hasMetaAlready {
		params.GetParams().AddMetadata(MetaKeyTestdata, MetaValueTestdata)
	}
}

func (s *TestdataBackend) Call(method, path, key string, params stripe.ParamsContainer, v stripe.LastResponseSetter) error {
	addMeta(method, path, params)
	return s.Backend.Call(method, path, key, params, v)
}
```

### Describe the solution you'd like

Ideally, the backend would use this signature:

```go
type Backend interface {
	Call(method, path, key string, params GenericParam, v LastResponseSetter) error
	// ... CallStreaming and the others the same way
}

type GenericParam interface {
	SetMetadata(key, value string) // already exists
	GetMetadata(key string) string // new on all structs
	GetMetadata() map[string]string // alternative
}
```

This would allow the usage of the non-deprecated metadata fields without reflection, type assertions, type switches, or other workarounds.

### Describe alternatives you've considered

Any other generic interface that allows modification and reading of the metadata and other common fields for all structs.

**Comment by pakrym-stripe** [comment]
Hi @zepatrik!

There is no guarantee that every resource will have a metadata collection, and we don't want to encode the wrong assumption in the SDK types. That was the thinking behind the original change that made 'Metadata' on the shared 'Params' type deprecated.

Defining the interface that all params have to implement will effectively reverses the change.

**Comment by zepatrik** [comment]
I see, that makes sense. It was just quite confusing that this change removed some of the flexibility we had, without a clear migration path. I guess we'll have to go with type assertions or reflection then, once the metadata are removed from the shared params.

**Comment by pakrym-stripe** [comment]
>Defining a common getter & setter interface would however still be useful for type assertions, as that is a lot easier than reflection

We'll keep an eye on similar requests in the future to see if there is more interest.

I'm going to close this issue as we won't be implementing the original suggestion.
