### ISSUE TITLE
Billing quickstart contains invalid code

### ISSUE THREAD

**Issue by ustun-ed** [stripe/stripe-go#1804]
### Describe the bug

The billing quickstart Go example code calls `.Front` which does not exist in this library: 

https://stripe.com/docs/billing/quickstart 

```
    i := price.List(params)
    if !i.Front() {
      log.Printf(">>>>>>>>>>>>>>>>>>>>>>>>>>> Add a price lookup key to checkout.html line 27 for the demo <<<<<<<<<<<<<<<<<<<<<<<<")
    }
```

### To Reproduce

1. Download Full App from 
https://stripe.com/docs/billing/quickstart
2. Try running `go run server.go`

### Expected behavior

```
> go run server.go
# command-line-arguments
./server.go:50:8: i.Front undefined (type *price.Iter has no field or method Front)
```

### OS

macOS

### Go version

go1.19.13

### stripe-go version

v76.0.0

### API version

Latest

**Comment by remi-stripe** [comment]
@ustun-ed Thanks for flagging! In the future this is best flagged to our support team instead of here as it's unrelated to the SDK itself but I'll flag to get it fixed!

**Comment by dreamerlzl** [comment]
@ustun-ed Hi, how did you solve this later?
