### ISSUE TITLE
Minor typo on wiki for v73 migration

### ISSUE THREAD

**Issue by arseniocosta1** [stripe/stripe-go#1826]
### Describe the bug

Please excuse me if this is not the correct template 🙇 , but couldn't find an appropriate one
I would do a PR but GH and Wiki's PRs 🤷 

There's a small typo on https://github.com/stripe/stripe-go/wiki/Migration-guide-for-v73#:~:text=CustomerInvoiceSettingsCustomField-,Customer,Customer%20dInvoiceSettingsCustomFieldParams,-Customer

`Customer dInvoiceSettingsCustomFieldParams` should be `CustomerInvoiceSettingsCustomFieldParams`me 

### To Reproduce

None this is a typo on the doc

### Expected behavior

no typo

### OS

Any browser

### Go version

any

### stripe-go version

v73

### API version

any

**Comment by anniel-stripe** [comment]
Hi there @arseniocosta1 ! Thanks so much for letting us know. Just updated.
