### ISSUE TITLE
Invalid header value Authorization when using Environment variable

### ISSUE THREAD

**Issue by Dmarcotrigiano** [stripe/stripe-go#1855]
### Describe the bug

I have this scenario, where the log is outputting the correct key, replacing the parameter in `client.New` with the key hardcoded produces a satisfactory response.

```go
	ssk := os.Getenv("STRIPE_SECRET_KEY")
	if ssk == "" {
		return nil, errors.New("STRIPE_SECRET_KEY not set")
	}
	slog.Debug(ssk)

	client := client.New(ssk, nil)
```
```
[usage] [ERROR] Request failed with error: Get "https://api.stripe.com/v1/billing/meters?display_name[%3D]=Transcript+Billing+Meter": net/http: invalid header field value for "Authorization"
[usage] [ERROR] Request failed with error: Post "https://api.stripe.com/v1/billing/meters": net/http: invalid header field value for "Authorization"
[usage] [ERROR] Request failed with error: Get "https://api.stripe.com/v1/products?name[%3D]=Transcript+API": net/http: invalid header field value for "Authorization"
[usage] [ERROR] Request failed with error: Post "https://api.stripe.com/v1/products": net/http: invalid header field value for "Authorization"
```
Implementation of client:
```go
func (s *Stripe) createProduct(name, description string) (*stripe.Product, error) {
	params := &stripe.ProductParams{
		Name:        stripe.String(name),
		Description: stripe.String(description),
	}
	product, err := s.client.Products.New(params)
	if err != nil {
		return nil, err
	}
	return product, nil
}
```
```go
func (s *Stripe) getBillingMetersByDisplayName(displayName string) (*stripe.BillingMeter, error) {
	filters := stripe.Filters{}
	filters.AddFilter(DISPLAY_NAME, "=", displayName)
	params := &stripe.BillingMeterListParams{
		ListParams: stripe.ListParams{
			Filters: filters,
		},
	}
	i := s.client.BillingMeters.List(params)
	if !i.Next() {
		return nil, nil
	}
	return i.BillingMeter(), nil
}
```

### To Reproduce

I can only reproduce this by using an environment variable as the parameter to the client initializer.

### Expected behavior

The usage of an environment variable should be identical to the usage of a string.

### OS

Linux Ubuntu

### Go version

1.22

### stripe-go version

v78.4.0

### API version

2024-04-10

**Comment by remi-stripe** [comment]
@Dmarcotrigiano Are you sure you have a valid Secret API key in that environment variable without any trailing spaces or line feed or similar?

Here's what I just tried for example locally

```
ssk := os.Getenv("STRIPE_SECRET_KEY")
fmt.Printf("Got: \n", ssk)

sc := &client.API{}
sc.Init(ssk, nil)

params := &stripe.CustomerParams{}
cus, _ := sc.Customers.New(params)
```

I then run this with ` STRIPE_SECRET_KEY=sk_test_123 go run client_with_environment_variable.go` and my key is parsed properly and the the API cleanly errors as `sk_test_123` is not a valid API key.

**Comment by Dmarcotrigiano** [comment]
@remi-stripe I am positive, I replaced the key with the logged value from the debug line and it worked as expected. 

- I added a space after the string to see if that was the issue, and it also accepted that hardcoded string. 
- A hardcoded space is detected as an empty api key.

I have about a months experience in Go so I don't know if these details are valuable but, I am using skaffold, building these images with `ko`, running them in local k8s using Minikube.

I can verify that the key is present in the pod, it is being read and logged in the code.

**Comment by Dmarcotrigiano** [comment]
What extracted value from the environment causes an invalid header field value?

**Comment by harveysanders** [comment]
Your key value you may have a newline (`\n`). I was able to reproduce the issue by adding a trailing newline to the secret:
```go
sc := client.New("sk_test_123\n", nil)
i := sc.Events.List(nil)
if i.Err() != nil {
    fmt.Println(err)
}
```

```
[ERROR] Request failed with error: Get "https://api.stripe.com/v1/events": net/http: invalid header field value for "Authorization"
[ERROR] Request failed with error: Get "https://api.stripe.com/v1/events": net/http: invalid header field value for "Authorization"
[ERROR] Request failed with error: Get "https://api.stripe.com/v1/events": net/http: invalid header field value for "Authorization"

Get "https://api.stripe.com/v1/events": net/http: invalid header field value for "Authorization"
```

**Comment by remi-stripe** [comment]
This comes from within the `net/http` go package and not Stripe so it would be their validation and might differ on go versions. I am on `1.22.2` locally though so we are on the same version. I worked with another person on my team who also makes this work totally fine with both `client.API` and `client.New` without issues.

At the moment, it really points to your system having an invalid character inside that environment variable causing the go package to reject the header.

**Comment by Dmarcotrigiano** [comment]
The key had a trailing newline, thanks everyone!
