### ISSUE TITLE
Unable to update card expiration month or year

### ISSUE THREAD

**Issue by wjohnson191** [stripe/stripe-go#186]
In the update card documentation, `exp_month` and `exp_year` are listed as valid fields to update:
https://stripe.com/docs/api/go#update_card

However, `func (c *CardParams) AppendDetails(values *url.Values, creating bool)` seems to ignore the `c.Month` and `c.Year` fields when `creating == false` (it only touches them when `creating == true`), making it impossible to update the card expiration month or year:
https://github.com/stripe/stripe-go/blob/babc9d3fcdcb25115b82681f5e2d0822146cffac/card.go#L78

**Comment by brandur** [comment]
@wjohnson191 Thanks a lot for taking the trouble to report this! Fixed as part of #187.

**Comment by wjohnson191** [comment]
Great, thanks!
