### ISSUE TITLE
Missing GeneratedFrom property of PaymentMethodCard type

### ISSUE THREAD

**Issue by serhii-chechun** [stripe/stripe-go#1866]
### Describe the bug

[Official API docs](https://docs.stripe.com/api/payment_methods/object) has it described and cURL response does return card.generated_from property as part of PaymentMethod object, but none of the SDK clients has it defined as data type property 

### To Reproduce

Type definition `stripe.PaymentMethodCard` has no Property `GeneratedFrom`, but raw response has it as `card.generated_from`

### Expected behavior

`stripe.PaymentMethodCard.GeneratedFrom` type definition must be defined as part of the API client data structure

### OS

macOS

### Go version

Go 1.22.3

### stripe-go version

v78.7.0

### API version

2024-04-10

**Comment by remi-stripe** [comment]
Thanks for flagging! It looks like this is incorrectly suppressed internally for our SDKs generation. We'll look into a fix soon!

**Comment by prathmesh-stripe** [comment]
This has been fixed in the latest SDK [release](https://github.com/stripe/stripe-go/releases/tag/v78.9.0). Can you try out the latest SDK version and check if your issue has been resolved.
