### ISSUE TITLE
The bindings should handle the `destination` parameter on the Transfer object

### ISSUE THREAD

**Issue by remistr** [stripe/stripe-go#193]
The `destination` [parameter](https://stripe.com/docs/api#transfer_object-destination) isn't handled currently. It can be an Account, a BankAccount or a Card right now so it will need some parent class.

Looks similar to the discussion in https://github.com/stripe/stripe-go/pull/169

**Comment by brandur** [comment]
Doh, thanks @remistr! I lost track of this one somehow, but let's take a look at it soon.

**Comment by MDrollette** [comment]
Same story for `source` on `Transaction`'s. There should be a way to get the object if it's expanded.

**Comment by MDrollette** [comment]
This can be closed as it's supported as of 17.0.0 by #294

**Comment by brandur** [comment]
@MDrollette +1. Thanks again!
