### ISSUE TITLE
You cannot specify both the (deprecated) .Params.Metadata and .Metadata, for SubscriptionCancelParams

### ISSUE THREAD

**Issue by J7mbo** [stripe/stripe-go#1944]
### Describe the bug

I have an error when trying to attach metadata to SubscriptionCancelParams:

> You cannot specify both the (deprecated) .Params.Metadata and .Metadata in SubscriptionCancelParams

I get the same error from:

```go
params := &stripe.SubscriptionCancelParams{}
params.AddMetadata("user_id", userID)

if _, err := c.sdk.Subscriptions.Cancel(subscriptionID, params); err != nil {
    return fmt.Errorf("error canceling subscription: %v", err)
}
```

and also from:

```go
params := &stripe.SubscriptionCancelParams{Params: stripe.Params{Metadata: map[string]string{"user_id": userID}}}

if _, err := c.sdk.Subscriptions.Cancel(subscriptionID, params); err != nil {
    return fmt.Errorf("error canceling subscription: %v", err)
}
```

---

Problems:

1. It's not clear which is not allowed, or if Metadata just isn't allowed at all?
2. If Metadata isn't allowed, then what's the point of listening to the webhook `customer.subscription.deleted` if I can't even pluck out the user id of the person that cancelled? If that's the case, then the event is useless for me.

### To Reproduce

Try the code above.

### Expected behavior

I can attach metadata to SubscriptionCancelParams without an error.

### OS

macOS

### Go version

go version go1.23.2 darwin/arm64

### stripe-go version

v80

### API version

latest

**Comment by seanzhang-stripe** [comment]
Hi @J7mbo `metadata` isn't a valid param for subscription cancellation. You can refer to the [API reference](https://docs.stripe.com/api/subscriptions/cancel) for the list of params that you can pass when cancelling a subscription.

If you really need to attach a metadata to a subscription, you should use the [update API](https://docs.stripe.com/api/subscriptions/update?lang=curl#update_subscription-metadata)
