### ISSUE TITLE
How do we fetch balance transactions for a managed account?

### ISSUE THREAD

**Issue by aravind88** [stripe/stripe-go#196]
I am trying to fetch a list of all transactions based on the [List All Balance History](https://stripe.com/docs/api/go#balance_history) API. However, I want do it for a particular managed account. 

I see that Params struct has a `Account` field that is used to set the Account header.
```
// Params is the structure that contains the common properties
// of any *Params structure.
type Params struct {
	Exp                     []string
	Meta                    map[string]string
	Extra                   url.Values
	IdempotencyKey, Account string
}
```
```
if account := strings.TrimSpace(params.Account); account != "" {
    req.Header.Add("Stripe-Account", account)
}
```

However, I could not find an `Account` field for the ListParams. Is there another way to set the `Stripe-Account` header for all the `$resource$.List(stripe.$Resource$ListParams)` calls?

**Comment by brandur** [comment]
Hi @aravind88, it looks like this is a legitimate blind spot in the bindings' functionality when it comes to managed accounts. A colleague and I are going to take a look and try to get a patch together. Thanks for reporting the problem!
