### ISSUE TITLE
Product Metadata is empty when retrieving from the subscription object

### ISSUE THREAD

**Issue by hadiweslati** [stripe/stripe-go#1960]
### Describe the bug

Hello, 
I tried to retrieve a Metadata that I set on a product from the subscription object. 
![image](https://github.com/user-attachments/assets/b3019c5f-44b2-46c0-af08-719ebee22314)
As on the image above, I printed the Metadata map of the Product that already has a Metadata, but it's returning empty map. 
I'm using latest stripe-go version v81

### To Reproduce

1. Set a Metadata on a product
2. Use checkout session to purchase a subscription
3. Grap the subscription ID and use subscription.Get() to get the subscription object 
4. Check sub.Items.Data[0].Plan.Product.Metadata

### Expected behavior

sub.Items.Data[0].Plan.Product.Metadata should have the Metadata: 
![image](https://github.com/user-attachments/assets/e90822da-cbf0-417f-b4ab-7717d4cf976e)

### OS

macOs

### Go version

Go 1.21

### stripe-go version

v81.1.1

### API version

2024-04-10

**Comment by jar-stripe** [comment]
Hi @hadiweslati thanks for reporting this.  We will take a look!

**Comment by jar-stripe** [comment]
@hadiweslati : Product is an [expandable field](https://github.com/stripe/stripe-go?tab=readme-ov-file#expanding-objects) on Plan, so you need to modify your code to include SubscriptionParams as such:
```go
p := stripe.SubscriptionParams{}
p.AddExpand("items.data.plan.product")
sub, err := subscription.Get(subscriptionId, &p)
```

`sub.Items.Data[0].Plan.Product.Metadata` should then contain the metadata you are looking for.

Let me know how it goes!

**Comment by hadiweslati** [comment]
Indeed, when adding p.AddExpand("items.data.plan.product") the returned metadata was not empty any more. 
Thank you 💯
