### ISSUE TITLE
Outdated Link in Docs: Account_object-controller-requirement_collection

### ISSUE THREAD

**Issue by adrianbartnik-sc** [stripe/stripe-go#1961]
### Describe the bug

The SDK contains a couple of references to `[controller.requirement_collection](https://stripe.com/api/accounts/object#account_object-controller-requirement_collection)`. However, the link leads to an empty page.

Instead, it should be `https://docs.stripe.com/api/accounts/object#account_object-controller-requirement_collection`.

### To Reproduce

Search through the code & do a search and replace.

### Expected behavior

The link should point to the right location.

### OS

macOS

### Go version

Go 1.23

### stripe-go version

latest

### API version

2020-08-27

**Comment by jar-stripe** [comment]
Thanks for reporting this!  This is not directly an SDK issue (i.e. the broken links are in generated code) but I have passed this on to the relevant team to take a look.  Closing this issue for now; this will be fixed after we rebuild against the latest spec.
