### ISSUE TITLE
Invoice preview, no subscription_plan

### ISSUE THREAD

**Issue by dstpierre** [stripe/stripe-go#198]
On the documentation, there's a `subscription_plan` field we can pass to `invoice.GetNext`'s `&stripe.InvoiceParams`.

I'm not finding anything on the `invoice.go`'s `Invoice` struct. I guess `subscription` on the doc is `Sub`, but no way to pass plan.

Any help would be appreciated, getting a preview of a plan change is required at the moment to show to users the effect of prorating etc.

Thanks

**Comment by brandur** [comment]
Added a fix in #200.

**Comment by dstpierre** [comment]
Thanks, and yes, my PR was wrongly targeting the `Invoice` ;)

**Comment by brandur** [comment]
@dstpierre Fix released as 11.4.0.
