### ISSUE TITLE
No way to set API Version

### ISSUE THREAD

**Issue by aodin** [stripe/stripe-go#204]
There is currently no way to set the API version. The [API documentation](https://stripe.com/docs/api/go#versioning) states:

> Since Go is strongly typed, the version is fixed in the library. Revert to an older version of the library to change the API version used.

However, since the Go library is more than 6 months behind current API version, being able to set the version header would be incredibly useful for testing / future-proofing. Additionally, the Java library allows the API version to be set.

Would it be alright if I submitted a patch that allowed the version to be set - perhaps with a warning "use at your own risk"?

**Comment by brandur** [comment]
@aodin To the point of an outdated version: we should be doing a better job of having the bindings follow what's in production. I've logged #205 to remind me to bump the version in these bindings.

> Would it be alright if I submitted a patch that allowed the version to be set - perhaps with a warning "use at your own risk"?

Although I think it opens up the possibility of users getting themselves into trouble by setting it at some point and then forgetting they did so, I think that adding a version switcher would be fine as long as it came with the caveat that it's expected to be used largely for debugging only.

Does anyone else on @stripe/api-libraries have feelings on that one?

**Comment by kyleconroy** [comment]
The Go bindings were designed to work with a specific version of the Stripe API. Allowing the version to be set would possible break the bindings. I'm not sure we're ready to commit to support using the Go bindings with any version of the Stripe API.

I'd rather we just commit to updating the bindings ever time we release a new version.

@cosn also probably has feeling about this.

**Comment by cosn** [comment]
Yeah, I'm not sure what problem passing a version dynamically solves. Since the bindings are strongly typed, if there's a new field added, it requires updates to the struct for it to work. Basically the structs are a snapshot in time for a given version.

It's likely I'm missing some scenario though...

**Comment by aodin** [comment]
@cosn Specifying a version always us to independently verify that the Go library has not become decoupled from the latest Stripe API (without forking)

**Comment by cosn** [comment]
@aodin: sorry, what do you mean? The Go binding always becomes decoupled with a new API update until it's updated back to that version, no?

**Comment by aodin** [comment]
@cosn I expect there to be a latency, but the Go library is currently more than 6 months behind API tip.

**Comment by brandur** [comment]
@cos @kyleconroy I definitely see where you guys are coming from here, but it may be worth noting that quite a few API changes (I would say most actually) tweak the implicit behavior of API calls rather than the structure of the data being returned, and being able to set the API version would still be useful for testing this class of change. Some examples:

> The Charges endpoint previously returned only card charges. Charges now returns all charges, such as card charges and bank account charges.

> An error is now returned if a tax_percent is provided without a plan during customer update and creation.

> Add strict checks for postal codes on the account update and account creation endpoints. See https://stripe.com/docs/api#update_account-legal_entity-address-postal_code for more details.

@aodin I've submitted a pull in #169 to bring these bindings onto the most modern version of the API. Despite my comment above, it generally is better to keep the interface as minimal as possible. Was your main motivation in opening this issue to gain access to features in newer versions of the API? If so, can we close this for the time being if we get the upgrade in?

**Comment by aodin** [comment]
@brandur The main motivation was to test our billing infrastructure against the latest version of the API on our staging servers before committing it to production. I felt that setting the API version dynamically - on our side through a staging-only config - was the most elegant solution.

Having the Go library version up to date with the current API would solve our problem now, and solving https://github.com/stripe/stripe-go/issues/205 would fix it going forward. I'll close if you guys agree this is the solution.

**Comment by brandur** [comment]
> The main motivation was to test our billing infrastructure against the latest version of the API on our staging servers before committing it to production. I felt that setting the API version dynamically - on our side through a staging-only config - was the most elegant solution.

Cool! Just to make sure that I have this straight: you know that whatever API version that you have set on your account will be overridden when it comes to using these bindings right?

> Having the Go library version up to date with the current API would solve our problem now, and solving #205 would fix it going forward. I'll close if you guys agree this is the solution.

Alright! I'll open a discussion internally on what we could do to be more systematic about keeping these API versions more up-to-date. Thanks.

**Comment by brandur** [comment]
And one more note here, I accidentally linked to the wrong pull request above: #206 is the correct pull request that takes these bindings to the latest API version.

**Comment by aodin** [comment]
@brandur - yes the header value overrides the account setting, correct? https://stripe.com/docs/api#versioning

**Comment by brandur** [comment]
> @brandur - yes the header value overrides the account setting, correct? https://stripe.com/docs/api#versioning

Yep! You got it. From the Go bindings at least, the requested API version will be coupled to the bindings version that you have on your servers rather than any other external factors.

**Comment by brandur** [comment]
@aodin Just to close the loop on this: I just cut version 13.0.0 which is tied to the latest Stripe API version. Thanks for your patience here.
