### ISSUE TITLE
Customer.New() is broken

### ISSUE THREAD

**Issue by zboralski** [stripe/stripe-go#218]
This works :
```
customerParams := &stripe.CustomerParams{
		Desc: "blah",
}
resp, err := sc.Customers.New(customerParams)
	if err != nil {
		return err
	}
```
If I follow your "documentation" and do:

`customerParams.SetSource('tok_xxx)`

or 

`customerParams.SetSource('card_xxx)`

It always return an error `No such token: XXX`.

We read the source... We even tried to use the curl example. Same error... We're going to skip trying to create stripe customers... 

I am quite disappointed...

**Comment by leedhamtekani** [comment]
Finding clear documentation has been difficult for this, just a lot of other users with the same problem, and no clear solution.

**Comment by remistr** [comment]
@leedhamtekani @zboralski  This specific error here indicates that you are using the wrong key at some point when creating the token or the customer. You need to triple-check your code and make sure that you use the exact API keys you see in your account settings here: https://dashboard.stripe.com/account/apikeys

This applies to both the Secret API key in your Go code and the publishable key that you use to create the token client side.

**Comment by leedhamtekani** [comment]
@remistr @zboralski  thanks for your help this appears to have solved the problem, much appreciated.

**Comment by brandur** [comment]
@leedhamtekani Thanks for following up here!

@zboralski Like Remi said, this is almost certainly a problem where the token was created under one account and not available from another (as identified by two separate keys).

I'm going to close out this issue for the time being, but let us know if you have any other problems!
