### ISSUE TITLE
Add public accessible predefined errors

### ISSUE THREAD

**Issue by zemirco** [stripe/stripe-go#234]
If this package would use predefined errors and make them public it would be easier to handle them in our apps. 

Think about a customer who selects a plan but doesn't have any cards for her account. I'd like to redirect to the page where she can enter a new credit card. Currently I have to do string comparison and check the error message for "This customer has no attached payment source".

See this pattern in `io.EOF` or `io.ErrClosedPipe` and an up-to-date presentation from Dave Cheney http://dave.cheney.net/paste/gocon-spring-2016.pdf.

**Comment by zemirco** [comment]
I just saw that you're already doing this - https://github.com/stripe/stripe-go/blob/master/error.go#L15. Would it make sense to add more?

**Comment by brandur** [comment]
> I just saw that you're already doing this - https://github.com/stripe/stripe-go/blob/master/error.go#L15. Would it make sense to add more?

Absolutely! Unfortunately, we still don't have an automated way of getting new error IDs to propagate from our backend out to these bindings, but if you want to identify any particular error messages that you want to use, you can either issue a PR here and we'll take a look, or let us know and we can add them in.

**Comment by pjebs** [comment]
that approach in above link is not as idiotmatic as :
`
var (
InvalidRequest                    = errors.New("invalid_request_error")
IncorrectNum = errors.New("incorrect_number")
`

This is how the standard library does it.

**Comment by brandur** [comment]
> that approach in above link is not as idiotmatic as :

Yes, I agree. It's _even more_ idiomatic if you make sure to prefix those errors with `err` like `errInvalidRequest` or `errIncorrectNum`.

I probably won't get around to tackling that anytime soon, but I'll definitely review PRs from anyone that feels particularly strongly about introducing the alternative pattern :)

**Comment by brandur** [comment]
@zemirco @pjebs Hello, just a heads up that a version of this came in on #254, and we now have typed errors that can be compared against and which may include more detailed information (depending on error type).

I'm going to close this out for now, but let me know if you have anymore thoughts and/or ideas. Thanks!
