### ISSUE TITLE
Create credit card Charge

### ISSUE THREAD

**Issue by pjebs** [stripe/stripe-go#236]
I am attempting to make/submit a charge like this:
```

ch, err := sc.Charges.New(chargeParams)
	log.Printf("%+v", ch)
	log.Printf("\nerror: %+v", err)

	if err != nil {
		stripeErr := err.(*stripe.Error)

		switch stripeErr.Code {
		case stripe.IncorrectNum:
		case stripe.InvalidNum:
		case stripe.InvalidExpM:
		case stripe.InvalidExpY:
		case stripe.InvalidCvc:
		case stripe.ExpiredCard:
		case stripe.IncorrectCvc:
		case stripe.IncorrectZip:
		case stripe.CardDeclined:
		case stripe.Missing:
		case stripe.ProcessingErr:
		}

		return i.FAILURE_DUE_TO_SERVER, stripeErr.Msg
	} else {
		//No error but check if paid = true
		if ch.Paid == true {
			return i.SUCCESS, ""
		} else {
			//Something went wrong here
			//
		}
	}
```

**Comment by pjebs** [comment]
if `err` is not nil, is it safe to assume that ch.Paid **WILL ALWAYS BE TRUE**?

**Comment by remistr** [comment]
@pjebs: For coding questions or similar, you want to contact support instead here: https://support.stripe.com/email

Github issues should be kept for bugs and feature requests on our Go bindings, not for technical questions.

To answer your question though, this can be assumed for card charges but wouldn't be true for ACH charges for example.
