### ISSUE TITLE
Extend Transfer type with Reversed and AmountReversed 

### ISSUE THREAD

**Issue by layby42** [stripe/stripe-go#244]
Hello,

Is it possible to extend **Transfer** type with **Reversed** and **AmountReversed**  (those are listed in https://stripe.com/docs/api#retrieve_transfer)?

type Transfer struct {
        ....
	Reversed       bool              `json:"reversed"`
	AmountReversed int64             `json:"amount_reversed"`
}

see https://github.com/stripe/stripe-go/blob/master/transfer.go

Also is there a way to test full/partial reversals in test Stripe mode? Looks like transfers to bank accounts are immediately "paid" and I'm getting "Transfers to non-Stripe accounts can currently only be reversed while they are pending" on attempt to make reversal.

**Comment by brandur** [comment]
Hi @layby42, thanks for reporting!

I've added a patch in #246, and it should be available in master soon.

> Also is there a way to test full/partial reversals in test Stripe mode? Looks like transfers to bank accounts are immediately "paid" and I'm getting "Transfers to non-Stripe accounts can currently only be reversed while they are pending" on attempt to make reversal.

Hm, I don't know the answer to this one off hand. Any chance that @remistr or @olivierbellone has an easy answer? Otherwise, I'll dig around a little bit.
