### ISSUE TITLE
Missing CardID attribute on token params

### ISSUE THREAD

**Issue by dominicphillips** [stripe/stripe-go#259]
Hi!

I'm trying to create a token on my connected accounts as described [here](https://stripe.com/docs/connect/shared-customers) and [here](https://stripe.com/docs/connect/shared-customers). Currently its impossible to add the "card" parameter as a string, using one of the customers cards - or am I missing something ?

**Comment by remistr** [comment]
@dominicphillips It's definitely possible with the Go bindings. The code would look like this:
```
    t, err := token.New(&stripe.TokenParams{
        Card: &stripe.CardParams{
            Token: "card_XYZ",
        },
        Customer: "cus_1234",
        Params: stripe.Params{Account: "acct_TUV"},
    })
```

**Comment by brandur** [comment]
I'm closing this issue out for now, but let us know if you have anymore trouble @dominicphillips. Thanks!
