### ISSUE TITLE
Can't set account balance to zero.

### ISSUE THREAD

**Issue by ssoroka** [stripe/stripe-go#261]
Because there's no ZeroBalance parameter, and because zero checks are assumed to be unset, the following code makes it so that you cannot set a zero balance.
```
		if params.Balance != 0 {
			body.Add("account_balance", strconv.FormatInt(params.Balance, 10))
		}
```
I think we're going to keep seeing this issue come up again and again. Using the default initialization values to imply null makes it so that you can't set parameters to their default values. 

Possible solutions:
- define things like ZeroBalance all over the place.
- expose behavior like the underlying `body.Add("account_balance", ...)`
- adopt nullable values or use pointers to values so you can tell the difference between null and 0.

**Comment by guillaumehenriot** [comment]
Thank you for flagging this! I'm working on a fix.

**Comment by brandur** [comment]
> I think we're going to keep seeing this issue come up again and again. Using the default initialization values to imply null makes it so that you can't set parameters to their default values.

Yeah, this is certainly a little unfortunate :/ I'd suggest that we continue forging ahead using the current `*Zero` convention for the time being though; it wasn't a good design choice originally, but given that it's already here and in widespread use, it makes sense to with it for now.

The omissions like `BalanceZero` are part of a larger class of problem which is that without any kind of automated generation or testing, it's easy for discrepancies between the bindings and the API to start appearing. We'll be tackling that more broadly in the not-too-distant future, and hopefully we can get a more general fix for `*Zero` stuff in as well.

Thanks for reporting!
