### ISSUE TITLE
CustomerParams.TaxPercent does not exist even though it is available in the API

### ISSUE THREAD

**Issue by antipasta** [stripe/stripe-go#264]
Would like to be able to set TaxPercent when creating the initial customer, but this does not seem to be possible via the go lib.

https://stripe.com/docs/api#create_customer lists tax_percent as a param that can be passed to create_customer

**Comment by brandur** [comment]
Thanks for reporting @antipasta! I've added a fix for the problem in #265, and we should have something mainline pretty soon.

**Comment by brandur** [comment]
Fix released as 15.5.0.
