### ISSUE TITLE
Charge shipping address line1 should be optional but always sent as empty string

### ISSUE THREAD

**Issue by rdingwall** [stripe/stripe-go#267]
https://github.com/stripe/stripe-go/blob/master/charge.go#L122

Is there a reason there is no length check on `s.Address.Line1`?

According to the API docs, `line1` should be optional however `go-stripe` always appends an empty string and we see the following error in the Stripe dashboard:

```
shipping: {
    name: "Xyz"
    address: {
        line1: ""
        country: "GBR",
        postal_code: "xxx",
    },
    phone: "+44xxxx"
}

{
    error: {
        type: "invalid_request_error",
        message: "Must have at least one letter",
        param: "shipping[address][line1]"
    }
}
```

**Comment by brandur** [comment]
Hi @rdingwall,

Although including the shipping object is optional, I don't believe that line1 in the address object is. Can you point me to the specific part of the docs that suggested that it was?

**Comment by rdingwall** [comment]
Sorry - I misread the documentation. Thanks for explaining!

**Comment by brandur** [comment]
NP. Thanks for following up!
