### ISSUE TITLE
Can't re-open an invoice

### ISSUE THREAD

**Issue by teepark** [stripe/stripe-go#273]
`&stripe.InvoiceParams{Closed: false}` is [ignored](https://github.com/stripe/stripe-go/blob/master/invoice/client.go#L134), confused with the zero-value.

There's no good way to allow it given the current API -- if it recognized `false` then the lack of any explicitly set `Closed` value would also trigger re-opening.

Maybe something like this:

```go
// package stripe
type InvoiceClosedState int

const (
    Unset InvoiceClosedState = iota
    Closed
    Open
)

// package stripe
type InvoiceParams struct {
    // ...
    Closed InvoiceClosedState
    // ...
}
```

That would implicitly treat zero value of the `Closed` type as `Unset`.

**Comment by brandur** [comment]
@teepark Thanks for reporting! We're assembling a fix.
