### ISSUE TITLE
Stripe Connect

### ISSUE THREAD

**Issue by nicholaspark09** [stripe/stripe-go#274]
Having a bit of a hard time with allowing Stripe Connect Managed accounts to view their balances. 
Here's what I've been using, and I'm confused as to why I'm not getting anything usable:

                                        httpClient := urlfetch.Client(context)
					sc := client.New(accounts[0].SecretKey, stripe.NewBackends(httpClient))
					balance, err := sc.Balance.Get(nil)
					if err != nil{
						m["Error"] = err.Error()
					}else if balance != nil{
						if len(balance.Available)>0{
							currentBalance := float32(balance.Available[0].Value)/100
						}else if len(balance.Pending)>0{
							currentBalance := float32(balance.Pending[0].Value)/100
						}	
					}

**Comment by remistr** [comment]
Hey @nicholaspark09!

First off you don't need to use the managed account's secret key. With managed account, we released a new header, `Stripe-Account`, documented [here](https://stripe.com/docs/connect/authentication#authentication-via-the-stripe-account-header) that allows you to make any API request on behalf of a connected account using your platform's Secret API key and the connected account identifier `acct_XYZ`.

If you want to retrieve each of the pending and available balance(s) of a managed account, you can do this:

    fmt.Printf("Retrieve balance of a connected account!\n")

    // Your platform's secret API key
    stripe.Key = "sk_test_XXX"

    params := &stripe.BalanceParams{}
    // Set the identifier of the connected account
    params.Params.Account = "acct_XXYYZZ"

    bal, _ := balance.Get(params)
    fmt.Printf("Balance object: %x\n", bal)

    for index,element := range bal.Available {
        fmt.Printf("Available Balance '%d': currency '%s' - amount: '%d' \n", index, element.Currency, element.Value)
    }

    for index,element := range bal.Pending {
        fmt.Printf("Pending Balance '%d': currency '%s' - amount: '%d' \n", index, element.Currency, element.Value)
    }

**Comment by nicholaspark09** [comment]
Thanks for the help! I appreciate any help I can get.
