### ISSUE TITLE
Expandable entities can't be decoded by Stripe Connect

### ISSUE THREAD

**Issue by hraban** [stripe/stripe-go#277]
This is related to issue #164 

When you get events through Stripe Connect, you don't control the `expand` parameter. E.g. we get `charge` events with un-expanded `charge.customer` (i.e. it's a string, not an object). But because the `Charge` struct specifies the `Customer` as being a customer entity (i.e. expects it to be expanded), we can't ever get to that data. I basically have to decode twice.

What do you think of this solution?

```go
type Customer struct {
	ID string `json:"id"`
}

type Charge struct {
	Customer    *Customer
	CustomerID  string
	CustomerRaw json.RawMessage `json:"customer"`
}

func (c *Charge) UnmarshalJSON(b []byte) error {
	type nojson Charge
	wrapped := (*nojson)(c)
	err := json.Unmarshal(b, wrapped)
	if err != nil {
		return err
	}
	err = json.Unmarshal(c.CustomerRaw, &c.CustomerID)
	if err == nil {
		return nil
	}
	return json.Unmarshal(c.CustomerRaw, &c.Customer)
	// optional: also set c.CustomerID
}
```

Pros:
* backwards compatible

Cons:
* introduces three elements just for Customer, one of which internal
* can't differentiate between customer id `""` and `null`.

An alternative would use a special purpose union-like struct with custom unmarshaller: looks better and supports `null`, but not backwards compatible :/

thoughts? did I miss something?

Google play example: https://play.golang.org/p/dnenaszQn4

**Comment by hraban** [comment]
Well, it looks like this already exists! I must have missed this somehow:

```go
// UnmarshalJSON handles deserialization of a Charge.
// This custom unmarshaling is needed because the resulting
// property may be an id or the full struct if it was expanded.
func (c *Charge) UnmarshalJSON(data []byte) error {
	type charge Charge
	var cc charge
	err := json.Unmarshal(data, &cc)
	if err == nil {
		*c = Charge(cc)
	} else {
		// the id is surrounded by "\" characters, so strip them
		c.ID = string(data[1 : len(data)-1])
	}

	return nil
}
```

:)

**Comment by brandur** [comment]
Oops, sorry about the late reply here! Glad that you got it figured out :)
