### ISSUE TITLE
Stripe Connect - Foreign Countries and Currencies

### ISSUE THREAD

**Issue by nicholaspark09** [stripe/stripe-go#280]
When creating a managed account for Stripe Connect, I'm confused as to how it would work for individuals in foreign countries. The following is what I have so far in the parameters:

                                             params := &stripe.AccountParams{
							Managed: true,
							BusinessName: body["name"],
							SupportEmail: body["email"],
							SupportPhone: body["phone"],
							Country: body["country"],
							DefaultCurrency: body["currency"],
						}
My question is, let's say I have an individual who wants to create a managed account in Korea and accept Korean Won (krw). Would I set the default currency to "krw" or "usd?" How would I enable their users to pay in Korean Won and send the money to the managed account's bank in America?

**Comment by remistr** [comment]
@nicholaspark09: This is more a question specific to Managed accounts and how they work than specific to the Go bindings. We try to keep issues here limited to bugs in the bindings or feature request so I'm going to close it out.

The best solution would be for you to reach out to our support team directly instead here: https://support.stripe.com/email

While I'm here I can provide some information though. First off, you can't create a managed account for a Korean user. We don't support Korea yet and you can see the list of countries we support on our global page here: https://stripe.com/global or on the list of fields we require for verification here: https://stripe.com/docs/connect/required-verification-information#US

Depending on the country an account is in, you can charge customers in some currencies or others. There's a detailed support article covering this here: https://support.stripe.com/questions/which-currencies-does-stripe-support

For any follow ups please talk to the support team!
