### ISSUE TITLE
Migrate existing recipient

### ISSUE THREAD

**Issue by layby42** [stripe/stripe-go#281]
Hi Everybody,

Is there /will be a way to migrate existing recipient to managed account? I was hoping to find FromRecipient param in AccpountParams and use Account.New(...).

https://stripe.com/docs/connect/migrating#migrating-existing-recipients:
To migrate a recipient to an account, make a POST request to /v1/accounts, passing the existing recipient ID: 

curl https://api.stripe.com/v1/accounts \
   -u {PLATFORM_SECRET_KEY}: \
   -d from_recipient={RECIPIENT_ID}

**Comment by layby42** [comment]
Maybe add a method Migrate or NewFromRecipient or whatever to account/client.go, something like:

func (c Client) Migrate(stripeRecipientId string) (*stripe.Account, error) {
	body := &stripe.RequestValues{}
	body.Add("from_recipient", stripeRecipientId)

	acct := &stripe.Account{}
	err := c.B.Call("POST", "/accounts", c.Key, body, nil, acct)

	return acct, err
}

**Comment by guillaumehenriot** [comment]
@layby42 Thanks for flagging this! We are working on a fix.

**Comment by layby42** [comment]
Thank you. Also please extend Recipient with ""migrated_to" attribute (https://stripe.com/docs/api/go#retrieve_recipient). There should be a way to know if recipient already migrated and if so which account to use. I'm getting error  {"type":"invalid_request_error","message":"This recipient is already migrated to an account (acct_18bYajGClcH0py21). You may only migrate a recipient once.","param":"from_recipient","request_id":"req_8tmKgpbYsM4WQu","status":400}
