### ISSUE TITLE
SubParams missing at_period_end

### ISSUE THREAD

**Issue by tj** [stripe/stripe-go#284]
little tricky to tell since the Go struct fields don't line up with the docs in all cases but it looks like this is missing

**Comment by remistr** [comment]
Hey @tj, the parameter is called `EndCancel` and you can see it [here](https://github.com/stripe/stripe-go/blob/master/sub.go#L21) and used [here](https://github.com/stripe/stripe-go/blob/d1e3ca8655917920c707b9e5816f04c7a897f780/sub/client.go#L197)

**Comment by tj** [comment]
perfect thanks!
