### ISSUE TITLE
Meta data on CardParams is not included when creating charges

### ISSUE THREAD

**Issue by telecoda** [stripe/stripe-go#287]
We have noticed when we create a charge with metadata in the Source, CardParams, it is not sent to the Stripe API.

	charge, err := charge.New(&stripe.ChargeParams{
		Amount:   uint64(1234),
		Currency: stripe.Currency("GBP"),
		Source: &stripe.SourceParams{
			Card: &stripe.CardParams{
				Name:   "testing metadata",
				Number: "4242424242424242",
				Month:  "12",
				Year:   "35",
				Params: stripe.Params{
					Meta: map[string]string{
						"paymentMethodId": "test-method-id",
					},
				},
			},
		},
		Desc: "test desc",
		Params: stripe.Params{
			Meta: map[string]string{
				"customerId": "test-cust-id",
				"orderId":    "test-order-id",
			},
		},
	})

The paymentMethodId will not appear in the meta part of the request.

**Comment by telecoda** [comment]
I have done some further testing with the following results:

Request:

    {
      "amount": "1234",
      "currency": "GBP",
      "card": {
        "object": "card",
        "number": "4242424242424242",
        "exp_month": "12",
        "exp_year": "35",
        "name": "testing metadata",
        "metadata": {
          "paymentMethodId": "test-method-id"
        }
      },
      "description": "test desc",
      "capture": "true",
      "metadata": {
        "orderId": "test-order-id",
        "customerId": "test-cust-id"
      }
    }

Response:

    {
      "id": "ch_xxx",
      "object": "charge",
      "amount": 1234,
      "amount_refunded": 0,
      "application_fee": null,
      "balance_transaction": "txn_xxx",
      "captured": true,
      "created": 1470833205,
      "currency": "gbp",
      "customer": null,
      "description": "test desc",
      "destination": null,
      "dispute": null,
      "failure_code": null,
      "failure_message": null,
      "fraud_details": {},
      "invoice": null,
      "livemode": false,
      "metadata": {
        "orderId": "test-order-id",
        "customerId": "test-cust-id"
      },
      "order": null,
      "paid": true,
      "receipt_email": null,
      "receipt_number": null,
      "refunded": false,
      "refunds": {
        "object": "list",
        "data": [],
        "has_more": false,
        "total_count": 0,
        "url": "/v1/charges/ch_xxx/refunds"
      },
      "shipping": null,
      "source": {
        "id": "card_xxx",
        "object": "card",
        "address_city": null,
        "address_country": null,
        "address_line1": null,
        "address_line1_check": null,
        "address_line2": null,
        "address_state": null,
        "address_zip": null,
        "address_zip_check": null,
        "brand": "Visa",
        "country": "US",
        "customer": null,
        "cvc_check": null,
        "dynamic_last4": null,
        "exp_month": 12,
        "exp_year": 2035,
        "fingerprint": "xxx",
        "funding": "credit",
        "last4": "4242",
        "metadata": {},
        "name": "testing metadata",
        "tokenization_method": null
      },
      "source_transfer": null,
      "statement_descriptor": null,
      "status": "succeeded"
    }


As you can see the "paymentMethodId" metadata sent in the Source.Card.Metadata is not returned in the response.

Is this a bug, or should I not be sending metadata in this part of the request body?

**Comment by brandur** [comment]
Hi @telecoda,

My apologies for the delayed response here.

I think the canonical reference for this is the [create charge documentation](https://stripe.com/docs/api#create_charge), and indeed it doesn't seem like metadata is a field that gets taken as part of the source input hash.

Sorry about the trouble here. I'm going to close this and the associated pull request, but let us know if you have any other questions/comments/concerns here.
