### ISSUE TITLE
Iterator conventions

### ISSUE THREAD

**Issue by kr** [stripe/stripe-go#29]
Congrats on releasing this package! It looks comprehensive and clean. I have one initial suggestion, if you're interested:

I find the naming convention and behavior for iterators in this package a little confusing. In particular, does the Next method produce a new value every time it is called, or does it simply access a single stored item between calls to Stop? For example, does the following code print one value twice, or two different values?

``` go
i := plan.List(params)
for !i.Stop() {
    log.Println(i.Next())
    log.Println(i.Next())
}
```

It is not clear. (Even after reading [the documentation](http://godoc.org/github.com/stripe/stripe-go/plan#Iter.Next) it remains unclear, since the comment there says essentially nothing beyond repeating the name of the method.)

In contrast, two standard library types ([bufio.Scanner](http://godoc.org/bufio#Scanner) and [sql.Rows](http://godoc.org/database/sql#Rows)) have adopted a slightly different convention: the driver method that goes in the for loop condition is called `Next` or `Step` rather than `Stop`, and, importantly, the iterator provides accessor methods for the _current_ item in the sequence.

Using the standard library convention, the documented [example for plan.List](http://godoc.org/github.com/stripe/stripe-go#example-Plan--List) would look like this:

``` go
stripe.Key = "sk_key"

params := &stripe.PlanListParams{}
params.Filters.AddFilter("limit", "", "3")
params.Single = true

i := plan.List(params)
for i.Next() {
    plan, err := i.Plan()
    if err != nil {
        log.Fatal(err)
    }

    log.Printf("%v ", plan.Name)
}
```

and my example above would look like either this:

``` go
i := plan.List(params)
for i.Next() {
    log.Println(i.Plan())
    log.Println(i.Plan())
}
```

or this, depending on the meaning of the API as it currently stands:

``` go
i := plan.List(params)
for i.Next() {
    log.Println(i.Plan())
    i.Next()
    log.Println(i.Plan())
}
```

Either way, it is self-evident.

I suggest that Stripe should consider adopting the standard library's convention, both for the sake of consistency and because it is (IMO) inherently less confusing.

You could go further, and put the error in a separate accessor method (as done by Scanner) but that's a separate issue.

**Comment by jarrodhroberson** [comment]
Are there any idomatic examples on how to use the "StartAfter" and get ALL of something instead of just a max of 100?

**Comment by remi-stripe** [comment]
@jarrodhroberson This is an almost 10 years old Github issue and not the best place to ask an integration support question. I'd recommend contacting our support team for 1:1 help at https://support.stripe.com/contact or talking to developers on our Discord server: https://stripe.com/go/developer-chat
