### ISSUE TITLE
Account's LegalEntity: missing address_kana and address_kanji

### ISSUE THREAD

**Issue by layby42** [stripe/stripe-go#301]
Hi Everybody,

This is not something very urgent. 

Update account has address_kana and address_kanji (https://stripe.com/docs/api#update_account) but LegalEntity (https://github.com/stripe/stripe-go/blob/master/account.go) does not have those.

Also: business_name_kana, business_name_kanji, first_name_kana, first_name_kanji, last_name_kana, last_name_kanji, personal_address_kana, personal_address_kanji, phone_number, gender

UPDATE: maiden_name

**Comment by guillaumehenriot** [comment]
Thank you @layby42 for flagging this. We work on a patch to fix it.

**Comment by brandur** [comment]
Thanks @layby42! Added a patch in #303.
