### ISSUE TITLE
Account verification section does not have status attribute

### ISSUE THREAD

**Issue by layby42** [stripe/stripe-go#302]
Hi Everybody,

Once managed account verified by Stripe attempt to change Legal Entity results in error like

You cannot change `legal_entity[first_name]` via API if an account is verified. Please contact support@stripe.com if you need to change the legal entity information associated with this account.

Stripe account object (https://stripe.com/docs/api/go#account_object) does have verification status

    "verification": {
      "details": null,
      "details_code": "failed_other",
      "document": null,
      "status": "unverified"
    }

But there is no description of possible values (https://stripe.com/docs/api) or I cannot find description and status not provided by https://github.com/stripe/stripe-go/blob/master/account.go

Is it possible to extend account with verification status, so we know when it is OK to update Legal Entity with Stripe and when we should redirect our users to support@stripe.com

UPDATE: Stripe dev support suggested to use legal_entity[verification][status], which has possible values "pending", "verified", "unverified"

**Comment by remistr** [comment]
@layby42 This would definitely be a good idea but it's not yet supported in our API so it's not really specific to the Go bindings.

The idea is that if your managed account is verified, you shouldn't try to change anything under the `LegalEntity` and we would error out. There are some edge-cases where even though the account is not verified yet, some fields are blocked. An example is that a Company could have their `business_tax_id` verified and you can't change it even though the account itself is not fully verified just yet.

We're aware that this is a shortcoming of the API and it's something we hope to fix in the future but we don't have a clear timeline for this right now unfortunately.

**Comment by layby42** [comment]
@remistr Thanks for quick answer. The problem is that we are forced by Stripe to migrate our clients from recipients (new recipients not allowed) to managed accounts and it is difficult to implement proper support for managed accounts.

BTW: it is expected to have possibility to provide verification information (including documents upload) for managed accouts via Stripe Dashboard? So we can implement minimum to creating managed account and the rest our clients can provide directly to Stripe via Stripe Dashboard?

**Comment by remistr** [comment]
@layby42: We currently haven't planned any work around the dashboard for this right now unfortunately. This should happen via the API and there are 2 different approaches:
1. Collect as little as possible, listen for `account.updated` events and check what new information we ask for in `fields_needed`.
2. Collect as much as possible upfront to increase the volume of accounts verified from the start and decrease the need to ask users for more information.

This is a bit out of scope for github issues here unfortunately and I'd recommend talking to our support team directly here: https://support.stripe.com/email. They should be able to both help guide you in the implementation and look into specific cases where the account hasn't been verified when you'd expect it to be.

**Comment by layby42** [comment]
UPDATE: Stripe dev support suggested to use legal_entity[verification][status], which has possible values "pending", "verified", "unverified"

**Comment by remistr** [comment]
Hey @layby42 that's correct! I think I really misunderstood your original question here as being about that specific error and not about how to check the status of the verification, sorry about that.

**Comment by brandur** [comment]
Glad you found an answer here! I'm going to close out this issue, but let us know if you have any more questions about this.
