### ISSUE TITLE
Rate limits?

### ISSUE THREAD

**Issue by tejasmanohar** [stripe/stripe-go#306]
How would we implement rate limiting given the iterator interface? After talking to support, they suggested ~100 rps. I guess this should be another "future" issue? @brandur

**Comment by brandur** [comment]
I'm be tempted to merge this into #300: you'd probably use a similar sort of retry policy (with a backoff).

Are these issues hypothetical or are they problems that you're running into? Due to the practical response time of a Stripe list call, you're pretty unlikely to ever run into rate limiting unless you're performing hundreds of parallel requests. If that's the case, I'd recommend a worker pool that allows the maximum number of parallel calls to be restricted to ensure that you're not abusing the API.

**Comment by tejasmanohar** [comment]
We're porting some services to Go and have seen these errors before, but we are an [ETL service](https://segment.com/sources/stripe) that does perform many requests in parallel... in addition to an unbounded amount that a customer may be performing independently. For many of our integrations, we allow customers to pick our rps cap.

I think a token bucket algorithm should be implemented independently of retries, as they're both useful for different things. Maybe instead of including it all in the library, some sort of interceptor / middleware model would be preferred (thinking...)

**Comment by brandur** [comment]
> We're porting some services to Go and have seen these errors before in the existing system, but we are an ETL service that does perform many requests in parallel... in addition to an unbounded amount that a customer may be performing independently. For many of our integrations, we allow customers to pick our rps cap.

Ah, cool. Do you have a rough idea of the ranges of RPS caps that most customers are operating inside? I'm still a little surprised that you'd be hitting rate limits because the limits tend to be _very_ generous. It's possible that you may want to consider lowering the upper bound of that RPS cap.

> I think a token bucket algorithm should be implemented independently of retries, as they're both useful for different things. Maybe instead of including it all in the library, some sort of interceptor / middleware model would be preferred (thinking...)

Oh, hm, we implement rate limiting on the server side using token bucket, but can you clarify as to where this might be useful here?

We should probably be a little careful about creating an abstraction that's too elaborate to start off, but "client middleware" designs as seen in the likes of Excon are quite a good idea. We may just want to bundle it all internally in the beginning though.

**Comment by tejasmanohar** [comment]
@brandur 

>Ah, cool. Do you have a rough idea of the ranges of RPS caps that most customers are operating inside? I'm still a little surprised that you'd be hitting rate limits because the limits tend to be very generous. It's possible that you may want to consider lowering the upper bound of that RPS cap.

Not atm. We don't have a rate limit set in our existing solution, but it's something that's been requested a handful of times and an error that we've seen a couple times with a handful of those customers haha. Definitely not common.... but something to consider.

>Oh, hm, we implement rate limiting on the server side using token bucket, but can you clarify as to where this might be useful here?

I meant something like [this](https://github.com/tejasmanohar/token-bucket-promise), but for Go, we could probably get away with just `time.Ticker` (even though it doesn't support bursts out of the box).

>We may just want to bundle it all internally in the beginning though.

Fine by me. Retries are definitely more important than rate limiting, as we've seen ephemeral errors from the API more than a handful of times. Knocking out some other things today, but I'll try to shoot over a PR for #300 soon if it's unlikely to be taken care of by Stripe internally soon.

**Comment by brandur** [comment]
> I meant something like this, but for Go, we could probably get away with just time.Ticker (even though it doesn't support bursts out of the box).

Oh right, but I mean why do we need a token bucket (or anything like it) in the client? Are you thinking of using it to space out retries or something?

> Fine by me. Retries are definitely more important than rate limiting, as we've seen ephemeral errors from the API more than a handful of times. Knocking out some other things today, but I'll try to try to send over a PR for #300 if it's unlikely to be taken care of by Stripe internally soon :)

Cool! I'll have a little more time next week, but probably won't get around to it in the next few days. If you want to give it a shot, that would be great.

**Comment by tejasmanohar** [comment]
>Oh right, but I mean why do we need a token bucket (or anything like it) in the client? Are you thinking of using it to space out retries or something?

@brandur Nope, to space out all requests so that rate-limit errors are avoided.

**Comment by brandur** [comment]
> @brandur Nope, to space out all requests so that rate-limit errors are avoided.

Oh, I see. Well, I think we'd leave that as an exercise to the calling app to implement however they want, but an alternative (and possibly simpler) solution might be something like a worker pool which could guarantee that no more than 50 requests can ever be executing in parallel. A token bucket should also do the trick though.

**Comment by tejasmanohar** [comment]
@brandur Hm, confused how the app could implement rate-limiting of requests if the iterator doesn't expose when it's actually making a request. I know the app can *respond* to rate-limit errors and act appropriately, but that's not always ideal.

**Comment by brandur** [comment]
> @brandur Hm, confused how the app could implement rate-limiting of requests if the iterator doesn't expose when it's actually making a request. I know the app can respond to rate-limit errors and act appropriately, but that's not always ideal.

Well, in practice, the iterator is always iterating sequentially, and round trips are likely to take 1+ seconds, which is beyond the threshold of the server side rate limiting that we're doing. So in other words, you'll almost certainly never be rate limited from iterating a single list.

With that assumption, it's just a matter of restricting the maximum number of lists that you're iterating in parallel to a reasonable level (well actually, all the requests that you're making). Retries can also be implemented to ensure that even if you get a statistically unlikely density of requests within a single second, you'd have a safety net.

Possibly a token bucket would allow you to totally saturate each second with the maximum number of requests that you can get away with, but I'm not sure that's a goal that I want to aim for.

**Comment by tejasmanohar** [comment]
this is what i ended up with https://gist.github.com/tejasmanohar/185c5b8150cd7f94e04a6b605d5a5093
