### ISSUE TITLE
Get bank accounts by Customer ID?

### ISSUE THREAD

**Issue by tejasmanohar** [stripe/stripe-go#312]
https://stripe.com/docs/api/go#customer_list_bank_accounts

`card.List(&stripe.BankAccountListParams{Customer: {CUSTOMER_ID}})`

The example here seems funky. I've come up with

`bankaccount.List(&stripe.BankAccountListParams{AccountID: customerID})`

Why is it  called `AccountID` when the param in the docs is called `customer`? is this really expecting a `customer` or `account` ID?

**Comment by brandur** [comment]
Ah yes, something is definitely not quite right here. We have by-customer deletion supported, but none of the other operations worked. Added a fix in #314.
