### ISSUE TITLE
account.external_account.created not working as expected

### ISSUE THREAD

**Issue by tejasmanohar** [stripe/stripe-go#315]
```go
package main

import (
	"fmt"

	"github.com/stripe/stripe-go"
	"github.com/stripe/stripe-go/event"
)

func main() {
	stripe.Key = "..."

	params := &stripe.EventListParams{}
	params.Filters.AddFilter("type", "", "account.external_account.created")
	i := event.List(params)

	for i.Next() {
		fmt.Printf("%+v\n", i.Event().Created)
	}

	if err := i.Err(); err != nil {
		panic(err)
	}
}
```

We've created lots of cards, but I don't see any here. Is that expected?

**Comment by remistr** [comment]
@tejasmanohar based on your code, you're filtering events in *your* platform account so it's expected. Those events would live on each of the connected accounts so to see those you'd need to list events on each of your connected accounts.

**Comment by tejasmanohar** [comment]
@remistr I see... so I'm misinterpreting this event, and "account.external_account" does not refer to "bank" or "card" of customers but instead connected accounts?

**Comment by remistr** [comment]
@tejasmanohar That's correct. `external_account` is what represents a payout method on a managed account. When you add a bank account or a card to a customer, it's called a `source` and you'd get a `source.created` event instead.

**Comment by tejasmanohar** [comment]
Ah. I see. Makes sense. `customer.source.created`
