### ISSUE TITLE
Array query parameter

### ISSUE THREAD

**Issue by tejasmanohar** [stripe/stripe-go#319]
https://stripe.com/docs/api/go#list_events

How would I specify the `types` (array) parameter via the Golang library? I tried
```
params.Filters.AddFilter("types", "", strings.Join(input.Events, ","))
```
and 
```
params.Filters.AddFilter("types", "", "["+strings.Join(input.Events, ",")+"]")
```
(last one was a shot in the dark)

Frankly, I'm not quite sure how Stripe's HTTP API expects this formatted in the first place.

**Comment by brandur** [comment]
@tejasmanohar Try just invoking the method multiple times:

``` go
params.Filters.AddFilter("types", "", " account.updated")
params.Filters.AddFilter("types", "", " account.external_account.updated")
```

This just gets encoded to typical form-encoded parameters like `?types[]=...&types[]=...`.

**Comment by tejasmanohar** [comment]
Ah. "types[]" seems to work too Thanks!
