### ISSUE TITLE
Tx doesn't handle created gte & lte filters simultaneously

### ISSUE THREAD

**Issue by tejasmanohar** [stripe/stripe-go#331]
```go
params := &stripe.TxListParams{}
params.Filters.AddFilter("limit", "", "100")
params.Filters.AddFilter("created", "gte", "1476208800")
// params.Filters.AddFilter("created", "lte", "1475712000")

i := s.stripeClient.Balance.List(params)

for i.Next() {
  v := i.Transaction()
  fmt.Println(v.Created)
  os.Exit(0)
}
```

This prints `1476257723` and then exits. When I uncomment the `lte` filter, `i.Next()` returns `false` and `i.Err()` is `nil`. Using `lte` or `gte` alone returns results, but I want both. This is reproducible so let me know if you're having trouble.

I have two filters being passed to the Events API, and that seems to work out OK so I wonder if this truly is a library problem or if there's something different for this resource.

**Comment by dpetrovics** [comment]
Hi @tejasmanohar, thanks for the question. Is it possible that you have your `gte` and `lte` times reversed? Or are you trying to exclude an interval from your results? I think internally the API `AND`s them, so the way you have it setup it will always return no results when both your filters are applied. If you do want to exclude an interval,  I would suggest making two separate list API requests. Hope that helps!

**Comment by tejasmanohar** [comment]
>  Is it possible that you have your gte and lte times reversed? 

1475712000 > 1476208800 so I don't think so.

>If you do want to exclude an interval, I would suggest making two separate list API requests. Hope that helps!

I want to get all data b/w two times. Could you expand here?

**Comment by brandur** [comment]
Are you sure that you have your parameters in the right order here? If we translated your code about to pseudocode, I think we'd have something like this:

```
if created >= 1476208800 &&
   created <= 1475712000
```

As you pointed out, 1475712000 > 1476208800, so it seems like the empty result here is correct.

**Comment by tejasmanohar** [comment]
oh hm my bad. i'll double check and re-open if this is still an issue. i was sharing the params on some other requests and those did return results but this didn't, maybe something was swapped. thanks
