### ISSUE TITLE
Should Order DeliveryEstimate have dates?

### ISSUE THREAD

**Issue by tejasmanohar** [stripe/stripe-go#333]
https://github.com/stripe/stripe-go/blob/master/order.go#L71-L74

Should these be int64 (dates)? I don't see much info on these values in docs.

**Comment by brandur** [comment]
> If type is "exact", date will be the expected delivery date in the format YYYY-MM-DD 

I think that they were made strings because of the very specific format and because the API only guarantees granularity to the coarseness of a day. They still might make sense as timestamps anyway though ...

**Comment by tejasmanohar** [comment]
ah, I see. I guess strings make sense here. don't want to indicate an hour (or second) if you don't know it for sure
