### ISSUE TITLE
Subscription tax_percent only supports 2 decimal floats.

### ISSUE THREAD

**Issue by fd** [stripe/stripe-go#350]
I need to to set the `tax_percent` value of my subscriptions to a 3 decimal number (eg `8.875`) currently this gets rounded to 2 decimals.

See: 
- https://github.com/stripe/stripe-go/blob/master/sub/client.go#L79
- https://github.com/stripe/stripe-go/blob/master/sub/client.go#L203

**Comment by brandur-stripe** [comment]
Yes, good find!

@kyleconroy Would you mind commenting as to the state of this one?

**Comment by brandur-stripe** [comment]
NM actually. Asked Kyle and this has been GA for a while. It's now just a Go bug that it's not supported.

**Comment by remi-stripe** [comment]
@brandur-stripe The change has been live for a few weeks and you can confirm in the docs [here](https://stripe.com/docs/api#create_subscription-tax_percent). We "just" need to update the Go bindings.
