### ISSUE TITLE
SubProrationDateNow never gets checked in invoices.GetNext()

### ISSUE THREAD

**Issue by hilljgo** [stripe/stripe-go#352]
stripe-go version: 18.13.0
golang version: 1.7.3

InvoiceParams is [defined](https://github.com/stripe/stripe-go/blob/master/invoice.go#L11) with a field called SubProrationDateNow, which is a bool. I intended on using this with the [invoices.GetNext()](https://github.com/stripe/stripe-go/blob/76efd227ee7e12e332412a515485e96894824efc/invoice/client.go#L169) method, but noticed that it doesn't ever get checked. I would expect that it would check if it was true, then set SubProrationDate to the current time. Was this deprecated at some time?

I know that I can just get the current time manually and set SubProrationDate to that, but I thought it was odd that SubProrationDateNow is left unchecked.

**Comment by brandur** [comment]
Hi @hilljgo, nice find! Sorry about the trouble here, I think this is a bug that I accidentally introduced.

It looks like a I might have thought that the `subscription_proration_date` might have been able to take the special value of "now" like the `trial_end` parameter when you're creating a new subscription. [Checking the docs though](https://stripe.com/docs/api/go#upcoming_invoice-subscription_proration_date), that doesn't seem to be the case.

Unfortunately I think that the right answer here is to just pull out the unused parameter, which I've done in #353. Is it okay if you just set the current time manually?
