### ISSUE TITLE
Impossible to remove coupon from subscription via API

### ISSUE THREAD

**Issue by layby42** [stripe/stripe-go#370]
Hi,
 
Looks like it is impossible to remove coupon from subscription via api.

According to the doc for subscription https://stripe.com/docs/api/go#update_subscription it should be possible: "This can be unset by updating the value to null and then saving."

Currently the code (https://github.com/stripe/stripe-go/blob/master/sub/client.go) does: 	

`
if len(params.Coupon) > 0 {
	body.Add("coupon", params.Coupon)
}
`

Maybe it is possible to extend `SubParams` with `CouponRemove` (or something like this) and handle it similar to `TaxPercentZero` in `func Update(id string, params *stripe.SubParams) (*stripe.Sub, error)`:

`
if len(params.Coupon) > 0 {
     body.Add("coupon", params.Coupon)
} else if params.CouponRemove {
     body.Add("coupon", "")
}
`
?

**Comment by remi-stripe** [comment]
@layby42 This is a pretty recent change and we didn't push the change to the Go bindings yet. We'll be shipping it in the future but if you're up for a pull request that would be awesome!

**Comment by layby42** [comment]
Hi Everybody,

Looks like it is possible to remove coupon from subscription other way around, from discount: https://stripe.com/docs/api/go#delete_subscription_discount. 

I will try to use it.

**Comment by remi-stripe** [comment]
@layby42  yes that's the way that we had until a few weeks ago. We recently added the ability to set `coupon: null` when updating a subscription via the API too but this isn't part of the Go bindings yet.

**Comment by layby42** [comment]
@remi-stripe, OK, I will submit  pull request

**Comment by brandur-stripe** [comment]
Closing this out as it was fixed in #372.
