### ISSUE TITLE
customer.Get() does not unmarshal default source

### ISSUE THREAD

**Issue by discordianfish** [stripe/stripe-go#398]
Hi,

maybe I'm missing something but it looks like customer.Get() doesn't unmarshal the DefaultSource properly.

This snippet:

```
        stripe.Key = "sk_test_..."
        c, err := customer.Get("cus_...", nil)
        log.Println(c.DefaultSource, err)
```

Prints:

```
2017/05/05 15:56:28 Requesting GET api.stripe.com/v1/customers/cus_xxx
2017/05/05 15:56:29 &{ card_XXX <nil> <nil> <nil> <nil> false} <nil>
```

Since the API call includes the other fields too, I'd expect stripe-go unmarshal them too.
The docs also mention custom unmarshalling here: https://godoc.org/github.com/stripe/stripe-go#PaymentSource.MarshalJSON

But it looks like Backend just unmarshals the json object and not takes care of such custom unmarshalling: https://github.com/stripe/stripe-go/blob/master/stripe.go#L318

**Comment by fred-stripe** [comment]
Hi there,

This is expected. If you look at the retrieve customer API response, you can see that only the ID of the default source is returned, not a source structure:

https://stripe.com/docs/api/curl#retrieve_customer
https://stripe.com/docs/api/curl#customer_object-default_source

The intention is that you use the default source ID to find the full default source structure in the array of sources:
https://stripe.com/docs/api/curl#customer_object-default_source
https://stripe.com/docs/api/curl#customer_object-sources

However, the "default_source" property is expandable, and this should work in Go:

```go
params := &stripe.CustomerParams{}
params.Expand("default_source")
charge.Get("cus_1234xxx999", params)
log.Println(c.DefaultSource, err)
```

More on expandable properties here:
https://stripe.com/docs/api/go#expanding_objects

**Comment by discordianfish** [comment]
Ah, perfect! Missed that, thanks a lot and sorry for the noise. In general using the lib is a breeze, love it! :)
