### ISSUE TITLE
Feature Request - Log to a file with custom header.

### ISSUE THREAD

**Issue by nextdimension** [stripe/stripe-go#399]
Feature request

- Specify a file to log.

- Allow a custom header.

- Optional.

**Comment by brandur-stripe** [comment]
Hi there,

> Specify a file to log.

Good news on this one. stripe-go sets a default logger, but you can reset it yourself with something like `stripe.Logger = log.New(os.Stderr, "", log.LstdFlags)`.

> Allow a custom header.

I'd be curious to know why you'd need to do this, but it's also possible to set your own `http.Client` using `stripe.SetHTTPClient()`. Once you have that you can set `Transport` with your own `RoundTripper` implementation where you can set a header.

> Optional.

I'm not sure what this one means!

I'm closing this for now, but let me know if you have anymore questions.
