### ISSUE TITLE
Add query method on RequestValues 

### ISSUE THREAD

**Issue by edenman** [stripe/stripe-go#401]
I'm writing a `Backend` object so i can fake the responses from Stripe in a test.  It's a little annoying that the only accessor method for `RequestValues` is `Encode`...would you be amenable to me adding a `Get(key string) []string` method?

**Comment by edenman** [comment]
(the workaround i'm using for now is just doing `url.ParseQuery(form.Encode())`, maybe that's just the recommended way to do this?)

**Comment by brandur-stripe** [comment]
Yeah, given that it's pretty symmetrical with `Set` which is already in there, I'd be fine with having it around.

Lets make sure to copy the comment off `Set` to help make it clear that `Get` is mostly intended for debugging purposes and will take linear time to do a lookup. If the need arises we can reimplement the internals with a more performant mechanic.
