### ISSUE TITLE
Bug in BankAccount client.go

### ISSUE THREAD

**Issue by UMaineACG** [stripe/stripe-go#426]
Hi,
There is a bug on line 100 in bankaccount/client.go. The GET request should take params.Customer but is being passed params.AccountID

`if len(params.Customer) > 0 {
		err = c.B.Call("GET", fmt.Sprintf("/customers/%v/bank_accounts/%v", params.AccountID, id), c.Key, body, commonParams, ba)
	} else if len(params.AccountID) > 0 {
		err = c.B.Call("GET", fmt.Sprintf("/accounts/%v/bank_accounts/%v", params.AccountID, id), c.Key, body, commonParams, ba)
	} else {
		err = errors.New("Invalid bank account params: either Customer or AccountID need to be set")
	}`

I have tested this locally and replacing params.Customer fixes the issue.

**Comment by brandur-stripe** [comment]
Yes, absolutely right! Thanks for the bug report. Fixed in #428.

**Comment by brandur-stripe** [comment]
Released as 23.2.1.
