### ISSUE TITLE
Integrate standard http library to webhook signatures verification

### ISSUE THREAD

**Issue by sanae10001** [stripe/stripe-go#436]
Can anyone integrate standard http library to webhook signatures verification?
Like this:
``` go
func ConstructEventFromRequest(req *http.Request, secret string) (stripe.Event, error) {
	buf := make([]byte, req.ContentLength)
	_, err := io.ReadFull(req.Body, buf)
	if err != nil {
		return stripe.Event{}, err
	}
	sig := req.Header.Get("Stripe-Signature")
	return ConstructEvent(buf, sig, secret, DefaultTolerance)
}
```
This is very simple but useful.
I can do it If I have some free time on this week.

**Comment by brandur-stripe** [comment]
Hi @sanae10001, do you mean just like an example? [There's one you can take a look at here](https://github.com/stripe/stripe-go/blob/master/webhook/client_handler_test.go).

**Comment by sanae10001** [comment]
@brandur-stripe 
Yes, I recommend integrating it into signatures verification function.
The user don't need to know how to extract the signature and the object `Event` from the `Request`.
I think it is easier to use and localized on `Go`.

Of course, this is just a suggestion😊.

**Comment by brandur-stripe** [comment]
@sanae10001 Yeah, I can see how it's less visible where it is, but the nice part about keeping it in the test file is that [Go will actually compile the example](https://blog.golang.org/examples) as we run tests in CI, which means that it's more likely to stay accurate.

Would a link or something to the file help?

**Comment by sanae10001** [comment]
@brandur-stripe 
I understand, thanks.
Have no other problems.

**Comment by brandur-stripe** [comment]
No worries! Closing this out for now.
