### ISSUE TITLE
Metadata cannot be set from nested params

### ISSUE THREAD

**Issue by brandur-stripe** [stripe/stripe-go#439]
By design, `Meta` belongs to the basic `Params` structure which all other parameters structures compose. Unfortunately though, during the course of an API call, it's only the top-level `Params` that has its `AppendTo` called, meaning that setting metadata on a nested structure is not possible:

``` go
customer.New(&stripe.CustomerParams {
  Source:  &stripe.SourceParams{
    Card: &stripe.CardParams{
      // Other CardParam fields
      Params: stripe.Params{
        Meta: cardInfo.Metadata,
      },
    },
  },
})
```

Fundamentally, the `AppendTo` implementation of `Params` cannot support it because it always writes `metadata` out at the top level:

``` go
func (p *Params) AppendTo(body *RequestValues) {
	for k, v := range p.Meta {
		body.Add(fmt.Sprintf("metadata[%v]", k), v)
	}

	for _, v := range p.Exp {
		body.Add("expand[]", v)
	}

	for k, vs := range p.Extra {
		for _, v := range vs {
			body.Add(k, v)
		}
	}
}
```

There's probably a few ways to fix this problem, but I suspect adding `Meta` to the top-level `Params` may have been a conceptual mistake in the API design — really it should probably be included on every parameters structure that supports it, and those parameter structures should be able to serialize it appropriately.

It's going to take a bit of refactoring to unwind this properly, so tagging this issue as future for the time being.

**Comment by remi-stripe** [comment]
Flagging that there are some edge-cases where the API won't support this at all. For example, creating a Customer with a card token means that you can not pass metadata on the card itself. The API would otherwise receive `source=tok_XXX` and `source[metadata][key]=value` which the API would reject.

**Comment by brandur-stripe** [comment]
@remi-stripe +1. I think our goal here should be to structure the API such that while errors are possible from either the compiler or the API, silent and mysterious failures that succeed but don't do what you intended to do, aren't (which seems to be the current situation).

**Comment by brandur-stripe** [comment]
I think this one's been fixed ever since the addition of the `form` package ages ago. Closing.
