### ISSUE TITLE
json error parsing webhook body

### ISSUE THREAD

**Issue by carlymarshmallow** [stripe/stripe-go#441]
When using ConstructEvent to verify and parse a charge.succeeded webhook there is a json parse error:

`Failed to parse webhook body json: json: cannot unmarshal string into Go struct field Event.request of type stripe.EventRequest.`

Here is the webhook body:
```javascript
{
  "id": "evt_YAyzHp4WaWW714",
  "object": "event",
  "api_version": "2015-02-16",
  "created": 1501192497,
  "livemode": false,
  "pending_webhooks": 1,
  "request": "req_mKRK26Lny9hgz8",
  "type": "charge.succeeded",
  "data": {...}
}
```

**Comment by remi-stripe** [comment]
@carlymarshmallow  The issue is that your event is based on an old API version `2015-02-16` and the Go library only supports the latest API version. If you use the Go library, you need to make sure that the API version in your account is in line with the version enforced in the repository otherwise you will not be able to deserialize events.

**Comment by carlymarshmallow** [comment]
@remi-stripe Ok I will look into upgrading, thank you.

**Comment by tj** [comment]
shoulda' vendored :( happened to me too

**Comment by mvpmvh** [comment]
where does one view the api version supported by the go library? I've vendor locked my go client to `revision = "be3df3193a5201385c5a3c66e9ca32ae6317e88c"`
 `version = "v25.0.0"`
and api version `2015-09-23`
and am currently seeing inconsistent behavior (i.e. some unmarshaling errors as stated above, and some unmarshaling working just fine).

**Comment by brandur-stripe** [comment]
@mvpmvh If you `cd` into your vendored version of `stripe-go`, you can open `stripe.go` and view the locked API version as `apiversion`.

**Comment by mvpmvh** [comment]
@brandur-stripe - thanks. 
you guys don't happen to version your api docs, do you? https://stripe.com/docs/api looks like it might only be the latest

**Comment by ob-stripe** [comment]
@mvpmvh We show the latest version by default, but you can use the `version` query parameter to show the docs for a specific version, e.g. https://stripe.com/docs/api?version=2015-02-18

**Comment by mvpmvh** [comment]
idk if this is the best medium for this conversation (although it might be useful for posterity), but I tried a quick verification by going to https://stripe.com/docs/api?version=2015-07-13#event_object and comparing those docs to https://github.com/stripe/stripe-go/blob/v12.1.0/event.go#L17.

From what I can tell, there's a mismatch between the api docs and the go client. For example:
in the docs, the event's `request` is a hash, but to go client is a string.

**Comment by ob-stripe** [comment]
Hm, I'm fairly sure the API reference is incorrect here. This specific change was introduced in version [2017-05-25](https://stripe.com/docs/upgrades#2017-05-25).

I'll report this internally, though feel free to report this by writing in using the form at https://support.stripe.com/email too.
