### ISSUE TITLE
StripeAccount field not registering in charge params

### ISSUE THREAD

**Issue by dparadise28** [stripe/stripe-go#445]
I may be using the interface incorrectly but when implimenting the example given on the sites instruction to create direct charges I have an error thrown that tells me that the StoreAccount field is not present in the ChargeParams struct. 

https://stripe.com/docs/connect/direct-charges
`    params := &stripe.ChargeParams{
        Fee:       fee,
        Amount:    amount,
        Currency:  "usd",
        NoCapture: true,
        StripeAccount: order.Store.PaymentDetails.StripeAccountID,
    }`
`unknown field 'StripeAccount' in struct literal of type stripe.ChargeParams`

**Comment by remi-stripe** [comment]
Hey @dparadise28. I just tried that exact code on my end and got the same error because `StripeAccount` is sub-field of the `Params` sub-`struct` that is part of all our `*Params`. I'll work with our documentation team to update this but here's how you should set this up:

``` params := &stripe.ChargeParams{
  Amount: 1000,
  Currency: "usd",
}
params.SetSource("tok_visa")
params.Params.StripeAccount = "acct_CONNECTED"

ch, err := charge.New(params)```
