### ISSUE TITLE
Always name fields after API request/response fields; remove all cases of weird abbreviation

### ISSUE THREAD

**Issue by brandur-stripe** [stripe/stripe-go#457]
Especially near the beginning of this library's life we engaged in a lot of weird abbreviate. For example a source is a `Src` and a transaction is a `Tx`. This most often obfuscates things unnecessarily when users are comparing our API reference to what they see in the library.

We haven't been abbreviated newly added fields for some time, so at some point let's go back and and strip out all the pre-existing ones.

**Comment by remi-stripe** [comment]
@brandur-stripe I will take this one and get started on it this week!

**Comment by brandur-stripe** [comment]
@remi-stripe Excellent :)

**Comment by brandur-stripe** [comment]
Problem solved thanks to Remi! Closing.
