### ISSUE TITLE
Issues when passing bank account details directly in external account creations

### ISSUE THREAD

**Issue by ob-stripe** [stripe/stripe-go#485]
cc @thorsten-stripe @gh-stripe 

@thorsten-stripe noticed a couple of issues when trying to add an external account to a custom account:

1. When using `ExternalAccountParams` and providing the bank account details directly, no `object` parameter is sent, causing the API request to fail.

2. When using `BankAccountParams` (as shown in the API reference [here](https://stripe.com/docs/api/go#account_create_bank_account)) and providing the bank account details directly, the library will send empty values for `account_holder_name` and `account_holder_type` if they are not provided. This causes the API request to fail with ""The bank account type you have added is invalid. You must pass either 'company' or 'individual'.""

    These parameters are only required when creating a bank account for payins (i.e. ACH). They are optional when creating a bank account as an external payouts account.

**Comment by brandur-stripe** [comment]
Totally missed that Remi was already working on this and had assigned it to himself. Sorry :/

**Comment by brandur-stripe** [comment]
#487 squashed the rest of this one. Closing.
