### ISSUE TITLE
Not able to create a charge based on card id and customer id

### ISSUE THREAD

**Issue by Swatiparbhakar** [stripe/stripe-go#489]
Hello Team,
I want to create a charge based on customer_id and card_id. But I did not found any way to do this.
If I am using only customer_id then charge created with the default card for that customer, but I need to charge a specific card (based on card id)  for a customer. 
Thanks in advance!

**Comment by ob-stripe** [comment]
Hi @Swatiparbhakar, I can't test this right now but I believe the following should work:

```go
charge, err := New(&stripe.ChargeParams{
	Amount: 400,
	Currency: "usd",
	Customer: "cus_...",
	Source: &stripe.SourceParams{Token: "card_..."},
})
```

**Comment by remi-stripe** [comment]
You can also use `SetSource` for this:

```
    chargeParams := &stripe.ChargeParams{
      Amount: 2000,
      Currency: "usd",
      Customer: "cus_123",
    }
    chargeParams.SetSource("card_ABC")
    ch, err := charge.New(chargeParams)
```

**Comment by shivkumarsingh7** [comment]
Is this working? If try with new card it will give me below error:
**Customer cus_123 does not have a linked source with ID tok_123**

**Comment by ob-stripe** [comment]
@shivkumarsingh7 You first need to use the token to [create a new card](https://stripe.com/docs/api#create_card) on the customer object, then you can [create the charge](https://stripe.com/docs/api#create_charge) by passing the card ID (`card_...`) instead of the token ID in the `source` parameter.

**Comment by shivkumarsingh7** [comment]
@ob-stripe Thanks a lot :)
