### ISSUE TITLE
function creating Stripe-Signature

### ISSUE THREAD

**Issue by jmhodges** [stripe/stripe-go#497]
It would be nice if this library had a means to create a Stripe-Signature for use in tests of code that use `webhook.ConstructEvent` and related functions. I think I'll have one to contribute soon if that's of interest.

**Comment by ob-stripe** [comment]
Hey @jmhodges, good news! The library already has this feature via the `computeSignature` function: https://github.com/stripe/stripe-go/blob/0f6277583a1514c96f7141d8aa1365eea6b382f8/webhook/client.go#L32-L38.

You can take a look at the code [here](https://github.com/stripe/stripe-go/blob/0f6277583a1514c96f7141d8aa1365eea6b382f8/webhook/client_test.go#L25-L41) to see how we generate signed payloads in our tests.

I'm closing the issue as this feature already exists, but feel free to reply if I misunderstood your request!

**Comment by brandur-stripe** [comment]
The function signature should be pretty stable, so it might be okay to just export this. One thing we might want to clean up is the types: it's a little weird that `payload` comes in as `[]byte` and `secret` comes in as `string`. Ideally, they'd both be one or the other.

`secret` gets changed to a `[]byte` inside the function anyway, so should be an easy change at least.

**Comment by brandur-stripe** [comment]
Exported in 40.0.0.
