### ISSUE TITLE
Event.GetObjValue cannot handle arrays

### ISSUE THREAD

**Issue by timendez** [stripe/stripe-go#503]
Hi, I've spoken with Stripe support and the IRC channel over the course of a couple days, and we've come to the conclusion that it's not a bug, just not implemented yet. If that's not the case please let me know otherwise!

On the invoice created event, I'm trying to access the plan ID, but am having trouble because I'm not sure how to drill down into an array with `GetObjValue`. `planID := event.GetObjValue("lines", "data[0]", "plan", "id")` would be great, or `"data", "0"`. Upon more research I've found that not every object in `data` will have a `plan` key, but I think this is a useful feature regardless.

Let me know if you have any plans to implement this, or if there is a better way to go about dealing with arrays located within events.

Thanks!

**Comment by ob-stripe** [comment]
Hi @timendez! I haven't had time to dig properly, but from a quick glance at the code I think that you're correct and the `GetObjValue` function is currently unable to access arrays. I agree it would be a nice addition though!

cc @brandur-stripe to take a look and maybe open a quick PR if it's easy to implement :)

**Comment by brandur** [comment]
Hm, the implementation would be easy, but a potential problem is that `"0"` is ambiguous between the zero-index of an array/slice or a key named `0` in a map. I think the implementation would have to try to coerce to both possible types, which isn't amazing. On the other hand, `GetObjValue` is a pretty quick and dirty API in the first place, so maybe it doesn't matter that much.

**Comment by timendez** [comment]
can you implement it where `"data[0]"` is the parameter instead of `"data", "0"` then?

**Comment by brandur** [comment]
@timendez Thinking about this a little more, I think it's okay to implement this as you originally proposed. I took a stab in #506.

**Comment by timendez** [comment]
Awesome, thank you man 👍
