### ISSUE TITLE
[Question] How to decode a ChargeParams form encoded?

### ISSUE THREAD

**Issue by AlexandreRoba** [stripe/stripe-go#524]
I looked at the documentation and in the standard ios implementation flow the backend provided in rails is the following:
https://github.com/stripe/example-ios-backend/blob/master/web.rb
I'm trying to implement this same ios backend in GO to get familiar with the flow and int the POST of a "charge" resource the body expected is a form encoded of a ChargeParams. When looking at the stripe-go and the ChargeParams implementation I can see the struct has "form" tags. I looked at the form folder provided but my feeling is only the encoded is supported for those kind of tags. Can you tell if there is any way to "decode" a form encoded ChargeParams with the SDK?

Thanks for any help.

**Comment by remi-stripe** [comment]
@AlexandreRoba Can you clarify what you mean by "decoding a form encoded ChargeParams with the SDK" exactly?

The SDK is here to abstract the complexity away. You simply pass the parameter you want based on what you want to charge. For example, to create a $10 USD charge you would do:

```
chargeParams := &stripe.ChargeParams{
  Amount: 2000,
  Currency: "usd",
}
chargeParams.SetSource("tok_mastercard") // obtained with Stripe.js
ch, err := charge.New(chargeParams)
```

**Comment by AlexandreRoba** [comment]
Hi remi-stripe, Thanks for reaching out to me.
What I meant by "decoding a form encoded ChargeParams with the SDK" is that I need to implement a an API method to create a charge on my backend server which is called by the stripe IOS SDK. 

This API method is a POST with a content type application/x-www-form-urlencoded and the body contains a ChargeParams. This is what one of the IOS Sample apple is doing (https://github.com/stripe/stripe-ios/tree/master/Example/Standard%20Integration%20(Swift)). There is a backend server sample implementation that goes with it (https://github.com/stripe/example-ios-backend). Have a look at the web.rb file:
```ruby
post '/charge' do
  authenticate!
  # Get the credit card details submitted
  payload = params
  if request.content_type.include? 'application/json' and params.empty? 
    payload = indifferent_params(JSON.parse(request.body.read))
  end

  source = payload[:source]
  customer = payload[:customer_id] || @customer.id
  # Create the charge on Stripe's servers - this will charge the user's card
  begin
    charge = Stripe::Charge.create(
      :amount => payload[:amount], # this number should be in cents
      :currency => "usd",
      :customer => customer,
      :source => source,
      :description => "Example Charge",
      :shipping => payload[:shipping],
    )
  rescue Stripe::StripeError => e
    status 402
    return "Error creating charge: #{e.message}"
  end

  status 200
  return "Charge successfully created"
end
```

I'm trying to implement this method in GO.  I need to "decode" the body of this POST which contains a x-www-form-urlencoded of a ChargeParams in order to call. My implementation looks like:
```Go
func handleCharge(w http.ResponseWriter, r *http.Request) {
	switch r.Method{
	case http.MethodPost:
		//this should come from the authentication
		customerId := "cus_CM3Uq1cYz7f5mC"

		r.ParseForm()
		source := r.Form.Get("source")
 
//ChargeParams should come from the body
// With something like:
// var params = &stripe.ChargeParams{}
// form.decode(r.Body,params) or something....

//Dummy harcoded params
		params := &stripe.ChargeParams{
			Amount:        5000,
			Currency:      "eur",
			Customer:      customerId,
			Desc:          "Purchase on the app",
			Shipping:      &stripe.ShippingDetails{
				Address:  stripe.Address{
					City:    "Bruxelles",
					Country: "Belgium",
					Line1:   "rue du Belvédère,29",
					State:   "Bruxelles",
					Zip:     "1050",
				},
				Name:     "Alexandre Roba",
			},
		}

// Set the source
		err := params.SetSource(source)
		if err!=nil{
			log.Println(err)
			w.WriteHeader(500)
			return
		}

// Create the charge
		_,err = charge.New(params)
		if err!=nil{
			log.Println(err)
			w.WriteHeader(500)
			return
		}
		w.WriteHeader(200)
	default:
		w.WriteHeader(http.StatusBadRequest)
	}
}
```

Is this clearer?

**Comment by remi-stripe** [comment]
@AlexandreRoba It is, thank you for the detailed explanation. So this is not really related to the Go library itself. You're asking how to parse POST parameters in Go so that you can fill out the right parameters in your own request.

We're not really sending ChargeParams from the mobile SDK either. It's a simple POST request with parameters directly in it. You can fetch the card id  in the `source` parameter for example.

Since it's not about a bug in the library and more a general development question, I'm going to close this out. I'd recommend looking into articles such as [this one](https://medium.com/@edwardpie/processing-form-request-data-in-golang-2dff4c2441be) and working on a simple example without even trying in Swift for now. Just make a post request to your server with curl or [hurl.it](https://www.hurl.it/) and then make sure your Go code can fetch the information.

**Comment by AlexandreRoba** [comment]
Hi @remi-stripe,
Thanks for the reply and yes you are right about the fact that I can decode manually the form posted using the Stripe IOS SDK but... When looking at the ChargeParams implementation on the Stripe-go Package you can find the following:
```Go
type ChargeParams struct {
	Params        `form:"*"`
	Amount        uint64              `form:"amount"`
	Currency      Currency            `form:"currency"`
	Customer      string              `form:"customer"`
... Removed for the example
	TransferGroup string              `form:"transfer_group"`
}
```
You (I mean the team :)) define a set of "custom" tag in order to be able to "Encode" the structure into a form and also provide an implementation that make use of those custom tags to encode the structure using: github.com/stripe/stripe-go/form/form.go

I took the I believed simpliest demo app provided by Stripe which combine the IOS standard flow application with a also simple Ios dummy backend implementation provided by stripe but in ruby and in the backend implementation it looks like it does make sens to decode that structure. IMHO as you define those meta tags to encode it why not provided in form.go a way to decode the structure.

Hope you will reconsider this decision

Best regards,

**Comment by remi-stripe** [comment]
@AlexandreRoba I think you're mixing two things that are unrelated here. Your code needs to parse the data posted from the mobile application. This is done by using the form logic in go in your own code.

Separately, our library needs to send parameters to our API. This used to be done by literally encoding every single parameter one by one in the code. This had numerous issues where we'd add the parameter but forget to encode it in the request for example. We fixed this a few months ago by adding this logic to the `*Params` class. Every property has the name of the parameter in the API and the code will "magically" encode everything the right way.

Those two things are separate and there's no reason to have them match so there's no plan to pipe the form data from iOS for example into Go directly. It's on you to build this logic in your own integration.

**Comment by AlexandreRoba** [comment]
Hi @remi-stripe, I spent more time on the sample and indeed you are right :) Those structure are note related. Thanks for clarifying that.
