### ISSUE TITLE
upgrade SubParams to support cancel at period end

### ISSUE THREAD

**Issue by charlierudolph** [stripe/stripe-go#531]
https://stripe.com/docs/upgrades#2018-02-28

Currently `EndCancel` goes to `at_period_end` for the cancel call. We also need something for the key `cancel_at_period_end` in the update call. The cancel call should probably have its own parameter object

**Comment by remi-stripe** [comment]
@charlierudolph Those are the same parameters. You set `EndCancel` to `true` if you don't want to cancel immediately and instead cancel at the end, otherwise the subscription will cancel immediately.

**Comment by timendez** [comment]
@remi-stripe The form is `at_period_end` in `SubParams`: https://github.com/stripe/stripe-go/blob/master/sub.go#L48

However the form is `cancel_at_period_end` in `Sub`: https://github.com/stripe/stripe-go/blob/master/sub.go#L101

Is this intentional?

**Comment by remi-stripe** [comment]
@timendez it is (though a bit confusing).

The [property](https://stripe.com/docs/api#subscription_object-cancel_at_period_end) on the Subscription object is `cancel_at_period_end` which is what you see.

The [parameter](https://stripe.com/docs/api#cancel_subscription-at_period_end) itself when calling the Cancel Subscription API is `at_period_end`.

**Comment by charlierudolph** [comment]
The API docs have the key for updating as `cancel_at_period_end` (https://stripe.com/docs/api#update_subscription-cancel_at_period_end) while the key for canceling is `at_period_end` (https://stripe.com/docs/api#cancel_subscription-at_period_end).

**Comment by remi-stripe** [comment]
Okay so now I see what I missed on first read. Sorry for the confusion on this one. You're saying that you want to call the Update Subscription [API](https://stripe.com/docs/api#update_subscription) does need to be able to pass `cancel_at_period_end` because that's the name of the parameter there.

**Comment by remi-stripe** [comment]
So to clarify, stripe-go is built for a specific API version in mind. Right now it's on an older API version where this parameter did not exist so you would not be able to use it.

Once we upgrade the API version we will add support for this parameter, though this will happen in a few weeks like (we have some large PRs to merge first).

In the meantime you can use the old way which is to simply update anything else on the subscription to bring it back to active such as setting the `Plan` again to what it is.

**Comment by brandur-stripe** [comment]
Sorry for the late followup on this one, but `cancel_at_period_end` is now available as `SubscriptionParams.CancelAtPeriodEnd`. Closing.
