### ISSUE TITLE
Change APIURL from const to var, so it can be used with stripe-mock?

### ISSUE THREAD

**Issue by kerak19** [stripe/stripe-go#532]
Hi. I would like to use [stripe-mock](https://github.com/stripe/stripe-mock) for my application instead of actual Stripe API, but APIURL in stripe.go is const, so i cannot change it to match stripe-mock url and port.

Is there any other way to use stripe-go with stripe-mock?

@edit i found that BackendConfiguration struct is public, maybe i could use it

**Comment by ob-stripe** [comment]
@kerak19 You can use `stripe.SetBackend()` to change the URL, cf. https://github.com/stripe/stripe-go/blob/master/testing/testing.go#L58-L62.

**Comment by kerak19** [comment]
Thanks, i've already closed this issue, because i found it
