### ISSUE TITLE
Injecting Mock Http Client for Testing

### ISSUE THREAD

**Issue by aranw** [stripe/stripe-go#537]
Currently I'm writing tests that are making requests to Stripe using stripe-go and my test key which has worked fine for now. It has however meant that I've then made additional requests to Stripe to delete the created entries and do various cleanup. I've had no major side effects to this approach however Stripe has then fired event calls to me which I've then had to handle otherwise the events will back up and get retired until handled. 

I'm now trying to do more complicated tests and integration tests but this is causing me problems. I'm hoping for a way for me to override the stripe-go http requests and instead direct the requests at a fake server that I can boot up using httptest. 

I'm trying to test event handling logic right now and I'd really like a way to mock the call I make to Stripe to see whether it's a geniune event or not. 

Is this perhaps already possible or could there be non-breaking changes that might allow such a change?

**Comment by aranw** [comment]
I've managed to come up with a solution. 

```go

srv := httptest.NewServer(handler)

	b := stripe.NewBackends(srv.Client())
	b.API = &stripe.BackendConfiguration{
		Type:       stripe.APIBackend,
		URL:        srv.URL + "/v1",
		HTTPClient: srv.Client(),
	}

	c := &client.API{}
	c.Init("sk_test_myTestKey", b)
```

**Comment by brandur-stripe** [comment]
@aranw Nice! Yes, that looks about right. I'm going to close this out, but let us know if there's anything else that comes up.

**Comment by gebv** [comment]
actual code for 2020-01
```
srv := httptest.NewServer(handler)

	b := stripe.NewBackends(srv.Client())
	b.API = &stripe.BackendImplementation{
		Type:       stripe.APIBackend,
		URL:        srv.URL + "/v1",
		HTTPClient: srv.Client(),
	}

	c := &client.API{}
	c.Init("sk_test_myTestKey", b)
```

**Comment by meggieveggie** [comment]
@gebv Any chance you can post what the handler looks like? I am trying to use this and my handler is returning a JSON response but I am getting a memory address error somewhere

**Comment by sprak3000** [comment]
> @gebv Any chance you can post what the handler looks like? I am trying to use this and my handler is returning a JSON response but I am getting a memory address error somewhere

@meggieveggie Not sure if you solved this issue or not, but I found I needed to add the `LeveledLogger` to the setup:
```go
b.API = &stripe.BackendImplementation{
    Type:          stripe.APIBackend,
    URL:           srv.URL,
    HTTPClient:    srv.Client(),
    LeveledLogger: stripe.DefaultLeveledLogger,
}
```
