### ISSUE TITLE
Source mandate[notification_type]

### ISSUE THREAD

**Issue by NFau** [stripe/stripe-go#540]
Hi ! It seems that we cannot retrieve the mandate[notification_type] in a source object.

Here is my workflow and why I would need it:
The source is creating by the front using stripe.js, in the documentation (https://stripe.com/docs/sources/sepa-debit #Using webhooks or automated emails) it's written that the mandate[notification_type] must be set at source creation and cannot be updated later.
Since I don't trust the front-end, I do a check on received source before attaching it to the customer. However, I need to ensure that the mandate[notification_type] is properly set to manual since we rely on it to send legal mandate notification (source.mandate_notification event), and I can't find anything in the source object relating to that.

Am I wrong somehow ?
Thanks

**Comment by brandur-stripe** [comment]
A fix has been released as 30.4.0 including @remi-stripe's patch!
