### ISSUE TITLE
Update Account: Received unknown parameter: country

### ISSUE THREAD

**Issue by nd2s** [stripe/stripe-go#548]
I tried putting a bunch of information into a Stripe Connect account, and got the error: `{"code":"account_country_invalid_address","status":400,"message":"Address for business must match account country","param":"legal_entity[address][country]","request_id":"req_I7VCfEXGD6u8eT","type":"invalid_request_error"}` 

So I am now setting `AccountParams.Country` as well, but getting following error: 
`{"code":"parameter_unknown","status":400,"message":"Received unknown parameter: country","param":"country","request_id":"req_0yQq9D38zJrekr","type":"invalid_request_error"}`

    account.Update(accountID,  &stripe.AccountParams{
    		BusinessName: a.BusinessName,
    		Country:      a.Country,
    		ExternalAccount: &stripe.AccountExternalAccountParams{
    			Account:           a.BankAccount.Number,
    			AccountHolderName: a.BankAccount.Holder,
    			AccountHolderType: "company",
    			Country:           a.BankAccount.Country,
    			Currency:          a.BankAccount.Currency,
    		},
    		LegalEntity: &stripe.LegalEntity{
    			Type:                  "company",
    			AdditionalOwners:      additionalOwners,
    			AdditionalOwnersEmpty: (len(additionalOwners) == 0),
    
    			BusinessName:  a.BusinessName,
    			BusinessTaxID: a.BusinessTaxID,
    			BusinessVatID: a.BusinessVatID,
    			PhoneNumber:   a.PhoneNumber,
    
    			Address: stripe.Address{
    				Line1:   a.Street,
    				Zip:     a.PostalCode,
    				City:    a.City,
    				Country: a.Country,
    			},
    
    			First:      a.Representative.FirstName,
    			Last:       a.Representative.LastName,
    			DOB:        repDOB,
    			PersonalID: a.Representative.PersonalIDNumber,
    			PersonalAddress: stripe.Address{
    				Line1:   a.Representative.Street,
    				Zip:     a.Representative.PostalCode,
    				City:    a.Representative.City,
    				Country: a.Representative.Country,
    			},
    		},
    		TOSAcceptance: &stripe.TOSAcceptanceParams{
    			Date:      a.Timestamp.UTC().Unix(),
    			IP:        a.ClientIP,
    			UserAgent: a.UserAgent,
    		},
    	})

go version go1.10.2 linux/amd64
Lib version: 30.5.0 / ce5465147931f6e984ebb655d0a1f88b8ddd5988

**Comment by nd2s** [comment]
Thank you for your quick response!

But shouldn't the library not send this parameter on update if it is not supported?

**Comment by remi-stripe** [comment]
The `AccountParams` structure is used on creation and update. Since almost all parameters are identical (country is the exception really) it would be a lot of duplicated code to just remove one parameter that the API can already reject.
