### ISSUE TITLE
Listing cards for a given account also returns external_accounts of type bank_account.

### ISSUE THREAD

**Issue by dalan-stripe** [stripe/stripe-go#565]
Thank you @hothero for reporting! 

Not sure if this is expected behavior but the following request will have bank accounts in the response. 

```go
params := &stripe.CardListParams{Account: acctID}
params.Filters.AddFilter("limit", "", strconv.FormatInt(limit, 10))
i := o.API.Cards.List(params)
for i.Next() {
  cs = append(cs, i.Card())
}
```

Solution is to add this as well:

```go
Filters.AddFilter("object", "", "card")
```

If the request is intended to solely list the cards attached to an account, then this filter should be added by default? Not totally familiar with Go so I might be misunderstanding what this is/should be doing? - https://github.com/stripe/stripe-go/blob/master/card.go#L89

**Comment by remi-stripe** [comment]
Thanks for the report. I pushed a fix in this commit https://github.com/stripe/stripe-go/pull/544/commits/0cf81bfe3d271a0bf95f98879389e71b5c7fc242 which is part of the large PR to revamp the whole library. Hopefully we can merge it this week.

**Comment by brandur-stripe** [comment]
And the pull request Remi mentioned above is now merged! Closing this out.
