### ISSUE TITLE
http client usage on appengine

### ISSUE THREAD

**Issue by bsr203** [stripe/stripe-go#57]
I am not sure how setting http client globally works under app engine, where it is unique per request.  Does the request attach to the correct context with concurrent access to the API.

 I saw it is handled with passing a context in go oauth2 client.
please see here.
https://github.com/golang/oauth2/blob/master/client_appengine.go 
https://github.com/golang/oauth2/blob/master/oauth2.go#L160

This may be evasive as all function needs to take a context as argument.

so, currently, am I expect to set the client before all API calls?

**Comment by cosn** [comment]
Sadly I haven't actually played with Google AppEngine, but I didn't think you'd need to set it per call, but rather just once since you can't use the `defaultHTTPClient` or some of the options passed by default.
