### ISSUE TITLE
How to create 3D Secure source?

### ISSUE THREAD

**Issue by powerman** [stripe/stripe-go#574]
I'm using current master (v32.0.0). Call to `threedsecure.New()` result in 
> {"status":404,"message":"Unrecognized request URL (POST: /v1/3d_secure). Please see https://stripe.com/docs or we can help at https://support.stripe.com/.","request_id":"req_LMYBSrkfiDKdWJ","type":"invalid_request_error"}

Doc at https://stripe.com/docs/sources/three-d-secure#server-side-source-creation has no Go example. Looks like threedsecure package doesn't work and I should create usual source with `Type:"three_d_secure"` and redirect url instead?

**Comment by remi-stripe** [comment]
@powerman the package `threedsecure` is an old package that should not be used unless you have an old integration that relies on it.

Instead, you should create a Source like you did in the other example. The issue you have is that you are passing `Customer` which is not supported on 3DS Source creation. If you remove the `Customer` from your parameters, the 3DS Source will work as expected.

**Comment by powerman** [comment]
You right, thanks!
