### ISSUE TITLE
PlanTransformUsageParams: DivideBy != BucketSize

### ISSUE THREAD

**Issue by mholt** [stripe/stripe-go#575]
Hi, just in the process of upgrading to the latest version with all the big changes and it's super nice to see a lot of alignment between the REST API and the Go structs, great work!

I did notice one discrepency. It may be a non-issue, but I thought I'd ask anyway. [PlanTransformUsageParams](https://godoc.org/github.com/stripe/stripe-go#PlanTransformUsageParams) has a field called `BucketSize`(`bucket_size`) but the API docs call it [`divide_by`](https://stripe.com/docs/api#create_plan-transform_usage-divide_by).

I think they are probably the same thing, but can you verify -- and should it be fixed in this library?

**Comment by mholt** [comment]
Actually, yeah, I just confirmed by trying it, that "bucket_size" is unrecognized:

> Error encountered from Stripe: {"code":"parameter_unknown","status":400,"message":"Received unknown parameter: transform_usage[bucket_size]","param":"transform_usage[bucket_size]","request_id":"req_u4UaZBypGB3jPL","type":"invalid_request_error"}

I have patched it locally and it works fine as divide_by. :+1:

**Comment by brandur-stripe** [comment]
> Hi, just in the process of upgrading to the latest version with all the big changes and it's super nice to see a lot of alignment between the REST API and the Go structs, great work!

Thanks for being so quick on the upgrade! We were definitely a little afraid to cut that new API because of the amount of effort involved in getting upgraded, so it's good to hear that you at least seem happy with it :)

Let us know if you find any other problems.
