### ISSUE TITLE
All API calls should take a parameters struct

### ISSUE THREAD

**Issue by brandur-stripe** [stripe/stripe-go#588]
All API calls (i.e., the ones in `*/client.go` like `countryspec.Get`) should take a parameter struct. This should be true just to ensure global consistency, but it's also important because that parameters struct allows you to inject "meta"-request information like a `Stripe-Account`.

I went through with grep and made a list of all the calls that don't take one right now:

* `charge.MarkFraudulent`
* `charge.MarkSafe`
* `charge.CloseDispute`
* `countryspec.Get`
* `exchangerate.Get`
* `issuerfraudrecord.Get` (gah, can't believe we introduced one so recently, my bad for not catching that on review)

Also weird:

* `event.Get` takes a basic `params *stripe.Params` instead of implementing its own `EventParams`. We might want to fix that just for consistency because it's the only one that does that.

@remi-stripe We've talked about this one a couple times, so I'm opening this for tracking. Question for you: do you think we should bother with methods like `charge.MarkFraudulent` or should we be considering those deprecated and not bother?

**Comment by remi-stripe** [comment]
> do you think we should bother with methods like charge.MarkFraudulent or should we be considering those deprecated and not bother?

I would be fine with removing them and letting people use the Update Charge API instead. I'm also happy to tackle that issue if you are okay leaving to me.

**Comment by brandur-stripe** [comment]
> I would be fine with removing them and letting people use the Update Charge API instead.

Cool, and +1. This will be a breaking change anyway, so it'd be a good time to just get rid of the.

> I'm also happy to tackle that issue if you are okay leaving to me.

Sounds good! I think my stripe-go contributions are over for the week anyway.
