### ISSUE TITLE
plans.List(PlanListParams) - add product as parameter

### ISSUE THREAD

**Issue by dgem** [stripe/stripe-go#594]
https://stripe.com/docs/api#list_plans-product

**Comment by remi-stripe** [comment]
@dgem Thanks for the report. I just pushed a PR https://github.com/stripe/stripe-go/pull/595

**Comment by brandur-stripe** [comment]
Released as 35.2.0.

**Comment by dgem** [comment]
Wow, super impressed as I thought I'd lost the report whilst on the train and didn't get to put in details!
amazing... I will pull it now.
