### ISSUE TITLE
API version mapping to library tag

### ISSUE THREAD

**Issue by prats226** [stripe/stripe-go#598]
Where is the mapping for API version which has format `2018-05-21` and stripe-go library tag which has semantic versioning. I wanted to know what are library tags for API versions `2018-01-23` and `2018-05-21`

**Comment by remi-stripe** [comment]
@prats226 I would highly recommend not taking this approach on your end. You should instead use the latest version on master based on the most recent API version to ensure that you have the latest properties and features in the library.

**Comment by prats226** [comment]
But different breaking changes. Like previously I was using multiple plans for our product and now in latest version they have added `Product` abstraction inside stripe API itself. Now for the upgrade process, my latest branch would be on previous library tag that was compatible with older API version. Now on another branch, I am using latest library tag which I am assuming will use latest API version. 

Just wanted a compatibility mapping of which library tag is meant for which API version. Or my understanding of this whole thing is completely incorrect.

**Comment by remi-stripe** [comment]
@prats226 Your understanding is correct but if you do this you would miss out on all new properties or parameters that are added in a backwards compatible manner.

Just in case, the API version is set in `stripe.go` [here](https://github.com/stripe/stripe-go/blob/master/stripe.go#L591). You can check the history of the file to see when it was changed/merged to map it to relevant stripe-go versions.

Looking into it though, I don't think stripe-go ever supported the API version `2018-01-23` per se or `2018-05-21`. We don't guarantee that we support each API version on our side and it depends when we release new versions of the library, usually linked to adding new parameters or properties.

You can see in [this PR](https://github.com/stripe/stripe-go/pull/522) that we moved from `2017-05-25` to `2018-02-06`

**Comment by brandur-stripe** [comment]
Closing this one out for now.
