### ISSUE TITLE
Feature request: non-global logging

### ISSUE THREAD

**Issue by SamWhited** [stripe/stripe-go#608]
In a project that I am working on we have a policy of not allowing any globals or init functions and would prefer to avoid having a `setupStripeLogging(logger *log.Logger)` function. Instead, we would like a way to pass in a logger when we create our Clients or Backends (similar to how we pass dependencies down the stack as function arguments to everything else that needs them) instead of relying on global state and functions with side effects.

It seems to me like it would make the most sense to add a logger on the `BackendConfiguration` struct since that's where all logging appears to happen. This could be checked first and if it was nil the global logger could be used to maintain backwards compatibility.

To use it, a new function to create a backend with a provided configuration could be added (as far as I can tell right now the `BackendConfiguration` struct isn't usable and doesn't need to be exported, this would change that):

> func GetBackendCfg(backend SupportedBackend, config BackendConfiguration) Backend

If this is too broad (it would also let you configure everything else in BackendConfiguration) something that only let you setup logging is an option:

> func GetLoggingBackend(backend SupportedBackend, logger *log.Logger) Backend

**Comment by remi-stripe** [comment]
@SamWhited Thanks for reporting a detailed feature request! I'm assigning to @brandur-stripe to investigate whether it's something we could add in the future!

**Comment by brandur-stripe** [comment]
Yeah, agreed that this would be a nice feature to have. I've taken an initial stab in #611.
