### ISSUE TITLE
[docs] Clarify error/result of charge.New()

### ISSUE THREAD

**Issue by kytrinyx** [stripe/stripe-go#61]
It looks like the error returned from a new charge is specifically HTTP and other language-level errors, not things like invalid number, card declined. Am I understanding this correctly?

* https://stripe.com/docs/api#create_charge
* https://github.com/stripe/stripe-go/blob/master/charge/client.go#L76
* https://github.com/stripe/stripe-go/blob/master/stripe.go#L109-L130

I'd be happy to update the docs, I just wanted to check with you first that my understanding is correct.

**Comment by cosn** [comment]
yes and no. It's both HTTP status codes, but when the status code is not 200, the error structure returned is this: https://github.com/stripe/stripe-go/blob/master/error.go#L36.

Happy to look at a PR if you think there's some docs that could be updated. Thanks!

**Comment by kytrinyx** [comment]
OK, I'll submit something. Just to be clear: If the card is declined the status code is 200 and there is no error, correct?

**Comment by cosn** [comment]
correct

**Comment by kytrinyx** [comment]
thanks
