### ISSUE TITLE
Missing field in AccountParams for setting `decline_charge_on`

### ISSUE THREAD

**Issue by sfriedel** [stripe/stripe-go#617]
I wanted to set `decline_charge_on[avs_failure]` and `decline_charge_on[cvc_failure]` for a Stripe custom account and noticed that the `AccountParams` struct does not have a field for those.

It would be nice it this could be added.

**Comment by remi-stripe** [comment]
@sfriedel Thanks a lot for the report. I just pushed a fix in https://github.com/stripe/stripe-go/pull/618

**Comment by brandur-stripe** [comment]
Remi's fix has been released as 35.11.0. Thanks for the report!

**Comment by sfriedel** [comment]
Awesome, thank you for the quick response and fix.
