### ISSUE TITLE
Missing fields in InvoiceItemParams

### ISSUE THREAD

**Issue by jimbeveridge** [stripe/stripe-go#619]
The fields `unit_amount` and `quantity` are both missing from InvoiceItemParams. These are definitely supported by the server because they are used by the admin UI to create invoice items (as shown by examining the POST'd JSON).

**Comment by brandur-stripe** [comment]
Thanks for the report! We have a fix coming through in #620.

**Comment by brandur-stripe** [comment]
Released as 35.12.0.
