### ISSUE TITLE
BankAccountParams Token Missing

### ISSUE THREAD

**Issue by tylerb** [stripe/stripe-go#62]
According to [Create Recipient Documentation](https://stripe.com/docs/api/go#create_recipient), I should be able to pass a Stripe.js bank account token like so:

```go
Bank:  &stripe.BankAccountParams{Token: token}
```

in the same manner as:

```go
Card:  &stripe.CardParams{Token: token},
```

However, `Token` is not a defined field in `stripe.BankAccountParams`. Has it simply not been added yet?

**Comment by cosn** [comment]
seems like it, we'll fix this soon (also happy to look at a PR if you have one). Thanks!

**Comment by cosn** [comment]
Just saw the PR, thanks!
