### ISSUE TITLE
disable log messages? 

### ISSUE THREAD

**Issue by kevinburke** [stripe/stripe-go#64]
Is there a way to disable/redirect Stripe logging? Specifically the "Requesting..." message when an API request goes out.

I tried putting this in my own code

```go
log.SetOutput(ioutil.Discard)
```

but this disables all logging, not just from this library.

**Comment by cosn** [comment]
That's not currently possible. There's a way to enable *more* logging (via `SetDebug`), but not less. Any particular reason you want to disable it completely? Is it not useful when troubleshooting issues?

**Comment by cosn** [comment]
Added `stripe.LogLevel`.

**Comment by kevinburke** [comment]
Sorry I didn't follow up here - it is useful for debugging, but clutters up
the logs when I am running a scripts that creates lots of charges/running
the tests.


--
Kevin Burke
phone: 925.271.7005 | twentymilliseconds.com

On Sat, Jan 24, 2015 at 4:27 PM, Cosmin Nicolaescu <notifications@github.com

**Comment by cosn** [comment]
Yeah, makes sense. Hopefully the new flag helps, let me know otherwise.
