### ISSUE TITLE
Incorrect JSON tag name for tax ID

### ISSUE THREAD

**Issue by arttu** [stripe/stripe-go#670]
I think the JSON tag should be `tax_id` on this line: https://github.com/stripe/stripe-go/blob/f679e53dfd390ef0cc4230baf7ea39e73cf6813a/customer.go#L110

**Comment by remi-stripe** [comment]
@arttu Nice catch and sorry about the mistake. I just pushed a fix in https://github.com/stripe/stripe-go/pull/671 that we will deploy later today.

**Comment by brandur-stripe** [comment]
Remi's fixed as been released as part of 43.1.0.
