### ISSUE TITLE
Some classes of failed transfers have a `nil` error object

### ISSUE THREAD

**Issue by kevinburke** [stripe/stripe-go#68]
Say you are trying to transfer money to a recipient, but your account doesn't have enough funds, and your code looks like:

```go
	params := stripe.TransferParams{
		Amount:    int64(32),
		Currency:  "usd",
		Recipient: user.RecipientId,
		Desc:      "test account payout",
	}
	t, err := sc.Transfers.New(&params)
	if err != nil {
	    user.TxfrId = t.Id           
        user.Save()
        return emailConfirmation(user.Email, "Your money will be arriving soon")
     }
```

In this case you've now told the user their money was paid out, when in fact no money was transferred. Instead you need the following error logic:

```go
func transferError(t *stripe.Transfer, err error) error {
	if err != nil {
		return err
	}
	if t.FailCode != "" {
		return fmt.Errorf("transfer_failure: Transfer %s failed with code %s", t.ID, t.FailCode)
	}
	return nil
}
```

This was not obvious, and almost led to people not getting paid. 

I understand that this is more of an API decision than a library decision, but there's no page for "general questions about API design", and it's particularly an issue in Go when the a) the error return parameter is used everywhere to report errors, and b) most people would categorize "the money will not be transferred" as an error.

**Comment by cosn** [comment]
So there's a few things here to clarify:

1. Transfers are not synchronous. Most failures can actually happen days after the transfer was created, so any flow that deals with transfers should keep that in mind
2. There is a known bug on our side where *testmode* transfers that cause the balance to go negative are accepted (vs. getting a 400-level error). In livemode this would not happen

The fix for 2 should be documented in an upcoming api-announce.

Does this make sense?

**Comment by kevinburke** [comment]
There are some cases where we know *right now* that the transfer will fail. Not just insufficient funds, but

- Recipient bank account closed
- Recipient bank account invalid
- Not authorized
- Invalid currency

It's *unintuitive* to have to check both the error object and a property of the Transfer object to determine whether the transfer failed. At the very least, the documentation should give an example of error checking ("you need to check both the error and the FailCode object to see if your transfer went through, or poll in 48-92 hours to see if the transfer succeeded").

**Comment by cosn** [comment]
Yeah, agreed this could be improved. I might just make the library return an error in some of these cases, but I do think having some consistency and principles applied to the API also is good, so we'll discuss internally soon. 

Thanks!
