### ISSUE TITLE
`SourceObjectParams` missing `receiver` field

### ISSUE THREAD

**Issue by ddosic** [stripe/stripe-go#684]
Hello, 

I have tried using the `source.New`, but it seems that I cannot set the `receiver.refund_attributes_method` as declared in https://stripe.com/docs/api#create_source

Am I missing something in the stripe-go api, or should the `SourceObjectParams` be enriched with another field?

Thanks,
Dejan

**Comment by remi-stripe** [comment]
@ddosic Thanks for the report! I just opened a PR https://github.com/stripe/stripe-go/pull/686 that will fix this and we will merge it later this week.

**Comment by ddosic** [comment]
That is great to hear, thanks!
