### ISSUE TITLE
stripe.com/docs often say "panics an error if..." but code doesn't match up

### ISSUE THREAD

**Issue by teepark** [stripe/stripe-go#70]
This sounded strange as it would be pretty non-idiomatic to panic out of a library like this, so I spot-checked a few places[1] and found that the library is doing the right thing and just returning non-nil errors.

Please fix the documentation to not confuse/scare newcomers like me.

[1]
https://stripe.com/docs/api/go#create_customer
vs
https://github.com/stripe/stripe-go/blob/master/customer/client.go#L68

https://stripe.com/docs/api/go#create_card
vs
https://github.com/stripe/stripe-go/blob/master/sub/client.go#L65

**Comment by cosn** [comment]
Ah indeed "panic" is a poor choice of wording. Thanks!
