### ISSUE TITLE
Closed connection with `define Request.GetBody` error message

### ISSUE THREAD

**Issue by majelbstoat** [stripe/stripe-go#710]
Running a script to delete subscriptions in a loop, I get:

```
http2: server sent GOAWAY and closed the connection; LastStreamID=XXXX, ErrCode=NO_ERROR, debug=""
Delete https://api.stripe.com/v1/subscriptions/sub_XXXXXXXXXXXXXX: http2: Transport: cannot retry err [http2: Transport received Server's graceful shutdown GOAWAY] after Request.Body was written; define Request.GetBody to avoid this error
```

I guess I was kind of expecting the SDK to handle closed connections, but if that's not happening, is there a recommended way to capture these specific errors and reconnect?

**Comment by remi-stripe** [comment]
@majelbstoat Thanks for the report! We're going to investigate and see what the right fix would be for that one but it might take a bit of time to get to a definitive answer!

**Comment by brandur-stripe** [comment]
It looks like it won't hurt to just start setting `Request.GetBody`. Opened #711.
