### ISSUE TITLE
SetHTTPClient and other global setters need locking

### ISSUE THREAD

**Issue by jmhodges** [stripe/stripe-go#72]
The Go runtime does not guarantee that pointer swaps are atomic (e.g. many non-x86 processors). In order for these globals to be used, the code needs to use locks or atomic loads and swaps to pull these objects out without racing.

Honestly, it would be preferable to have these as default clients etc. that can't be changed and just make it easier to build out clients that do not use the default HTTP client. Currently, it's very difficult to not use the default HTTP client, etc., because of the complicated use of BackendConfiguration, SupportedBackend, Backend, and even Backends types in this API.

**Comment by jmhodges** [comment]
The "etc." I kept putting in there is because there is more code that get and sets globals without locks. Examples include GetBackends, SetBackends, Key, LogLevel. I've not evaluated the rest of the code.

**Comment by cosn** [comment]
Most of those are actually not meant to be used in production, and certainly not intended to be called more than once. That being said, I'm happy to review a PR if you feel this is important enough.

I do agree the multiple backends definitely made things more complex, and would be happy to re-evaluate the approach if there's enough demand for it (currently the main use-case other than unit testing is Google App Engine).

**Comment by jmhodges** [comment]
So, the issue isn't just that these globals can be set more than once, it's that you can easily have spawned off threads before these globals are set up. Then, by way of the Go and your processor's memory model, those threads are not guaranteed to see any changes to those globals. 

This leads to memory corruption (if a pointer is "half-set" in one thread's view, for instance) and is a source of panics and memory insecurity (that is, a place where bad guys can do bad things; one of the few Go has).

Dmitriy Vyukov has a good article on why "benign races" [aren't actually benign](https://software.intel.com/en-us/blogs/2013/01/06/benign-data-races-what-could-possibly-go-wrong).

**Comment by jmhodges** [comment]
(Oh, important note I forgot: even importing a package can [spawn other goroutines](https://golang.org/ref/mem#tmp_4).)

**Comment by cosn** [comment]
Given that this is and edge case of an edge case (race in global client in a concurrent context on a non-x86 arch), I don't think adding locks everywhere is worth it (especially given the fact that most of these are again, not necessarily useful in production). If you strongly disagree, feel free to send out a PR and I'm happy to take a look.
