### ISSUE TITLE
Cannot set PaymentIntentTransferData in PaymentIntentParams

### ISSUE THREAD

**Issue by nd2s** [stripe/stripe-go#726]
I need to create a new `PaymentIntent` with "destination" to automatically transfer funds to a connected account. It seems this is done via `transfer_data`/`PaymentIntentTransferData` but that's missing in `PaymentIntentParams`.

**Comment by remi-stripe** [comment]
@nd2s Sorry about the trouble for that one. I opened a PR that will fix the issue and we'll release it early next week but you can use the code in that one for now!

**Comment by brandur-stripe** [comment]
Remi's fix has been merged and released as 53.3.0.

**Comment by nd2s** [comment]
Unfortunately this isn't working:
`parameter_unknown: Received unknown parameter: transfer_data[amount])`

I noticed there really is no `amount` attribute in the current API - I guess this should be a ticket for the API team?!

**Comment by remi-stripe** [comment]
@nd2s You need to use Application Fees instead of `transfer_data[amount]` for Payment Intents. The `transfer_data[amount]` is here for legacy reasons for specific users but not recommended otherwise and disabled for most.

**Comment by nd2s** [comment]
@remi-stripe But I think this doesn't work for us.

> The amount of the application fee (if any) that will be applied to the payment and transferred to the application owner’s Stripe account. To use an application fee, the request must be made on behalf of another account, using the Stripe-Account header or an OAuth key. For more information, see Collecting application fees.

If we make the payment on behalf of a connected account, the account would habe to pay the Stripe fees. That's why all our payments go to the marketplace account and we create transfers to the connected accounts. We keep our commission and pay the Stripe fee with it.

**Comment by remi-stripe** [comment]
@nd2s This works fine even in your case, just try it you'll see. You pass `transfer_data[destination]` to indicate where to send the funds and `application_fee_amount` to indicate how much to keep as your fee. This is documented in details here: https://stripe.com/docs/payments/payment-intents/usage#connect

**Comment by nd2s** [comment]
Yes, that works. Many thanks!
