### ISSUE TITLE
SubParams: Support trial_end: now

### ISSUE THREAD

**Issue by epelc** [stripe/stripe-go#74]
The sub params do not support the special `now` value for `TrialEnd`. Using `time.Now().Unix()` is problematic because depending on server/network lag you could end up with the following error

```
Error encountered from Stripe: {"type":"invalid_request_error","message":"Invalid timestamp: must be an integer Unix timestamp in the future.","param":"trial_end"}
```

I think a `EndTrial` bool would work nice for this case.

https://stripe.com/docs/api/go#update_subscription

**Comment by cosn** [comment]
Thanks!

**Comment by epelc** [comment]
@cosn Thanks for this
