### ISSUE TITLE
Missing import after version update

### ISSUE THREAD

**Issue by JeremyChase** [stripe/stripe-go#767]
The `v55` version is not publicly available.

https://github.com/stripe/stripe-go/blob/master/webhook/client.go#L14
`github.com/stripe/stripe-go/v55` 404's.

Go Version: go1.11.2
Latest stripe version from github.

**Comment by brandur-stripe** [comment]
Hey @JeremyChase, sorry to hear about the trouble here.

So the `v55` in this case is a "virtual" suffix that's powered by Go's [new module system](https://github.com/golang/go/wiki/Modules).

Your version of Go should support it, so I think this might be a case of trying to combine the new suffix with a slightly outdated version of stripe-go.

Depending on what your local set up looks like, could you try something like this?

``` sh
cd $GOPATH/src/github.com/stripe/stripe-go/
git pull origin master
```

Then try building again?

**Comment by brandur-stripe** [comment]
And one more note: if your project is not using Go modules (has a `go.mod` in its root), then I believe you can't use the new import paths. You still want (for example):

``` sh
import "github.com/stripe/stripe-go"
```

Instead of:

``` sh
import "github.com/stripe/stripe-go/v55"
```

**Comment by JeremyChase** [comment]
Hey Brandur - thanks for the quick response.

I looked out our CI output and the code is _compiling_ but `go-swagger` is failing. After some hunting it turns out that modules [aren't yet supported in go-swagger](https://github.com/go-swagger/go-swagger/issues/1681). 

So - I believe we should close this issue in `stripe-go`. Thanks again

**Comment by brandur-stripe** [comment]
No worries Jeremy, and glad you were able to track it down.

If you find a resolution for that, it'd be great if you could post it here if it looks like it might be helpful for others.
