### ISSUE TITLE
Cannot find package v55/form

### ISSUE THREAD

**Issue by gourlaa** [stripe/stripe-go#771]
Hi Stripe,

Since your last release, we can't get Stripe using go get.

Here is the result:

go get -u github.com/stripe/stripe-go

```
package github.com/stripe/stripe-go/v55/form: cannot find package "github.com/stripe/stripe-go/v55/form" in any of:
        D:\Go\src\github.com\stripe\stripe-go\v55\form (from $GOROOT)
        D:\Code\home\htdocs\go\src\github.com\stripe\stripe-go\v55\form (from $GOPATH)
```

Have a good day

**Comment by ob-stripe** [comment]
Hi @gourlaa. Which version of Go are you using? As of v55, stripe-go uses [modules](https://github.com/golang/go/wiki/Modules), which requires Go  1.11, 1.10.3 or 1.9.7.

**Comment by gourlaa** [comment]
We are using the go version 1.9.2 but why the release v55.8.0 is working fine ?

**Comment by ob-stripe** [comment]
Actually, I think the change was pushed in 55.9.0. @brandur-stripe, can you confirm?

@gourlaa Can you try upgrading Go to 1.9.7?

**Comment by gourlaa** [comment]
We just upgraded to the 1.11.4, and it's now working fine. You should add a breaking change in your release.

Thanks!

**Comment by ob-stripe** [comment]
Yep, seems like this should have been released with a major version bump. Sorry for the inconvenience!

Closing the issue. @brandur-stripe, maybe we ought to re-release the latest version as v56.0.0? Or at least add a notice in the changelog.

**Comment by XanderDwyl** [comment]
hope it will be fixed soon, we are using this package and encounter same error

**Comment by brandur-stripe** [comment]
@ob-stripe Yeah, let me take a closer look at this. I don't think re-releasing a major will help that much because people aren't paying too much attention to the version in Go anyway. At minimum I'll add a README note, but we may also have to revert until dep is able to mature a little further.
