### ISSUE TITLE
IssuingCardDetails.Number has incorrect json tag

### ISSUE THREAD

**Issue by tylerb** [stripe/stripe-go#786]
Hey there!

I know this is fixed in https://github.com/stripe/stripe-go/commit/191c859892451556bdbe09068eae3be158da6f4e, but it appears it was not backported to previous releases. We're currently using `v36.*.*` and we have manually edited the json tag to be `number` instead of `type` in our vendored code. However, this is causing issues whenever we go to vendor new code as it overwrites that change.

Would it be possible to issue a release like `v36.3.1` with just https://github.com/stripe/stripe-go/commit/191c859892451556bdbe09068eae3be158da6f4e as a bugfix?

Thanks!

**Comment by remi-stripe** [comment]
@tylerb Unfortunately, we never backport fixes to previous releases today. All fixes are always added to the next version. You will have to upgrade your integration to use the latest stripe-go instead (or at least the one that included that change).

**Comment by tylerb** [comment]
Rats. Ok. We'll see what we can do on our end. Thanks!
