### ISSUE TITLE
stripe-go/client missing the UsageRecordSummary client

### ISSUE THREAD

**Issue by ks2211** [stripe/stripe-go#799]
Go version 1.11.4
Stripe SDK version 57.1.0 (latest)

The stripe-go/client API struct is missing the `UsageRecordSummary` Client. The `USageRecords` client is present but no `UsageRecordSummary`. 
https://github.com/stripe/stripe-go/blob/v57.1.0/client/api.go#L184

**Comment by remi-stripe** [comment]
@ks2211 This was released as 57.1.1
