### ISSUE TITLE
Subscriptions object does not have `latest_invoice` field

### ISSUE THREAD

**Issue by mahirk** [stripe/stripe-go#801]
Hello,

When attempting to expand and access the `latest_invoice` on retrieving a subscription, the `latest_invoice` field is not populated with the details from the response. Specifically here: https://github.com/stripe/stripe-go/blob/master/sub.go#L128

Unsure if that is actual functionality which is missing, intentionally left out or is there another way of accessing those fields.

**Library Version**: 56.0.0
**Go Version**: 1.9.4

**Comment by remi-stripe** [comment]
@mahirk This was released in 57.2.0
