### ISSUE TITLE
panic: event.GetObjValue(...) with non-strings

### ISSUE THREAD

**Issue by mattes** [stripe/stripe-go#82]
```go
event.GetObjValue("amount_due")
```

will panic: 

```
interface conversion: interface is float64, not string
```

https://github.com/stripe/stripe-go/blob/e9daefe4d3a026f2ca867a40f49045aaa51ffab8/event.go#L69

**Comment by cosn** [comment]
Fixed in 019138ae29961efd68dfc80427007c150938664c. Thanks!
