### ISSUE TITLE
Missing "webhooks" api in the client.API struct

### ISSUE THREAD

**Issue by ks2211** [stripe/stripe-go#822]
Go version 1.11.4
Stripe SDK version 60.0.0 (latest)

The stripe-go/client API struct is missing the Webhooks Client. The WebhooksEndpoint client is present but no Webhooks.
https://github.com/stripe/stripe-go/blob/master/client/api.go#L189

**Comment by ob-stripe** [comment]
Hi @ks2211. The `webhook` module is not an API client: there is no API resource called `webhook`, or any `/v1/webhooks` API endpoints.

Rather, it contains utility methods meant to be used to deserialize and verify webhook payloads sent by Stripe to your webhook endpoints. Cf. https://stripe.com/docs/webhooks/signatures#verify-official-libraries for an example of how to use the Go library to verify webhook signatures and deserialize events using the `webhook.ConstructEvent` function.

Closing as this doesn't appear to be an issue with the Go client library, but feel free to reply and provide more information if you believe it is.

**Comment by ks2211** [comment]
@ob-stripe thanks for the explanation, figured out the issue I was having, thanks!
