### ISSUE TITLE
How to use events GetObjectValue ? causing a panic

### ISSUE THREAD

**Issue by bjm88** [stripe/stripe-go#838]
user.Email = event.GetObjectValue("receipt_email")
or this..
user.Email = event.GetObjectValue("billing_details", "email")
causing:

2019/04/22 20:40:23 [Recovery] 2019/04/22 - 20:40:23 panic recovered:
POST /api/payment/webhook/stripe HTTP/1.1
Host: 8031acad.ngrok.io
Connection: close
Accept: */*; q=0.5, application/xml
Authorization: Basic U1RSSVBFOnNrX3Rlc3RfeVdMV3pEYXVLbmMzbHFlaTNsQzd0OWxHMDB1Y1lMblMxSA==
Cache-Control: no-cache
Connection: close
Content-Length: 4762
Content-Type: application/json; charset=utf-8
Stripe-Signature: t=1555980020,v1=6a7842d35827ed02363edcea686c71c682643228cbb70465f7788b744ddf24ea,v0=ac5025d15256b95e31c63950fea470d518cb782c64eb36fe4e891c8ebb97a0fb
User-Agent: Stripe/1.0 (+https://stripe.com/docs/webhooks)
X-Forwarded-For: 54.187.205.235
X-Forwarded-Proto: https

Cannot descend into non-map non-slice object with key: email
/Users/ben/go/pkg/mod/github.com/stripe/stripe-go@v60.4.0+incompatible/event.go:116 (0x1876a33)
	getValue: panic(fmt.Sprintf(
/Users/ben/go/pkg/mod/github.com/stripe/stripe-go@v60.4.0+incompatible/event.go:69 (0x1926868)
	(*Event).GetObjectValue: return getValue(e.Data.Object, keys)

**Comment by brandur-stripe** [comment]
Hi @bjm88,

Sorry about the trouble, but this probably just means that you either don't have a `billing_details` subobject, or you do have one, but you don't have an `email` within it. You can verify this by just printing the contents of your event's object:

``` go
fmt.Printf("my object looks like = %+v\n", event.Data.Object)

For better or for worse, this is how `GetObjectValue` is intended to function — it's a bit of a blunt tool. Closing this out.
