### ISSUE TITLE
CheckoutSessionSubscriptionDataParams.Items Isn't an Array

### ISSUE THREAD

**Issue by jor-go** [stripe/stripe-go#847]
The **/v1/checkout/session** is expecting `subscription_data.items` to be an array however, `CheckoutSessionSubscriptionDataParams.Items` is a singular `CheckoutSessionSubscriptionDataItemsParams`. 
This causes a "Invalid Array" error on the endpoint.

Go Version: 1.12.1
stripe-go Version: v60.12.0

**Comment by remi-stripe** [comment]
@jor-go Sorry for the trouble on that one, that's my bad. Will push a fix soon.

**Comment by remi-stripe** [comment]
@jor-go I just released 60.12.1 which fixes the issue, thanks again for flagging!
