### ISSUE TITLE
Source doesn't have Customer data?

### ISSUE THREAD

**Issue by danqing** [stripe/stripe-go#849]
According to the [documentation](https://stripe.com/docs/api/sources/attach), source objects have a string key called `customer` that is supposed to hold the customer ID. The [Source type](https://godoc.org/github.com/stripe/stripe-go#Source) doesn't have such a key though. Am I missing anything? Thanks!

**Comment by remi-stripe** [comment]
@danqing This is now fixed in 60.13.0
