### ISSUE TITLE
PaymentMethods API is not available

### ISSUE THREAD

**Issue by layby42** [stripe/stripe-go#852]
I'm trying to create payment method as part of backend test. Looks like it should be possible (see https://stripe.com/docs/api/payment_methods/create), but `PaymentMethods *paymentmethod.Client` is not listed in https://github.com/stripe/stripe-go/blob/master/client/api.go.

**Comment by remi-stripe** [comment]
@layby42 Sorry for the trouble. I'll push a fix soon

**Comment by remi-stripe** [comment]
This has now been fixed in 60.13.1
