### ISSUE TITLE
PaymentIntentParams type does not include field for `requested_credentials`

### ISSUE THREAD

**Issue by g-wilson** [stripe/stripe-go#901]
`requested_credentials` is a preview feature so not sure what the plan is to implement this property? https://stripe.com/docs/api/payment_intents/create?lang=go#create_payment_intent-requested_credentials

**Comment by g-wilson** [comment]
Please ignore - API has been updated since https://stripe.com/docs/payments/3d-secure#manual-three-ds

**Comment by remi-stripe** [comment]
@g-wilson Thanks for taking the time to update the thread with the latest state!

I also wanted to mention that the library supports a way to send undocumented parameters, which is useful for features that are in beta for example and not yet in the library. The idea is to use the `AddExtra` method:

```
params := &stripe.CustomerParams{
  Amount: stripe.Int64(1000),
  Currency: stripe.String(string(stripe.CurrencyUSD)),
}
params.SetSource("tok_visa")
 
params.AddExtra("custom_parameter_name", "param_value");
params.AddExtra("other_parameter_name[nested]", "other_value");
 
charge, err := charge.New(params)
```

I hope it helps if you (or someone else) needs this in the future.
