### ISSUE TITLE
No way to override default payment source in invoice with payment intent

### ISSUE THREAD

**Issue by ronanamsterdam** [stripe/stripe-go#907]
currently when submitting a payment request with existing user -> setting a `PaymentMethod` or `Source` has not effect on invoice -> it will always choose the default  payment  method that is set for user.

Preconditions: 
*note test data is being used in the example bellow
1. existing stripe_user has two cards:
DEFAULT -> "card_1F17HIAwfGMwqxjvFiJtZFiE", 
and "card_1F17NyAwfGMwqxjvUYAVIkIJ"
2. created intent is being used to charge for subscription

```
      pip := &stripe.PaymentIntentParams{
		Amount:                 stripe.Int64(totalCost),
		Currency:               stripe.String(string(currency)),
		PaymentMethod:   "card_1F17NyAwfGMwqxjvUYAVIkIJ",
                // or 
                //Source:                "card_1F17NyAwfGMwqxjvUYAVIkIJ", 
		Customer:              &c.ID,
	}

	intent, err = paymentintent.New(pip)
```

this request results in POST request with body:

```
{
  "amount": "55",
  "currency": "usd",
  "customer": "cus_FW9VXTLCDXQUHS",
  "payment_method": "card_1F17NyAwfGMwqxjvUYAVIkIJ"
}
```

yet on the following invoice's charge -> default source is being charged:

```
{
...,
"payment_method": "card_1F17HIAwfGMwqxjvFiJtZFiE"
}
```

go version 0.1.12
stripe-go v61.19.0

**Comment by ronanamsterdam** [comment]
while described above might be a bug in API it self, but in currently sdk is missing DefaultPaymentMethodOverride option that can be set on the invoice item, but since I'm creating an intent -> I need that option in the intent. or `PaymentMethod`/`Source` to work as such.

Stipe's UI allows to do an override when doing custom invoice -> but no way to do it using sdk 🤷‍♂️

**Comment by remi-stripe** [comment]
@ronanamsterdam We don't have an option to confirm a PaymentIntent with a new PaymentMethod **and** make that PaymentMethod the default for future invoices in one API call.

You need to confirm that PaymentIntent first and separately update the Customer to make the new PaymentMethod the default for future invoices by setting `InvoiceSettings.DefaultPaymentMethod` as documented here: https://stripe.com/docs/api/customers/update#update_customer-invoice_settings-default_payment_method

Can you confirm that this answers your question? I was not sure that this was your ask!

**Comment by ronanamsterdam** [comment]
@remi-stripe yup that what I ended up doing(but setting a default source though). Though from UX perspective this feels weird as say I have card A(default) and card B and I'm paying with card B and when going back to the UI after payment my card B is set now to default.

Thanks though for the link 👍  -> will check that if `InvoiceSettings` works better for my case.
Would be great to have an `DefaultPaymentMethod` for invoices described more in the docs with relation to subscription, as it seems uncertain to what will happen with other subscriptions that user may have with current merchant? Will they now be billed to the new default payment method when the billing cycle repeats?

last one may be as well a support  question more, sorry if missadressing it)

**Comment by remi-stripe** [comment]
If you set `invoice_settings.default_payment_method`, that PaymentMethod will be used for all future Invoices payments (unless that invoice or invoice's subscription have `default_payment_method` set).

**Comment by ronanamsterdam** [comment]
@remi-stripe and to anyone who may stumble upon this ->  tried setting `invoice_settings.default_payment_method` -> so it works exactly the same as setting  `Customer.DefaultSource` for user -> in both cases user's default payment source will be set to the one used used in the transaction. No way to override it just for that invoice.

**Comment by remi-stripe** [comment]
@ronanamsterdam You can definitely update the default `PaymentMethod` for a specific `Invoice` object: https://stripe.com/docs/api/invoices/update#update_invoice-default_payment_method
