### ISSUE TITLE
Early Fraud Warnings incorrect URL

### ISSUE THREAD

**Issue by danhilltech** [stripe/stripe-go#917]
I'm attempting to use the early fraud warnings API endpoints, but I think the URL in the library may be wrong?

I'm using stripe-go v62.1.0 against API version 2019-08-14.

Code:
```
import (
"github.com/stripe/stripe-go/radar/earlyfraudwarning"
...
)

params := &stripe.RadarEarlyFraudWarningListParams{}
		params.Filters.AddFilter("charge", "", chrg.ID)
		
i := earlyfraudwarning.List(params)
		for i.Next() {
			r := i.RadarEarlyFraudWarning()
			if r != nil && !thisCharge.FraudStripe.Valid {
				thisCharge.FraudStripe = makeNullString(string(r.FraudType))
			}

		}
```

I receive this error:

```
Request error from Stripe: {"status":404,"message":"Unrecognized request URL (GET: /v1/issuer_fraud_records). Please see https://stripe.com/docs or we can help at https://support.stripe.com/.","request_id":"...","type":"invalid_request_error"}
```

In the library the URL is `/v1/issuer_fraud_records`:

https://github.com/stripe/stripe-go/blob/9a482751051238d15bd59b12138ce8cf44d3803b/radar/earlyfraudwarning/client.go#L42

Yet according to the docs it's `curl https://api.stripe.com/v1/radar/early_fraud_warnings`

https://stripe.com/docs/api/early_fraud_warnings/retrieve?lang=curl

(Also, the Go docs here don't seem to compile?)

Thanks!

**Comment by remi-stripe** [comment]
@danhilltech Thanks for the thorough report and sorry about the bug here. `IssuerFraudRecord` is the old name of the feature when it was in beta and it looks like we missed fixing the URL. I've opened a PR and we'll release a fix shortly

**Comment by danhilltech** [comment]
Thanks! If you're able to look too, the docs on your site I think are incorrect:

<img width="603" alt="Screen Shot 2019-08-15 at 5 03 47 PM" src="https://user-images.githubusercontent.com/876990/63126786-ab2abc80-bf7e-11e9-93d0-87cbf0a671e0.png">

It wouldn't remotely compile for me.

**Comment by remi-stripe** [comment]
@danhilltech The fix has been released for the library and we're working on fixing the API reference!

**Comment by danhilltech** [comment]
Thanks! Verified it's working.
