### ISSUE TITLE
PaymentMethodListParams.Customer, .Type don't work

### ISSUE THREAD

**Issue by rothskeller** [stripe/stripe-go#919]
The Customer and Type fields of the PaymentMethodListParams structure appear to be ignored.  Those criteria need to be supplied with AddFilter instead.  Why are those fields there if they don't work?

**Comment by remi-stripe** [comment]
@rothskeller I just tested on my end and the parameters work as expected for me. Here's some sample code:

```
    params := &stripe.PaymentMethodListParams{
        Customer: stripe.String("cus_123"),
        Type: stripe.String(string(stripe.PaymentMethodTypeCard)),
    }
    i := paymentmethod.List(params)
    for i.Next() {
        p := i.PaymentMethod()
        fmt.Printf("Got: \n", p)  
    } 
```

Can you clarify if the code doesn't work for you or if you were just confused by the example in our API reference (which I will be fixing now)?

**Comment by rothskeller** [comment]
I was confused by the example in the API reference as well as by the fact that there is no reference to those fields in the code for the paymentmethod.List method.  I didn't realize that stripe.GetIter uses reflection.  Tricky. :-)

**Comment by remi-stripe** [comment]
Gotcha, sorry for the confusion! Going to close this our but let me know if anything is confusing!
