### ISSUE TITLE
Create customer | With subscription

### ISSUE THREAD

**Issue by skorpionas777** [stripe/stripe-go#92]
{"type":"invalid_request_error","message":"Invalid timestamp: must be an integer Unix timestamp in the future.","param":"trial_end"}

It would be good if:

&CustomerParams{TrialEndNow: true}

Thanks.

**Comment by cosn** [comment]
Makes sense, will fix

**Comment by cosn** [comment]
Are you trying to create a customer with a subscription whose trial expires immediately? May I ask what the scenario is?

**Comment by skorpionas** [comment]
Yes, add coupon discount. Scenarios or start trial or start with discount coupon (and update subscription have SubParams "TrialEndNow")
