### ISSUE TITLE
Creating payment method arguments documentation are different from this library

### ISSUE THREAD

**Issue by dbarzdys** [stripe/stripe-go#920]
While programming I found that `PaymentMethodParams` struct contains `Customer`
https://github.com/stripe/stripe-go/blob/405d49fc661018b60477d1160e5ae65e7c25b823/paymentmethod.go#L69

But API documentation does not list it under allowed arguments
https://stripe.com/docs/api/payment_methods/create?lang=go

How does it work? Does it automatically attaches customer to new payment method or is it not even used for creating new payment methods?

**Comment by remi-stripe** [comment]
@dbarzdys Sorry about the confusion here. You're right that this parameter does not work in the API. You have to create the `PaymentMethod` and then separately attach it to a `Customer`

**Comment by remi-stripe** [comment]
Opened a PR to clearly mention this parameter never worked and we will remove it in the next major version!

**Comment by XplittR** [comment]
Removing this parameter removed the possibility to share a payment-method from a platform-account to a connected account.

After recommendation from "@karllekko" on #stripe on freenode IRC, a workaround is to use https://godoc.org/github.com/stripe/stripe-go#ExtraValues to manually add the Customer-parameter back.

Maybe another endpoint should be created for sharing payment-methods that take a `ClonePaymentMethodParams`/`PaymentMethodCloneParams` struct or similar?

**Comment by remi-stripe** [comment]
Opened a fix in https://github.com/stripe/stripe-go/pull/983 sorry for the trouble here
