### ISSUE TITLE
Refund struct missing failure_reason

### ISSUE THREAD

**Issue by jredl-va** [stripe/stripe-go#929]
When implementing the stripe refund webhook it seems as though `failure_reason` is missing from the struct: https://github.com/stripe/stripe-go/blob/master/refund.go#L48

Link to the documentation: https://stripe.com/docs/api/refunds/object

Is there any specific reason that this field is excluded? 
Would you accept a PR adding this field?

**Comment by remi-stripe** [comment]
@jredl-va No specific reason except that we must have missed that field. I can take the fix if you want but we would definitely love a PR if you're up for doing the work :)

**Comment by jredl-va** [comment]
If you have the time it would be most appreciated. We have for the time being implemented our own   proxy object that contains this field when unmarshalling.

**Comment by remi-stripe** [comment]
@jredl-va This was fixed in 62.5.0, thanks again for the report!

**Comment by jredl-va** [comment]
Thanks for the quick turn around!
