### ISSUE TITLE
#935 (merged yesterday) logs a error level for every 402

### ISSUE THREAD

**Issue by yareid** [stripe/stripe-go#936]
Using stripe-go 62.7.0
Golang 1.11.x and 1.12.x

This commit https://github.com/stripe/stripe-go/commit/53c32f1222679822a5b9ebb90c7c6abdaa09ad97 moves `s.LeveledLogger.Errorf("Request failed with body: %s (status: %v)" ...` before the `!s.shouldRetry(err, req, res, retry)` check.

Previously `shouldRetry()` returned `false` for 402 responses causing the logging to be skipped.  Now 402s are always logged as Errors.  I presume this change is unintentional given that 402 does not represent an unexpected error?

**Comment by brandur-stripe** [comment]
It wasn't unintentional (in that the goal of the PR was to change something else), but on the other hand, I'm not sure that it's the worst thing that some kind of logging is made on a 402, which is still a failed request. I'll take a look at this a little later today.

**Comment by yareid** [comment]
Yeah, the goal of the PR looks good.  However the practical result of moving the test below the logging is that *our* error log is now full of these - which from an e-commerce perspective are entirely expected responses and not errors (or warnings which is how _we_ log Stripe errors).
```json
2019-08-29T19:30:48.000Z WARN PaymentProcessor: Request failed with body: {
  "error": {
    "charge": "ch_1FCtK[redacted]",
    "code": "card_declined",
    "decline_code": "insufficient_funds",
    "doc_url": "https://stripe.com/docs/error-codes/card-declined",
    "message": "Your card has insufficient funds.",
    "type": "card_error"
  }
}
 (status: 402)
```
IIRC 402 response bodies were previously logged (by stripe-go) at debug level along with all other response bodies.

**Comment by brandur-stripe** [comment]
Alright, we're likely to change this back in #938.
