### ISSUE TITLE
Regression: Impossible to remove coupon from subscription via API

### ISSUE THREAD

**Issue by inoda** [stripe/stripe-go#940]
`stripe-go` version: `github.com/stripe/stripe-go v60.18.0+incompatible`

From https://stripe.com/docs/api/subscriptions/update#update_subscription-coupon:
> This can be unset by updating the value to null and then saving.

The following call does not remove the coupon from subscription `subID`. 

```
subParams := &stripe.SubscriptionParams{}
sub.Update(subID, subParams)
```

I don't think it *should* remove the coupon, since I wouldn't want to have to make sure `Coupon` is specified every time I want to update other attributes while leaving the coupon alone. I see in an older version, there was a `CouponEmpty` param: https://github.com/stripe/stripe-go/pull/372 (original issue: https://github.com/stripe/stripe-go/issues/370). Looks like in the more recent version this has been removed and there is no way to actually specify a null coupon.

**Comment by remi-stripe** [comment]
@inoda The stripe-go library now uses pointers for all parameters. This allows you to pass an empty string explicitly in the parameter to unset the coupon instead of using the old `CouponEmpty` approach.

I've just tried this code on my end which works:

```
  sub, err := sub.Update(
    "sub_123",
    &stripe.SubscriptionParams{
      Coupon: stripe.String(""),
    },
  )
```
