### ISSUE TITLE
Getting active subscriptions for users have product details blank

### ISSUE THREAD

**Issue by Nirmal-Vatsyayan** [stripe/stripe-go#942]
using - 

go version go1.12.7 darwin/amd64
stripe-go version 2019-08-14

Getting active subscription in test scenario for a user do not returns any product information even when product is active on test dashboard. It says active = false and name is blank in product. I am executing this using stripe test key. Also the days_until_due field in subscription is always 0 even if in dashboard it's showing valid days left in subscription.

Below is the code snippet executed.
  
       // get the customer
       customer, _ := customer.Get(
		<customer id>,
		nil,
	)

        //get all subscription for the customer
	var ret_val []*stripe.Subscription
	params := &stripe.SubscriptionListParams{}
	params.Filters.AddFilter("customer", "", customer.ID)
	i := sub.List(params)
	for i.Next() {
		s := i.Subscription()
		ret_val = append(ret_val, s)
	}

  It returns all active subscriptions for the user but product information is missing. Product response is below:

   "product": {
            "active": false,
            "attributes": null,
            "caption": "",
            "created": 0,
            "deactivate_on": null,
            "description": "",
            "id": <a valid product id>,
            "images": null,
            "livemode": false,
            "metadata": null,
            "name": "",
            "package_dimensions": null,
            "shippable": false,
            "statement_descriptor": "",
            "type": "",
            "unit_label": "",
            "url": "",
            "updated": 0
   }

**Comment by remi-stripe** [comment]
My guess here is that you're looking at `sub.Plan.Product`. The latter is not expanded by default so only the Product id is returned on a Plan object as documented here: https://stripe.com/docs/api/plans/object#plan_object-product

If you want the Product you need to expand it by expanding `data.plan.product` like this:

```
var ret_val []*stripe.Subscription
params := &stripe.SubscriptionListParams{}
params.Filters.AddFilter("customer", "", customer.ID)
params.AddExpand("data.plan.product")
i := sub.List(params)
for i.Next() {
	s := i.Subscription()
	ret_val = append(ret_val, s)
}
```
