### ISSUE TITLE
Missing error code constant for "authentication_required"

### ISSUE THREAD

**Issue by atombender** [stripe/stripe-go#956]
Here's an error response:

```
POST /v1/payment_intents HTTP/1.1
[...]

{
  "error": {
    "charge": "ch_1FMGfoGX8CD6YzDIHLXlIpfv",
    "code": "authentication_required",
    "decline_code": "authentication_required",
    "message": "Your card was declined. This transaction requires authentication.",
    "payment_intent": {...},
    "payment_method": {...},
    "type": "card_error"
  }
}
```

which gets translated to this Go struct:

```go
&stripe.Error{
  ChargeID: "ch_1FMGfoGX8CD6YzDIHLXlIpfv",
  Code: "authentication_required",
  DocURL: "",
  Err: &stripe.CardError{
    DeclineCode: "authentication_required",
  },
  HTTPStatusCode: 402,
  Msg: "Your card was declined. This transaction requires authentication.",
  Param: "",
  PaymentIntent: &stripe.PaymentIntent{...},
  PaymentMethod: &stripe.PaymentMethod{...},
  RequestID: "req_Yumn8SEwstsQpA",
  SetupIntent: nil,
  Source: nil,
  Type: "card_error",
  OAuthError: "",
  OAuthErrorDescription: "",
}
```

Notice `Code`, which is a `stripe.ErrorCode`, is `"authentication_required"`. But while stripe-go's `errors.go` has `DeclineCodeAuthenticationRequired`, there's no `ErrorCodeAuthenticationRequired`.

**Comment by remi-stripe** [comment]
@atombender Thanks for the report. I've opened a PR to fix https://github.com/stripe/stripe-go/pull/957

**Comment by atombender** [comment]
@remi-stripe Thanks!

**Comment by atombender** [comment]
@remi-stripe It looks like the `stripe.Error` also is missing the `decline_code` as a Go field. Should this not be returned as a `CardError` (which has that field)?

**Comment by remi-stripe** [comment]
@atombender I'm not sure I follow what you mean here. I see `DeclineCode` on `Error`: https://github.com/stripe/stripe-go/blob/master/error.go#L175

**Comment by atombender** [comment]
@remi-stripe I upgraded 12 days ago and you added `DeclineCode` [11 days ago](https://github.com/stripe/stripe-go/commit/5b60a476321f7b016ed4f107fa66e90d97167de3). 🙂 
 Thanks, should've tried upgrading before asking.

**Comment by remi-stripe** [comment]
Ah gotcha, I was worried for a minute that my fix was done incorrectly :)

**Comment by atombender** [comment]
But speaking of, is `DeclineCode` empty if it does not apply? It's a `string`, not `*string`.

My app's heuristic is that an off-session card is declined (`err.DeclineCode != ""`), it can be retried by notifying the user and asking them to rectify the problem (add funds, enter new card details, etc.). I don't see any other way in the API to distinguish between hard errors (e.g. invalid API key) and something that is on the customer end, other than doing a `switch` on all the error codes that seem to indicate customer error. There's an overlap between the set of codes in `ErrorCode` and `DeclineCode` which makes this less clear, too.

**Comment by remi-stripe** [comment]
Correct, if you send bad parameters for example `DeclineCode` won't apply and will be empty (an empty string) and you'd ignore it.

That's why it originally was not top-level but it made it confusing for other developers!

Really `DeclineCode` matter when you try to charge a card and it fails because it was declined and `Code` is a "developer-focused" error code that you can use to catch specific issues.

**Comment by atombender** [comment]
Got it, that's perfect! Thanks again.
