### ISSUE TITLE
PaymentMethodDetachParams

### ISSUE THREAD

**Issue by layby42** [stripe/stripe-go#958]
PaymentMethodDetachParams: has Customer, attempt to provide value results in 

{"code":"parameter_unknown","doc_url":"....","status":400,"message":"Received unknown parameter: customer","param":"customer","request_id":"req_XXXX","type":"invalid_request_error"}

**Comment by remi-stripe** [comment]
@layby42 Thanks for the report! I'll add a comment to mark it as incorrect and we'll remove it in the next major version!
