### ISSUE TITLE
Expose logger

### ISSUE THREAD

**Issue by wyattjoh** [stripe/stripe-go#97]
I have a use case where I need to track transactions going across my application. Each request has a unique ID which I attach to the log entry. I propose that instead of using the `log` package as it is seen [here](https://github.com/stripe/stripe-go/blob/3e087c3123b07601e1409d0cd660f62db0819195/stripe.go#L258), that a `Logger` variable be added as a package level variable to `stripe.go` where the whole package could log to instead. This would allow runtime customization of the logging prefix, and level to a much higher degree then the `stripe.LogLevel` variable gives.

Could create a new logger in an `init` function as:

```go
var Logger *log.Logger

func init() {
    ...
    Logger = log.New(os.Stderr, "", log.LstdFlags)
    ...
}
```

Then customizations could be done with `stripe.Logger.SetPrefix` or `stripe.Logger.SetFlags`.

**Comment by cosn** [comment]
Sorry for the delay on this!

Not opposed to the idea. Any interest in submitting a PR?

**Comment by wyattjoh** [comment]
Sure can.

**Comment by wyattjoh** [comment]
Is it required that the PR be backwards compatible with the previous `LogLevel` option?
