### ISSUE TITLE
Require multiple Stripe keys on same AppEngine instances, yet stripe.Key is global

### ISSUE THREAD

**Issue by krolaw** [stripe/stripe-go#971]
We're moving into another country and setting up a new legal entity to collect application_fees (thought connect) within that country. We want to reuse the same appengine project/domains infrastructure etc and select the correct StripeKey per request depending on whether it's for this other country.

Alas, stripe.Key is global, instead of something like `s := stripe.New(key)`, making setting the correct StripeKey on each request really difficult. Overriding headers in params, might work (unsure), but it's not exactly a clean solution. Individual BackendImplementations might work, but that's getting pretty low level as we can't use the common functions.

Thoughts?

**Comment by ob-stripe** [comment]
Hi @krolaw. You can create different client instances and set different API keys per client: https://github.com/stripe/stripe-go#with-a-client

Would that work for your use case?

**Comment by krolaw** [comment]
I think it would. Sorry for the noise.

**Comment by ob-stripe** [comment]
No worries at all!
