### ISSUE TITLE
Filter "limit" is not applied to List-queries

### ISSUE THREAD

**Issue by remnestal** [stripe/stripe-go#982]
**go version go1.13 darwin/amd64**
**stripe-go v66.1.1**

Hey, I'm having trouble getting the `"limit"` filter to work when invoking `stripe-go/invoice.List`; just like the example provided in the [Invoices API docs](https://stripe.com/docs/api/invoices/list?lang=go):
```go
params := &stripe.InvoiceListParams{}
params.Filters.AddFilter("limit", "", "3")
i := invoice.List(params)
for i.Next() {
  invoice := i.Invoice()
}
```

However, I end up with an iterator for every single invoice in the system.

I then tried to do the same with `stripe-go/plans.List` to see if I did something wrong with the invoice-resource in particular and had the same results; an iterator for every plan in the system. For that attempt I used the corresponding example snippet in the [Plans API doc](https://stripe.com/docs/api/plans/list?lang=go):
```go
params := &stripe.PlanListParams{}
params.Filters.AddFilter("limit", "", "3")
i := plan.List(params)
for i.Next() {
  plan := i.Plan()
}
```
Maybe I'm missing something,  but it seems to me like `"limit"` is not being applied in either case.

**Comment by remi-stripe** [comment]
@remnestal `limit` is applied here and decides how many items to get in each "page" that we fetch from the API.

Our client libraries support auto-pagination as documented [here](https://stripe.com/docs/api/pagination/auto?lang=go) which lets you loop over all items matching your query without having to handle the logic yourself of fetching the next page, checking if there are more items, etc.

With stripe-go, auto-pagination is built-in automatically and you always loop over all elements. If you only care about the first page of items, you can explicitly ask for a single page using `params.ListParams.Single = true` like this:

```
params := &stripe.PlanListParams{}
params.Filters.AddFilter("limit", "", "3")
params.ListParams.Single = true
i := plan.List(params)
for i.Next() {
  plan := i.Plan()
}
```

**Comment by ibeckermayer** [comment]
@remi-stripe it would be helpful if you added this more detailed explanation about how the `"limit"` feature works with auto-pagination. It's a really nice API, but the documentation isn't clear that that's how it works.

**Comment by remi-stripe** [comment]
@ibeckermayer do you have specific changes in mind? The auto-pagination just keeps your default filters/options and uses this on each calls to the API to get the next page.

**Comment by ibeckermayer** [comment]
Suggestion:

> Our libraries support auto-pagination. This feature easily handles fetching large lists of resources without having to manually paginate results and perform subsequent requests.

> Auto-pagination in Go is enabled by default. Under the hood, the iterator returned by any `List` function handles the logic for checking if there are more items and fetching the next page if there are. It can be disabled by setting the `Single` option to `true` in any `ListParams` struct.

It might also be broadly helpful to users to update the example with error checking. OTOH I'm relatively new to `go` and so maybe this is a well known pattern that need not be specified, but just a possibility:

```go
stripe.Key = "sk_test_XXXXXX"

params := &stripe.CustomerListParams{}
params.Filters.AddFilter("limit", "", "3")
i := customer.List(params)
for i.Next() {
  customer := i.Customer()
  // Do something with customer
}

if err := iter.Err(); err != nil {
  panic("error listing customers")
}
```

**Comment by remi-stripe** [comment]
Thanks for the feedback! The way the docs work, we can't really tweak the main text specifically for Go so that kind of edit will be a bit tricky. As for error handling, it's a common go pattern and we want the examples to be as simple as possible, otherwise they can seem overwhelming!
 I'll flag it internally though to see how we can improve this!

**Comment by paulasjes-stripe** [comment]
Considering the iterative nature of `Next()`  as a Go pattern, this behaviour is expected. This snippet might help as it shows how to loop over just the "page" that was initially retrieved:

```
params := &stripe.CustomerListParams{}
params.Filters.AddFilter("limit", "", "5")
i := customer.List(params)

// Should print "5", as that's the total amount of customers per "page" we requested
fmt.Printf("%v\n", len(i.CustomerList().Data))

// Print all the customer IDs we have on this "page"
for n := range i.CustomerList().Data {
	c := i.CustomerList().Data[n]
	fmt.Printf("%s\n", c.ID)
}

// Print all customers on this account, till  i.Next() doesn't return anything
for i.Next() {
	c := i.Customer()
	// Will print customer IDs in increments of 5 until we run out of customers on this account
	fmt.Printf("%s\n", c.ID)
}
```

**Comment by ibeckermayer** [comment]
@paulasjes-stripe that looks great
