### ISSUE TITLE
CustomerParams struct missing metadata attribute

### ISSUE THREAD

**Issue by temesxgn** [stripe/stripe-go#990]
Stripe Go Version: v67.3.0
Currently there is not a way to add metadata info to Customer object since CustomerParams does not specify it

**Comment by remi-stripe** [comment]
@temesxgn The stripe-go library handles metadata a bit differently from most libraries. All our types for parameters  have an embedded `Params` which handles metadata for you. The way you add metadata is documented [here](https://stripe.com/docs/api/metadata).

For Customer it would look like this:

```
params := &stripe.CustomerParams{
  Description: stripe.String("Description"),
  Currency: stripe.String("usd"),
}
params.AddMetadata("order_id", "6735")
customer.New(params)
```
